using System.Text;

namespace DotMatter.CodeGen;

/// <summary>Emits C# source code from a ClusterModel — smart instance classes with async commands.</summary>
static class ClusterCodeEmitter
{
    public static string Emit(ClusterModel cluster, string xmlFileName)
    {
        var localTypes = new HashSet<string>();
        var enumNames = new HashSet<string>();
        var structNames = new HashSet<string>();
        var enumUnderlyingTypes = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var e in cluster.Enums)
        {
            var n = Naming.ToPascalCase(e.Name);
            localTypes.Add(n);
            enumNames.Add(n);
            enumUnderlyingTypes[n] = ResolveEnumBase(e);
        }
        foreach (var b in cluster.Bitmaps)
        {
            var n = Naming.ToPascalCase(b.Name);
            localTypes.Add(n);
            enumNames.Add(n);
            enumUnderlyingTypes[n] = ResolveBitmapBase(b);
        }
        foreach (var s in cluster.Structs)
        {
            var n = Naming.ToPascalCase(s.Name);
            localTypes.Add(n);
            structNames.Add(n);
        }
        var structMap = cluster.Structs.ToDictionary(s => Naming.ToPascalCase(s.Name), StringComparer.Ordinal);

        var sb = new StringBuilder();

        EmitHeader(sb, cluster, xmlFileName);

        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using DotMatter.Core.InteractionModel;");
        sb.AppendLine("using DotMatter.Core.Sessions;");
        sb.AppendLine("using DotMatter.Core.TLV;");
        sb.AppendLine();
        sb.AppendLine("namespace DotMatter.Core.Clusters;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>{Naming.EscapeXml(cluster.Name)} (0x{cluster.Id:X4}, rev {cluster.Revision})</summary>");
        sb.AppendLine($"public class {cluster.CSharpName}Cluster : ClusterBase");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Matter cluster identifier.</summary>");
        sb.AppendLine($"    public const uint ClusterId = 0x{cluster.Id:X4};");
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    protected override uint GetClusterId() => ClusterId;");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Creates a new <see cref=\"{cluster.CSharpName}Cluster\"/> bound to the given session and endpoint.</summary>");
        sb.AppendLine($"    public {cluster.CSharpName}Cluster(ISession session, ushort endpointId = 1)");
        sb.AppendLine("        : base(session, endpointId) { }");

        EmitFeatures(sb, cluster);
        EmitEnums(sb, cluster);
        EmitBitmaps(sb, cluster);
        EmitStructs(sb, cluster, localTypes);
        EmitStructSerializers(sb, cluster, localTypes, enumNames, structNames, enumUnderlyingTypes);
        EmitAttributeConstants(sb, cluster);
        EmitCommandConstants(sb, cluster);
        EmitEventConstants(sb, cluster);
        EmitAsyncCommands(sb, cluster, localTypes, enumNames, structNames, enumUnderlyingTypes, structMap);
        EmitAttributeReaders(sb, cluster, localTypes, enumNames);

        sb.AppendLine("}");
        return sb.ToString();
    }

    static void EmitHeader(StringBuilder sb, ClusterModel cluster, string xmlFileName)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).");
        sb.AppendLine($"// XML: {xmlFileName}");
        sb.AppendLine($"// Cluster: {cluster.Name} (0x{cluster.Id:X4})");
        sb.AppendLine("// To regenerate: dotnet run --project DotMatter.CodeGen");
        sb.AppendLine();
    }

    static void EmitFeatures(StringBuilder sb, ClusterModel cluster)
    {
        if (cluster.Features.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Feature flags for this cluster.</summary>");
        sb.AppendLine("    [System.Flags]");
        sb.AppendLine("    public enum Feature : uint");
        sb.AppendLine("    {");
        foreach (var f in cluster.Features)
        {
            if (!string.IsNullOrEmpty(f.Summary))
            {
                sb.AppendLine($"        /// <summary>{Naming.EscapeXml(f.Summary)}</summary>");
            }
            else
            {
                sb.AppendLine($"        /// <summary>{Naming.EscapeXml(f.Name)} feature.</summary>");
            }

            sb.AppendLine($"        {Naming.ToPascalCase(f.Name)} = 1u << {f.Bit},");
        }
        sb.AppendLine("    }");
    }

    static void EmitEnums(StringBuilder sb, ClusterModel cluster)
    {
        foreach (var e in cluster.Enums)
        {
            string name = Naming.ToPascalCase(e.Name);
            string baseType = ResolveEnumBase(e);
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Naming.EscapeXml(e.Name)} enum values.</summary>");
            sb.AppendLine($"    public enum {name} : {baseType}");
            sb.AppendLine("    {");
            var seen = new HashSet<string>();
            foreach (var v in e.Values)
            {
                string vName = Naming.ToPascalCase(v.Name);
                if (!seen.Add(vName))
                {
                    continue;
                }

                if (!string.IsNullOrEmpty(v.Summary))
                {
                    sb.AppendLine($"        /// <summary>{Naming.EscapeXml(v.Summary)}</summary>");
                }
                else
                {
                    sb.AppendLine($"        /// <summary>{Naming.EscapeXml(v.Name)} value.</summary>");
                }

                sb.AppendLine($"        {vName} = {FormatEnumValueLiteral(v.Value, baseType)},");
            }
            sb.AppendLine("    }");
        }
    }

    static void EmitBitmaps(StringBuilder sb, ClusterModel cluster)
    {
        foreach (var b in cluster.Bitmaps)
        {
            string name = Naming.ToPascalCase(b.Name);
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Naming.EscapeXml(b.Name)} bitmap flags.</summary>");
            sb.AppendLine("    [System.Flags]");
            sb.AppendLine($"    public enum {name} : uint");
            sb.AppendLine("    {");
            var seen = new HashSet<string>();
            foreach (var bit in b.Bits)
            {
                string bitName = Naming.ToPascalCase(bit.Name);
                if (!seen.Add(bitName))
                {
                    continue;
                }

                if (!string.IsNullOrEmpty(bit.Summary))
                {
                    sb.AppendLine($"        /// <summary>{Naming.EscapeXml(bit.Summary)}</summary>");
                }
                else
                {
                    sb.AppendLine($"        /// <summary>{Naming.EscapeXml(bit.Name)} flag.</summary>");
                }

                sb.AppendLine($"        {bitName} = 1u << {bit.Bit},");
            }
            sb.AppendLine("    }");
        }
    }

    static void EmitStructs(StringBuilder sb, ClusterModel cluster, HashSet<string> localTypes)
    {
        foreach (var s in cluster.Structs)
        {
            string name = Naming.ToPascalCase(s.Name);
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>{Naming.EscapeXml(s.Name)} struct.</summary>");
            sb.AppendLine($"    public sealed class {name}");
            sb.AppendLine("    {");
            foreach (var f in s.Fields)
            {
                string csType = Naming.MapCSharpType(f.Type, f.Nullable, f.Optional, f.IsArray, f.EntryType, localTypes);
                string fName = Naming.ToPascalCase(f.Name);
                string init = Naming.NeedsDefaultInit(csType) ? " = default!;" : "";
                sb.AppendLine($"        /// <summary>Gets or sets {Naming.EscapeXml(f.Name)}.</summary>");
                sb.AppendLine($"        public {csType} {fName} {{ get; set; }}{init}");
            }
            sb.AppendLine("    }");
        }
    }

    static void EmitStructSerializers(
        StringBuilder sb,
        ClusterModel cluster,
        HashSet<string> localTypes,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes)
    {
        if (cluster.Structs.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    // TLV struct serializers");

        foreach (var s in cluster.Structs)
        {
            string name = Naming.ToPascalCase(s.Name);

            sb.AppendLine();
            sb.AppendLine($"    private static void Write{name}(MatterTLV tlv, byte tag, {name} value)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
            sb.AppendLine("        tlv.AddStructure(tag);");
            sb.AppendLine($"        Write{name}Fields(tlv, value);");
            sb.AppendLine("        tlv.EndContainer();");
            sb.AppendLine("    }");

            sb.AppendLine();
            sb.AppendLine($"    private static void Write{name}(MatterTLV tlv, {name} value)");
            sb.AppendLine("    {");
            sb.AppendLine("        ArgumentNullException.ThrowIfNull(value);");
            sb.AppendLine("        tlv.AddStructure();");
            sb.AppendLine($"        Write{name}Fields(tlv, value);");
            sb.AppendLine("        tlv.EndContainer();");
            sb.AppendLine("    }");

            sb.AppendLine();
            sb.AppendLine($"    private static void Write{name}Fields(MatterTLV tlv, {name} value)");
            sb.AppendLine("    {");
            foreach (var f in s.Fields)
            {
                string csType = Naming.MapCSharpType(f.Type, f.Nullable, f.Optional, f.IsArray, f.EntryType, localTypes);
                string accessor = $"value.{Naming.ToPascalCase(f.Name)}";
                string? tlvCall = EmitTlvWrite(f, accessor, csType, localTypes, enumNames, structNames, enumUnderlyingTypes);
                if (tlvCall != null)
                {
                    sb.AppendLine($"        {tlvCall}");
                }
            }
            sb.AppendLine("    }");
        }
    }

    // ── Attribute Constants (backward-compatible) ────────────────

    static void EmitAttributeConstants(StringBuilder sb, ClusterModel cluster)
    {
        if (cluster.Attributes.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Attribute identifiers.</summary>");
        sb.AppendLine("    public static class Attributes");
        sb.AppendLine("    {");
        foreach (var a in cluster.Attributes)
        {
            sb.AppendLine($"        /// <summary>{Naming.EscapeXml(a.Name)} (0x{a.Id:X4}).</summary>");
            sb.AppendLine($"        public const uint {Naming.ToPascalCase(a.Name)} = 0x{a.Id:X4};");
        }
        sb.AppendLine("    }");
    }

    // ── Command Constants (backward-compatible) ──────────────────

    static void EmitCommandConstants(StringBuilder sb, ClusterModel cluster)
    {
        var clientCmds = cluster.Commands.Where(c => c.IsClientToServer).ToList();
        if (clientCmds.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Command identifiers.</summary>");
        sb.AppendLine("    public static class Commands");
        sb.AppendLine("    {");
        foreach (var c in clientCmds)
        {
            sb.AppendLine($"        /// <summary>{Naming.EscapeXml(c.Name)} (0x{c.Id:X4}).</summary>");
            sb.AppendLine($"        public const uint {Naming.ToPascalCase(c.Name)} = 0x{c.Id:X4};");
        }
        sb.AppendLine("    }");
    }

    // ── Event Constants ──────────────────────────────────────────

    static void EmitEventConstants(StringBuilder sb, ClusterModel cluster)
    {
        if (cluster.Events.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    /// <summary>Event identifiers.</summary>");
        sb.AppendLine("    public static class Events");
        sb.AppendLine("    {");
        foreach (var e in cluster.Events)
        {
            sb.AppendLine($"        /// <summary>{Naming.EscapeXml(e.Name)} (0x{e.Id:X4}).</summary>");
            sb.AppendLine($"        public const uint {Naming.ToPascalCase(e.Name)} = 0x{e.Id:X4};");
        }
        sb.AppendLine("    }");
    }

    // ── Async Command Methods ────────────────────────────────────

    static void EmitAsyncCommands(
        StringBuilder sb,
        ClusterModel cluster,
        HashSet<string> localTypes,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes,
        Dictionary<string, StructModel> structMap)
    {
        var clientCmds = cluster.Commands.Where(c => c.IsClientToServer).ToList();
        if (clientCmds.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    // Async command methods");

        foreach (var cmd in clientCmds)
        {
            string methodName = Naming.ToPascalCase(cmd.Name) + "Async";
            var unsupportedFields = GetUnsupportedCommandFields(cmd, localTypes, enumNames, structNames, enumUnderlyingTypes, structMap);

            if (cmd.Fields.Count == 0)
            {
                // No-arg command: simple one-liner
                sb.AppendLine();
                sb.AppendLine($"    /// <summary>Send {Naming.EscapeXml(cmd.Name)} command (0x{cmd.Id:X4}).</summary>");
                sb.AppendLine($"    public Task<InvokeResponse> {methodName}(CancellationToken ct = default)");
                sb.AppendLine($"        => InvokeCommandAsync(0x{cmd.Id:X4}, ct: ct);");
            }
            else
            {
                // Command with fields: build parameters and TLV serialization
                var paramEntries = new List<(string param, bool isOptional)>();
                var tlvLines = new List<string>();

                foreach (var f in cmd.Fields)
                {
                    string csType = Naming.MapCSharpType(f.Type, f.Nullable, f.Optional, f.IsArray, f.EntryType, localTypes);
                    string paramName = Naming.ToCamelCase(f.Name);
                    string defaultVal = f.Optional ? " = default" : "";
                    paramEntries.Add(($"{csType} {paramName}{defaultVal}", f.Optional));

                    string? tlvCall = EmitTlvWrite(f, paramName, csType, localTypes, enumNames, structNames, enumUnderlyingTypes);
                    if (tlvCall != null)
                    {
                        tlvLines.Add(tlvCall);
                    }
                }

                // Sort: required params first, then optional, then CancellationToken
                var paramList = paramEntries
                    .Where(p => !p.isOptional).Select(p => p.param)
                    .Concat(paramEntries.Where(p => p.isOptional).Select(p => p.param))
                    .Append("CancellationToken ct = default")
                    .ToList();

                sb.AppendLine();
                sb.AppendLine($"    /// <summary>Send {Naming.EscapeXml(cmd.Name)} command (0x{cmd.Id:X4}).</summary>");

                string allParams = string.Join(",\r\n        ", paramList);
                sb.AppendLine($"    public Task<InvokeResponse> {methodName}(");
                sb.AppendLine($"        {allParams})");

                if (unsupportedFields.Count > 0)
                {
                    sb.AppendLine($"        => UnsupportedCommandAsync(\"{Naming.EscapeXml(BuildUnsupportedCommandDetail(cmd.Name, unsupportedFields))}\");");
                }
                else if (tlvLines.Count == 1)
                {
                    sb.AppendLine($"        => InvokeCommandAsync(0x{cmd.Id:X4}, tlv => {{ {tlvLines[0]} }}, ct);");
                }
                else
                {
                    sb.AppendLine($"        => InvokeCommandAsync(0x{cmd.Id:X4}, tlv =>");
                    sb.AppendLine("        {");
                    foreach (var line in tlvLines)
                    {
                        sb.AppendLine($"            {line}");
                    }

                    sb.AppendLine("        }, ct);");
                }
            }
        }
    }

    /// <summary>Emit a single TLV write call for a command field.</summary>
    static string? EmitTlvWrite(
        FieldModel field,
        string paramName,
        string csType,
        HashSet<string> _,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes)
    {
        uint tag = field.Id;
        string baseType = csType.TrimEnd('?');

        // Handle optional fields with null check
        bool isOptional = csType.EndsWith('?') && !field.IsArray;
        string prefix = isOptional ? $"if ({paramName} != null) " : "";

        // Value access for nullable value types
        string val = isOptional && Naming.IsValueType(baseType) ? $"{paramName}.Value" : paramName;

        if (field.IsArray)
        {
            // Extract element type: "ushort[]" → "ushort", "byte[][]" → "byte[]"
            string elementType = baseType.EndsWith("[]") ? baseType[..^2] : baseType;
            return EmitArrayWrite(field, paramName, elementType, tag, enumNames, structNames, enumUnderlyingTypes);
        }

        return baseType switch
        {
            "bool" => $"{prefix}tlv.AddBool({tag}, {val});",
            "byte" => $"{prefix}tlv.AddUInt8({tag}, {val});",
            "sbyte" => $"{prefix}tlv.AddInt8({tag}, {val});",
            "ushort" => $"{prefix}tlv.AddUInt16({tag}, {val});",
            "short" => $"{prefix}tlv.AddInt16({tag}, {val});",
            "uint" => $"{prefix}tlv.AddUInt32({tag}, {val});",
            "int" => $"{prefix}tlv.AddInt32({tag}, {val});",
            "ulong" => $"{prefix}tlv.AddUInt64({tag}, {val});",
            "long" => $"{prefix}tlv.AddInt64({tag}, {val});",
            "string" => $"{prefix}tlv.AddUTF8String({tag}, {val});",
            "byte[]" => $"{prefix}tlv.AddOctetString({tag}, {val});",
            "float" => $"{prefix}tlv.AddFloat({tag}, {val});",
            "double" => $"{prefix}tlv.AddDouble({tag}, {val});",
            _ when enumNames.Contains(baseType) => EmitEnumOrBitmapWrite(baseType, tag, prefix, val, enumUnderlyingTypes),
            _ when structNames.Contains(baseType) => $"{prefix}Write{baseType}(tlv, {tag}, {val});",
            _ => $"throw new NotSupportedException(\"Field {field.Name} ({csType}) is not supported by the generated TLV writer yet.\");",
        };
    }

    static string EmitArrayWrite(
        FieldModel field,
        string paramName,
        string elementCsType,
        uint tag,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes)
    {
        // Determine the per-element TLV add call
        string? elemWrite = elementCsType switch
        {
            "bool" => "tlv.AddBool(item);",
            "byte" => "tlv.AddUInt8(item);",
            "sbyte" => "tlv.AddInt8(item);",
            "ushort" => "tlv.AddUInt16(item);",
            "short" => "tlv.AddInt16(item);",
            "uint" => "tlv.AddUInt32(item);",
            "int" => "tlv.AddInt32(item);",
            "ulong" => "tlv.AddUInt64(item);",
            "long" => "tlv.AddInt64(item);",
            "string" => "tlv.AddUTF8String(item);",
            "byte[]" => "tlv.AddOctetString(item);",
            "float" => "tlv.AddFloat(item);",
            "double" => "tlv.AddDouble(item);",
            _ when enumNames.Contains(elementCsType) => EmitAnonymousEnumOrBitmapWrite(elementCsType, "item", enumUnderlyingTypes),
            _ when structNames.Contains(elementCsType) => $"Write{elementCsType}(tlv, item);",
            _ => null,
        };

        if (elemWrite == null)
        {
            return $"throw new NotSupportedException(\"Array field {field.Name} ({elementCsType}[]) is not supported by the generated TLV writer yet.\");";
        }

        return $"if ({paramName} != null) {{ tlv.AddArray({tag}); foreach (var item in {paramName}) {{ {elemWrite} }} tlv.EndContainer(); }}";
    }

    static string EmitEnumOrBitmapWrite(
        string baseType,
        uint tag,
        string prefix,
        string val,
        Dictionary<string, string> enumUnderlyingTypes)
    {
        string underlyingType = enumUnderlyingTypes.GetValueOrDefault(baseType, "byte");

        if (underlyingType == "ushort")
        {
            return $"{prefix}tlv.AddUInt16({tag}, (ushort){val});";
        }

        if (underlyingType == "uint")
        {
            return $"{prefix}tlv.AddUInt32({tag}, (uint){val});";
        }

        if (underlyingType == "ulong")
        {
            return $"{prefix}tlv.AddUInt64({tag}, (ulong){val});";
        }

        return $"{prefix}tlv.AddUInt8({tag}, (byte){val});";
    }

    static string EmitAnonymousEnumOrBitmapWrite(
        string baseType,
        string valueExpression,
        Dictionary<string, string> enumUnderlyingTypes)
    {
        string underlyingType = enumUnderlyingTypes.GetValueOrDefault(baseType, "byte");

        return underlyingType switch
        {
            "ushort" => $"tlv.AddUInt16((ushort){valueExpression});",
            "uint" => $"tlv.AddUInt32((uint){valueExpression});",
            "ulong" => $"tlv.AddUInt64((ulong){valueExpression});",
            _ => $"tlv.AddUInt8((byte){valueExpression});",
        };
    }

    // ── Typed Attribute Readers ──────────────────────────────────

    static void EmitAttributeReaders(StringBuilder sb, ClusterModel cluster, HashSet<string> localTypes, HashSet<string> enumNames)
    {
        if (cluster.Attributes.Count == 0)
        {
            return;
        }

        sb.AppendLine();
        sb.AppendLine("    // Attribute readers");

        foreach (var attr in cluster.Attributes)
        {
            string csType = Naming.MapCSharpType(attr.Type, attr.Nullable, false, attr.IsArray, attr.EntryType, localTypes);
            string methodName = $"Read{Naming.ToPascalCase(attr.Name)}Async";

            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Read {Naming.EscapeXml(attr.Name)} attribute (0x{attr.Id:X4}).</summary>");

            string baseCsType = csType.TrimEnd('?');
            if (Naming.IsValueType(baseCsType) || enumNames.Contains(baseCsType))
            {
                // Value types and generated enums/bitmaps use the typed reader.
                sb.AppendLine($"    public Task<{csType}> {methodName}(CancellationToken ct = default)");
                if (csType.EndsWith('?'))
                {
                    sb.AppendLine($"        => ReadNullableAttributeAsync<{baseCsType}>(0x{attr.Id:X4}, ct);");
                }
                else
                {
                    sb.AppendLine($"        => ReadAttributeAsync<{csType}>(0x{attr.Id:X4}, ct);");
                }
            }
            else if (csType.TrimEnd('?') is "string" or "byte[]" || csType.TrimEnd('?').EndsWith("[]", StringComparison.Ordinal))
            {
                // Reference types: ReadRefAttributeAsync<T> returns Task<T?>
                string readType = csType.TrimEnd('?');
                string returnType = csType.EndsWith('?') ? csType : $"{csType}?";
                sb.AppendLine($"    public Task<{returnType}> {methodName}(CancellationToken ct = default)");
                sb.AppendLine($"        => ReadRefAttributeAsync<{readType}>(0x{attr.Id:X4}, ct);");
            }
            else
            {
                // Preserve raw reads for complex/unknown attributes until generated parsers land.
                sb.AppendLine($"    public Task<object?> {methodName}(CancellationToken ct = default)");
                sb.AppendLine($"        => ReadAttributeAsync(0x{attr.Id:X4}, ct);");
            }
        }
    }

    static List<string> GetUnsupportedCommandFields(
        CommandModel cmd,
        HashSet<string> localTypes,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes,
        Dictionary<string, StructModel> structMap)
    {
        var unsupported = new List<string>();

        foreach (var field in cmd.Fields)
        {
            string csType = Naming.MapCSharpType(field.Type, field.Nullable, field.Optional, field.IsArray, field.EntryType, localTypes);
            if (!SupportsSerialization(field, csType, localTypes, enumNames, structNames, enumUnderlyingTypes, structMap, []))
            {
                unsupported.Add(field.IsArray
                    ? $"{field.Name} ({GetElementTypeForUnsupportedMessage(csType)}[])"
                    : $"{field.Name} ({csType})");
            }
        }

        return unsupported;
    }

    static string BuildUnsupportedCommandDetail(string commandName, List<string> unsupportedFields)
        => $"{commandName} requires serializer support for {string.Join(", ", unsupportedFields)}.";

    static string GetElementTypeForUnsupportedMessage(string csType)
        => csType.EndsWith("[]", StringComparison.Ordinal) ? csType[..^2] : csType;

    static bool SupportsSerialization(
        FieldModel field,
        string csType,
        HashSet<string> localTypes,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes,
        Dictionary<string, StructModel> structMap,
        HashSet<string> visitedStructs)
    {
        string baseType = csType.TrimEnd('?');
        if (field.IsArray && baseType.EndsWith("[]", StringComparison.Ordinal))
        {
            return SupportsTypeSerialization(baseType[..^2], localTypes, enumNames, structNames, enumUnderlyingTypes, structMap, visitedStructs);
        }

        return SupportsTypeSerialization(baseType, localTypes, enumNames, structNames, enumUnderlyingTypes, structMap, visitedStructs);
    }

    static bool SupportsTypeSerialization(
        string csType,
        HashSet<string> localTypes,
        HashSet<string> enumNames,
        HashSet<string> structNames,
        Dictionary<string, string> enumUnderlyingTypes,
        Dictionary<string, StructModel> structMap,
        HashSet<string> visitedStructs)
    {
        if (IsDirectlySerializableType(csType) || enumUnderlyingTypes.ContainsKey(csType))
        {
            return true;
        }

        if (!structNames.Contains(csType) || !structMap.TryGetValue(csType, out var structModel))
        {
            return false;
        }

        if (!visitedStructs.Add(csType))
        {
            return true;
        }

        foreach (var field in structModel.Fields)
        {
            string nestedType = Naming.MapCSharpType(field.Type, field.Nullable, field.Optional, field.IsArray, field.EntryType, localTypes);
            if (!SupportsSerialization(field, nestedType, localTypes, enumNames, structNames, enumUnderlyingTypes, structMap, visitedStructs))
            {
                visitedStructs.Remove(csType);
                return false;
            }
        }

        visitedStructs.Remove(csType);
        return true;
    }

    static bool IsDirectlySerializableType(string csType)
        => csType is "bool" or "byte" or "sbyte" or "short" or "ushort"
            or "int" or "uint" or "long" or "ulong" or "string"
            or "byte[]" or "float" or "double";

    // ── Helpers ──────────────────────────────────────────────────

    static string ResolveEnumBase(EnumModel e)
    {
        string declared = (e.BaseType?.ToLowerInvariant()) switch
        {
            "enum16" or "uint16" or "bitmap16" or "int16u" => "ushort",
            "enum32" or "uint32" or "bitmap32" or "int32u" => "uint",
            _ => "byte",
        };
        uint maxVal = e.Values.Count > 0 ? e.Values.Max(v => v.Value) : 0;
        if (maxVal > 65535)
        {
            return "uint";
        }

        if (maxVal > 255 && declared == "byte")
        {
            return "ushort";
        }

        return declared;
    }

    static string ResolveBitmapBase(BitmapModel bitmap) =>
        (bitmap.BaseType?.ToLowerInvariant()) switch
        {
            "bitmap8" or "enum8" or "uint8" or "int8u" => "byte",
            "bitmap16" or "enum16" or "uint16" or "int16u" => "ushort",
            "bitmap32" or "enum32" or "uint32" or "int32u" => "uint",
            "bitmap64" or "enum64" or "uint64" or "int64u" => "ulong",
            _ => "uint",
        };

    static string FormatEnumValueLiteral(uint value, string baseType) =>
        baseType switch
        {
            "byte" => $"0x{value:X2}",
            "ushort" => $"0x{value:X4}",
            "ulong" => $"0x{value:X}UL",
            _ => $"0x{value:X}",
        };
}
