using System.Text;
using System.Text.Json;

namespace DotMatter.CodeGen;

/// <summary>
/// Generates protocol message record classes from JSON structure definitions.
/// Each generated class has Serialize (TLV writer) and Deserialize (TLV reader) methods.
/// </summary>
public static class MessageCodeEmitter
{
    public record FieldDef(int Tag, string Name, string Type, bool Optional);
    public record MessageDef(string Name, string Doc, string Container, List<FieldDef> Fields);

    public static List<MessageDef> LoadDefinitions(string jsonPath)
    {
        var json = File.ReadAllText(jsonPath);
        var items = JsonSerializer.Deserialize<List<JsonElement>>(json)!;
        var result = new List<MessageDef>();

        foreach (var item in items)
        {
            var fields = new List<FieldDef>();
            foreach (var f in item.GetProperty("fields").EnumerateArray())
            {
                fields.Add(new FieldDef(
                    f.GetProperty("tag").GetInt32(),
                    f.GetProperty("name").GetString()!,
                    f.GetProperty("type").GetString()!,
                    f.TryGetProperty("optional", out var opt) && opt.GetBoolean()
                ));
            }

            result.Add(new MessageDef(
                item.GetProperty("name").GetString()!,
                item.TryGetProperty("doc", out var doc) ? doc.GetString()! : "",
                item.TryGetProperty("container", out var c) ? c.GetString()! : "structure",
                fields
            ));
        }

        return result;
    }

    public static string EmitFile(List<MessageDef> messages, string jsonFileName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by DotMatter.CodeGen from Matter Specification v1.5.");
        sb.AppendLine($"// Schema: {jsonFileName}");
        sb.AppendLine($"// Count: {messages.Count} message types");
        sb.AppendLine("// To regenerate: dotnet run --project DotMatter.CodeGen");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using DotMatter.Core.TLV;");
        sb.AppendLine();
        sb.AppendLine("namespace DotMatter.Core.Protocol;");

        foreach (var msg in messages)
        {
            sb.AppendLine();
            EmitMessage(sb, msg);
        }

        return sb.ToString();
    }

    private static void EmitMessage(StringBuilder sb, MessageDef msg)
    {
        sb.AppendLine($"/// <summary>{msg.Doc}</summary>");
        sb.AppendLine($"public sealed class {msg.Name}");
        sb.AppendLine("{");

        foreach (var f in msg.Fields)
        {
            string csType = ToCSharpType(f.Type, f.Optional);
            string init = f.Optional ? " = null;" : GetDefaultInit(f.Type);
            sb.AppendLine($"    /// <summary>Tag {f.Tag}: {f.Name}</summary>");
            sb.AppendLine($"    public {csType} {f.Name} {{ get; set; }}{init}");
        }

        sb.AppendLine();

        EmitSerialize(sb, msg);
        sb.AppendLine();

        EmitDeserialize(sb, msg);

        sb.AppendLine("}");
    }

    private static void EmitSerialize(StringBuilder sb, MessageDef msg)
    {
        sb.AppendLine("    /// <summary>Serialize this message into TLV.</summary>");
        sb.AppendLine("    public void Serialize(MatterTLV writer, int? tag = null)");
        sb.AppendLine("    {");

        string openMethod = msg.Container == "list" ? "AddList" : "AddStructure";
        sb.AppendLine("        if (tag.HasValue)");
        sb.AppendLine("        {");
        sb.AppendLine($"            writer.{openMethod}((byte)tag.Value);");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine($"            writer.{openMethod}();");
        sb.AppendLine("        }");

        foreach (var f in msg.Fields)
        {
            bool isMultiLine = f.Type.StartsWith("array:") || f.Type.StartsWith("struct:");
            if (f.Optional)
            {
                sb.AppendLine($"        if ({f.Name} != null)");
                if (isMultiLine)
                {
                    sb.AppendLine("        {");
                }
                else
                {
                    sb.AppendLine("        {");
                }
            }
            EmitFieldWrite(sb, f, f.Optional ? "    " : "");
            if (f.Optional)
            {
                sb.AppendLine("        }");
            }
        }

        sb.AppendLine("        writer.EndContainer();");
        sb.AppendLine("    }");
    }

    private static void EmitFieldWrite(StringBuilder sb, FieldDef f, string extraIndent = "")
    {
        string tagExpr = f.Tag.ToString();
        string indent = "        " + extraIndent;

        if (f.Type.StartsWith("array:struct:"))
        {
            sb.AppendLine($"{indent}writer.AddArray((byte){tagExpr});");
            sb.AppendLine($"{indent}foreach (var item in {f.Name}!)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    item.Serialize(writer);");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine($"{indent}writer.EndContainer();");
        }
        else if (f.Type.StartsWith("struct:"))
        {
            sb.AppendLine($"{indent}{f.Name}!.Serialize(writer, {tagExpr});");
        }
        else if (f.Type == "any")
        {
            sb.AppendLine($"{indent}// Tag {tagExpr}: {f.Name} is an 'any' value; caller writes raw TLV.");
        }
        else
        {
            string writeCall = f.Type switch
            {
                "bool" => $"writer.AddBool({tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "uint8" => $"writer.AddUInt8({tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "uint16" => $"writer.AddUInt16({tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "uint32" => $"writer.AddUInt32({tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "uint64" => $"writer.AddUInt64({tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "octstr" => $"writer.AddOctetString((byte){tagExpr}, {f.Name}{(f.Optional ? "!" : "")})",
                "string" => $"writer.AddUTF8String((byte){tagExpr}, {f.Name}{(f.Optional ? "!" : "")})",
                "float" => $"writer.AddFloat((byte){tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                "double" => $"writer.AddDouble((byte){tagExpr}, {f.Name}{(f.Optional ? ".Value" : "")})",
                _ => $"throw new NotSupportedException(\"Field {f.Name} ({f.Type}) is not supported by the generated TLV writer yet.\")"
            };
            sb.AppendLine($"{indent}{writeCall};");
        }
    }

    private static void EmitDeserialize(StringBuilder sb, MessageDef msg)
    {
        sb.AppendLine("    /// <summary>Deserialize from a TLV reader.</summary>");
        sb.AppendLine($"    public static {msg.Name} Deserialize(MatterTLV reader, int? tag = null)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var result = new {msg.Name}();");

        string openMethod = msg.Container == "list" ? "OpenList" : "OpenStructure";
        sb.AppendLine($"        reader.{openMethod}(tag);");
        sb.AppendLine();
        sb.AppendLine("        while (!reader.IsEndContainerNext())");
        sb.AppendLine("        {");

        foreach (var f in msg.Fields)
        {
            sb.AppendLine($"            if (reader.IsNextTag({f.Tag}))");
            sb.AppendLine("            {");
            EmitFieldRead(sb, f);
            sb.AppendLine("                continue;");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            reader.SkipElement();");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        reader.CloseContainer();");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
    }

    private static void EmitFieldRead(StringBuilder sb, FieldDef f)
    {
        if (f.Type.StartsWith("array:struct:"))
        {
            string itemType = f.Type["array:struct:".Length..];
            sb.AppendLine($"                result.{f.Name} = new List<{itemType}>();");
            sb.AppendLine($"                reader.OpenArray({f.Tag});");
            sb.AppendLine("                while (!reader.IsEndContainerNext())");
            sb.AppendLine("                {");
            sb.AppendLine($"                    result.{f.Name}.Add({itemType}.Deserialize(reader));");
            sb.AppendLine("                }");
            sb.AppendLine("                reader.CloseContainer();");
        }
        else if (f.Type.StartsWith("struct:"))
        {
            string structType = f.Type["struct:".Length..];
            sb.AppendLine($"                result.{f.Name} = {structType}.Deserialize(reader, {f.Tag});");
        }
        else if (f.Type == "any")
        {
            sb.AppendLine($"                result.{f.Name} = reader.GetData({f.Tag})!;");
        }
        else
        {
            string readCall = f.Type switch
            {
                "bool" => $"reader.GetBoolean({f.Tag})",
                "uint8" => $"reader.GetUnsignedInt8({f.Tag})",
                "uint16" => $"reader.GetUnsignedInt16({f.Tag})",
                "uint32" => $"reader.GetUnsignedInt32({f.Tag})",
                "uint64" => $"reader.GetUnsignedInt64({f.Tag})",
                "octstr" => $"reader.GetOctetString({f.Tag})",
                "string" => $"reader.GetUTF8String({f.Tag})",
                "float" => $"reader.GetFloat({f.Tag})",
                "double" => $"reader.GetDouble({f.Tag})",
                _ => $"throw new NotSupportedException(\"Field {f.Name} ({f.Type}) is not supported by the generated TLV reader yet.\")"
            };
            sb.AppendLine($"                result.{f.Name} = {readCall};");
        }
    }

    private static string ToCSharpType(string type, bool optional)
    {
        if (type.StartsWith("array:struct:"))
        {
            string itemType = type["array:struct:".Length..];
            return optional ? $"List<{itemType}>?" : $"List<{itemType}>";
        }
        if (type.StartsWith("struct:"))
        {
            string structType = type["struct:".Length..];
            return optional ? $"{structType}?" : structType;
        }
        string baseType = type switch
        {
            "bool" => "bool",
            "uint8" => "byte",
            "uint16" => "ushort",
            "uint32" => "uint",
            "uint64" => "ulong",
            "octstr" => "byte[]",
            "string" => "string",
            "float" => "float",
            "double" => "double",
            "any" => "object",
            _ => "object"
        };

        if (optional)
        {
            // Value types need ? for Nullable<T>, reference types need ? for nullable annotation
            return baseType switch
            {
                "bool" or "byte" or "ushort" or "uint" or "ulong" => $"{baseType}?",
                _ => $"{baseType}?"
            };
        }
        return baseType;
    }

    private static string GetDefaultInit(string type)
    {
        return type switch
        {
            "octstr" => " = Array.Empty<byte>();",
            "string" => " = string.Empty;",
            "any" => " = null!;",
            _ when type.StartsWith("struct:") => " = null!;",
            _ when type.StartsWith("array:") => " = new();",
            _ => ""
        };
    }
}
