// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: account-login-cluster.xml
// Cluster: Account Login (0x050E)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Account Login (0x050E, rev 2)</summary>
public class AccountLoginCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x050E;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="AccountLoginCluster"/> bound to the given session and endpoint.</summary>
    public AccountLoginCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>GetSetupPIN (0x0000).</summary>
        public const uint GetSetupPIN = 0x0000;
        /// <summary>Login (0x0002).</summary>
        public const uint Login = 0x0002;
        /// <summary>Logout (0x0003).</summary>
        public const uint Logout = 0x0003;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>LoggedOut (0x0000).</summary>
        public const uint LoggedOut = 0x0000;
    }

    // Async command methods

    /// <summary>Send GetSetupPIN command (0x0000).</summary>
    public Task<InvokeResponse> GetSetupPINAsync(
        string tempAccountIdentifier,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { tlv.AddUTF8String(0, tempAccountIdentifier); }, ct);

    /// <summary>Send Login command (0x0002).</summary>
    public Task<InvokeResponse> LoginAsync(
        string tempAccountIdentifier,
        string setupPIN,
        ulong? node = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv =>
        {
            tlv.AddUTF8String(0, tempAccountIdentifier);
            tlv.AddUTF8String(1, setupPIN);
            if (node != null) tlv.AddUInt64(2, node.Value);
        }, ct);

    /// <summary>Send Logout command (0x0003).</summary>
    public Task<InvokeResponse> LogoutAsync(
        ulong? node = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv => { if (node != null) tlv.AddUInt64(0, node.Value); }, ct);
}
