// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: actions-cluster.xml
// Cluster: Actions (0x0025)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Actions (0x0025, rev 1)</summary>
public class ActionsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0025;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ActionsCluster"/> bound to the given session and endpoint.</summary>
    public ActionsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>ActionErrorEnum enum values.</summary>
    public enum ActionErrorEnum : byte
    {
        /// <summary>Unknown value.</summary>
        Unknown = 0x00,
        /// <summary>Interrupted value.</summary>
        Interrupted = 0x01,
    }

    /// <summary>ActionStateEnum enum values.</summary>
    public enum ActionStateEnum : byte
    {
        /// <summary>Inactive value.</summary>
        Inactive = 0x00,
        /// <summary>Active value.</summary>
        Active = 0x01,
        /// <summary>Paused value.</summary>
        Paused = 0x02,
        /// <summary>Disabled value.</summary>
        Disabled = 0x03,
    }

    /// <summary>ActionTypeEnum enum values.</summary>
    public enum ActionTypeEnum : byte
    {
        /// <summary>Other value.</summary>
        Other = 0x00,
        /// <summary>Scene value.</summary>
        Scene = 0x01,
        /// <summary>Sequence value.</summary>
        Sequence = 0x02,
        /// <summary>Automation value.</summary>
        Automation = 0x03,
        /// <summary>Exception value.</summary>
        Exception = 0x04,
        /// <summary>Notification value.</summary>
        Notification = 0x05,
        /// <summary>Alarm value.</summary>
        Alarm = 0x06,
    }

    /// <summary>EndpointListTypeEnum enum values.</summary>
    public enum EndpointListTypeEnum : byte
    {
        /// <summary>Other value.</summary>
        Other = 0x00,
        /// <summary>Room value.</summary>
        Room = 0x01,
        /// <summary>Zone value.</summary>
        Zone = 0x02,
    }

    /// <summary>CommandBits bitmap flags.</summary>
    [System.Flags]
    public enum CommandBits : uint
    {
        /// <summary>InstantAction flag.</summary>
        InstantAction = 1u << 0,
        /// <summary>InstantActionWithTransition flag.</summary>
        InstantActionWithTransition = 1u << 1,
        /// <summary>StartAction flag.</summary>
        StartAction = 1u << 2,
        /// <summary>StartActionWithDuration flag.</summary>
        StartActionWithDuration = 1u << 3,
        /// <summary>StopAction flag.</summary>
        StopAction = 1u << 4,
        /// <summary>PauseAction flag.</summary>
        PauseAction = 1u << 5,
        /// <summary>PauseActionWithDuration flag.</summary>
        PauseActionWithDuration = 1u << 6,
        /// <summary>ResumeAction flag.</summary>
        ResumeAction = 1u << 7,
        /// <summary>EnableAction flag.</summary>
        EnableAction = 1u << 8,
        /// <summary>EnableActionWithDuration flag.</summary>
        EnableActionWithDuration = 1u << 9,
        /// <summary>DisableAction flag.</summary>
        DisableAction = 1u << 10,
        /// <summary>DisableActionWithDuration flag.</summary>
        DisableActionWithDuration = 1u << 11,
    }

    /// <summary>ActionStruct struct.</summary>
    public sealed class ActionStruct
    {
        /// <summary>Gets or sets ActionID.</summary>
        public ushort ActionID { get; set; }
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
        /// <summary>Gets or sets Type.</summary>
        public ActionTypeEnum Type { get; set; } = default!;
        /// <summary>Gets or sets EndpointListID.</summary>
        public ushort EndpointListID { get; set; }
        /// <summary>Gets or sets SupportedCommands.</summary>
        public CommandBits SupportedCommands { get; set; } = default!;
        /// <summary>Gets or sets State.</summary>
        public ActionStateEnum State { get; set; } = default!;
    }

    /// <summary>EndpointListStruct struct.</summary>
    public sealed class EndpointListStruct
    {
        /// <summary>Gets or sets EndpointListID.</summary>
        public ushort EndpointListID { get; set; }
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
        /// <summary>Gets or sets Type.</summary>
        public EndpointListTypeEnum Type { get; set; } = default!;
        /// <summary>Gets or sets Endpoints.</summary>
        public ushort[] Endpoints { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteActionStruct(MatterTLV tlv, byte tag, ActionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteActionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteActionStruct(MatterTLV tlv, ActionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteActionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteActionStructFields(MatterTLV tlv, ActionStruct value)
    {
        tlv.AddUInt16(0, value.ActionID);
        tlv.AddUTF8String(1, value.Name);
        tlv.AddUInt8(2, (byte)value.Type);
        tlv.AddUInt16(3, value.EndpointListID);
        tlv.AddUInt16(4, (ushort)value.SupportedCommands);
        tlv.AddUInt8(5, (byte)value.State);
    }

    private static void WriteEndpointListStruct(MatterTLV tlv, byte tag, EndpointListStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteEndpointListStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteEndpointListStruct(MatterTLV tlv, EndpointListStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteEndpointListStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteEndpointListStructFields(MatterTLV tlv, EndpointListStruct value)
    {
        tlv.AddUInt16(0, value.EndpointListID);
        tlv.AddUTF8String(1, value.Name);
        tlv.AddUInt8(2, (byte)value.Type);
        if (value.Endpoints != null) { tlv.AddArray(3); foreach (var item in value.Endpoints) { tlv.AddUInt16(item); } tlv.EndContainer(); }
    }

    // TLV struct deserializers

    private static ActionStruct ReadActionStruct(MatterTLV tlv)
        => ReadActionStruct(tlv, null);

    private static ActionStruct ReadActionStruct(MatterTLV tlv, int? tag)
    {
        var value = new ActionStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ActionID = (ushort)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.Name = tlv.GetUTF8String(1);
                    break;
                case 2:
                    value.Type = (ActionTypeEnum)tlv.GetUnsignedIntAny(2);
                    break;
                case 3:
                    value.EndpointListID = (ushort)tlv.GetUnsignedIntAny(3);
                    break;
                case 4:
                    value.SupportedCommands = (CommandBits)tlv.GetUnsignedIntAny(4);
                    break;
                case 5:
                    value.State = (ActionStateEnum)tlv.GetUnsignedIntAny(5);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static EndpointListStruct ReadEndpointListStruct(MatterTLV tlv)
        => ReadEndpointListStruct(tlv, null);

    private static EndpointListStruct ReadEndpointListStruct(MatterTLV tlv, int? tag)
    {
        var value = new EndpointListStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.EndpointListID = (ushort)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.Name = tlv.GetUTF8String(1);
                    break;
                case 2:
                    value.Type = (EndpointListTypeEnum)tlv.GetUnsignedIntAny(2);
                    break;
                case 3:
                    var items3 = new List<ushort>();
                    tlv.OpenArray(3);
                    while (!tlv.IsEndContainerNext())
                    {
                        items3.Add((ushort)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Endpoints = [.. items3];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>ActionList (0x0000).</summary>
        public const uint ActionList = 0x0000;
        /// <summary>EndpointLists (0x0001).</summary>
        public const uint EndpointLists = 0x0001;
        /// <summary>SetupURL (0x0002).</summary>
        public const uint SetupURL = 0x0002;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>InstantAction (0x0000).</summary>
        public const uint InstantAction = 0x0000;
        /// <summary>InstantActionWithTransition (0x0001).</summary>
        public const uint InstantActionWithTransition = 0x0001;
        /// <summary>StartAction (0x0002).</summary>
        public const uint StartAction = 0x0002;
        /// <summary>StartActionWithDuration (0x0003).</summary>
        public const uint StartActionWithDuration = 0x0003;
        /// <summary>StopAction (0x0004).</summary>
        public const uint StopAction = 0x0004;
        /// <summary>PauseAction (0x0005).</summary>
        public const uint PauseAction = 0x0005;
        /// <summary>PauseActionWithDuration (0x0006).</summary>
        public const uint PauseActionWithDuration = 0x0006;
        /// <summary>ResumeAction (0x0007).</summary>
        public const uint ResumeAction = 0x0007;
        /// <summary>EnableAction (0x0008).</summary>
        public const uint EnableAction = 0x0008;
        /// <summary>EnableActionWithDuration (0x0009).</summary>
        public const uint EnableActionWithDuration = 0x0009;
        /// <summary>DisableAction (0x000A).</summary>
        public const uint DisableAction = 0x000A;
        /// <summary>DisableActionWithDuration (0x000B).</summary>
        public const uint DisableActionWithDuration = 0x000B;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>StateChanged (0x0000).</summary>
        public const uint StateChanged = 0x0000;
        /// <summary>ActionFailed (0x0001).</summary>
        public const uint ActionFailed = 0x0001;
    }

    /// <summary>Base type for this cluster's event reports.</summary>
    public abstract class ClusterEvent
        : MatterClusterEvent
    {
        /// <summary>Initializes a new cluster event wrapper.</summary>
        protected ClusterEvent(MatterEventReport report, string eventName)
            : base(report, "Actions", eventName) { }
    }

    /// <summary>Fallback event wrapper when DotMatter cannot parse a typed payload.</summary>
    public sealed class UnknownClusterEvent(MatterEventReport report, string? reason = null)
        : ClusterEvent(report, "Unknown")
    {
        /// <summary>Gets the reason the typed payload parser could not materialize this event.</summary>
        public override string? Reason { get; } = reason;
    }

    /// <summary>StateChanged event payload.</summary>
    public sealed class StateChangedEventData
    {
        /// <summary>Gets or sets ActionID.</summary>
        public ushort ActionID { get; set; }
        /// <summary>Gets or sets InvokeID.</summary>
        public uint InvokeID { get; set; }
        /// <summary>Gets or sets NewState.</summary>
        public ActionStateEnum NewState { get; set; } = default!;
    }

    /// <summary>StateChanged event report.</summary>
    public sealed class StateChangedEvent(MatterEventReport report, StateChangedEventData payload)
        : ClusterEvent(report, "StateChanged")
    {
        /// <summary>Gets the typed StateChanged payload.</summary>
        public StateChangedEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>ActionFailed event payload.</summary>
    public sealed class ActionFailedEventData
    {
        /// <summary>Gets or sets ActionID.</summary>
        public ushort ActionID { get; set; }
        /// <summary>Gets or sets InvokeID.</summary>
        public uint InvokeID { get; set; }
        /// <summary>Gets or sets NewState.</summary>
        public ActionStateEnum NewState { get; set; } = default!;
        /// <summary>Gets or sets Error.</summary>
        public ActionErrorEnum Error { get; set; } = default!;
    }

    /// <summary>ActionFailed event report.</summary>
    public sealed class ActionFailedEvent(MatterEventReport report, ActionFailedEventData payload)
        : ClusterEvent(report, "ActionFailed")
    {
        /// <summary>Gets the typed ActionFailed payload.</summary>
        public ActionFailedEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    // Async command methods

    /// <summary>Send InstantAction command (0x0000).</summary>
    public Task<InvokeResponse> InstantActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send InstantActionWithTransition command (0x0001).</summary>
    public Task<InvokeResponse> InstantActionWithTransitionAsync(
        ushort actionID,
        ushort transitionTime,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
            tlv.AddUInt16(2, transitionTime);
        }, ct);

    /// <summary>Send StartAction command (0x0002).</summary>
    public Task<InvokeResponse> StartActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send StartActionWithDuration command (0x0003).</summary>
    public Task<InvokeResponse> StartActionWithDurationAsync(
        ushort actionID,
        uint duration,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
            tlv.AddUInt32(2, duration);
        }, ct);

    /// <summary>Send StopAction command (0x0004).</summary>
    public Task<InvokeResponse> StopActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send PauseAction command (0x0005).</summary>
    public Task<InvokeResponse> PauseActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send PauseActionWithDuration command (0x0006).</summary>
    public Task<InvokeResponse> PauseActionWithDurationAsync(
        ushort actionID,
        uint duration,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
            tlv.AddUInt32(2, duration);
        }, ct);

    /// <summary>Send ResumeAction command (0x0007).</summary>
    public Task<InvokeResponse> ResumeActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0007, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send EnableAction command (0x0008).</summary>
    public Task<InvokeResponse> EnableActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0008, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send EnableActionWithDuration command (0x0009).</summary>
    public Task<InvokeResponse> EnableActionWithDurationAsync(
        ushort actionID,
        uint duration,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0009, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
            tlv.AddUInt32(2, duration);
        }, ct);

    /// <summary>Send DisableAction command (0x000A).</summary>
    public Task<InvokeResponse> DisableActionAsync(
        ushort actionID,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000A, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
        }, ct);

    /// <summary>Send DisableActionWithDuration command (0x000B).</summary>
    public Task<InvokeResponse> DisableActionWithDurationAsync(
        ushort actionID,
        uint duration,
        uint? invokeID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000B, tlv =>
        {
            tlv.AddUInt16(0, actionID);
            if (invokeID != null) tlv.AddUInt32(1, invokeID.Value);
            tlv.AddUInt32(2, duration);
        }, ct);

    // Attribute readers

    /// <summary>Read ActionList attribute (0x0000).</summary>
    public Task<ActionStruct[]?> ReadActionListAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0000, ReadActionStruct, ct);

    /// <summary>Read EndpointLists attribute (0x0001).</summary>
    public Task<EndpointListStruct[]?> ReadEndpointListsAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0001, ReadEndpointListStruct, ct);

    /// <summary>Read SetupURL attribute (0x0002).</summary>
    public Task<string?> ReadSetupURLAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0002, ct);

    // Event payload parsers

    private static StateChangedEventData ReadStateChangedEventData(MatterTLV tlv)
    {
        var value = new StateChangedEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ActionID = (ushort)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.InvokeID = tlv.GetUnsignedIntAny(1);
                    break;
                case 2:
                    value.NewState = (ActionStateEnum)tlv.GetUnsignedIntAny(2);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadStateChangedEventData(MatterEventReport report, out StateChangedEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadStateChangedEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "StateChanged payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static ActionFailedEventData ReadActionFailedEventData(MatterTLV tlv)
    {
        var value = new ActionFailedEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ActionID = (ushort)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.InvokeID = tlv.GetUnsignedIntAny(1);
                    break;
                case 2:
                    value.NewState = (ActionStateEnum)tlv.GetUnsignedIntAny(2);
                    break;
                case 3:
                    value.Error = (ActionErrorEnum)tlv.GetUnsignedIntAny(3);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadActionFailedEventData(MatterEventReport report, out ActionFailedEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadActionFailedEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "ActionFailed payload parse failed: " + ex.Message;
            return false;
        }
    }

    // Event payload JSON projectors

    private static JsonObject CreateActionStructJson(ActionStruct value)
    {
        var json = new JsonObject();
        json["actionID"] = CreateJsonValue(value.ActionID);
        if (value.Name is { } name)
        {
            json["name"] = CreateJsonValue(name);
        }
        if (value.Type is { } type)
        {
            json["type"] = CreateJsonValue(type.ToString());
        }
        json["endpointListID"] = CreateJsonValue(value.EndpointListID);
        if (value.SupportedCommands is { } supportedCommands)
        {
            json["supportedCommands"] = CreateJsonValue(supportedCommands.ToString());
        }
        if (value.State is { } state)
        {
            json["state"] = CreateJsonValue(state.ToString());
        }
        return json;
    }

    private static JsonObject CreateEndpointListStructJson(EndpointListStruct value)
    {
        var json = new JsonObject();
        json["endpointListID"] = CreateJsonValue(value.EndpointListID);
        if (value.Name is { } name)
        {
            json["name"] = CreateJsonValue(name);
        }
        if (value.Type is { } type)
        {
            json["type"] = CreateJsonValue(type.ToString());
        }
        if (value.Endpoints is { } endpointsValues)
        {
            var endpointsItems = new JsonArray();
            foreach (var item in endpointsValues)
            {
                endpointsItems.Add((JsonNode?)CreateJsonValue(item));
            }
            json["endpoints"] = endpointsItems;
        }
        return json;
    }

    private static JsonObject CreateStateChangedEventDataJson(StateChangedEventData value)
    {
        var json = new JsonObject();
        json["actionID"] = CreateJsonValue(value.ActionID);
        json["invokeID"] = CreateJsonValue(value.InvokeID);
        if (value.NewState is { } newState)
        {
            json["newState"] = CreateJsonValue(newState.ToString());
        }
        return json;
    }

    private static JsonObject CreateActionFailedEventDataJson(ActionFailedEventData value)
    {
        var json = new JsonObject();
        json["actionID"] = CreateJsonValue(value.ActionID);
        json["invokeID"] = CreateJsonValue(value.InvokeID);
        if (value.NewState is { } newState)
        {
            json["newState"] = CreateJsonValue(newState.ToString());
        }
        if (value.Error is { } error)
        {
            json["error"] = CreateJsonValue(error.ToString());
        }
        return json;
    }

    internal static JsonObject? MapEventPayloadJson(ClusterEvent evt)
    {
        return evt switch
        {
            StateChangedEvent typed => CreateStateChangedEventDataJson(typed.Payload),
            ActionFailedEvent typed => CreateActionFailedEventDataJson(typed.Payload),
            _ => null,
        };
    }

    // Event readers and subscriptions

    /// <summary>Read event reports from this cluster.</summary>
    public async Task<ClusterEvent[]> ReadEventsAsync(
        uint[]? eventIds = null,
        bool fabricFiltered = false,
        CancellationToken ct = default)
    {
        var events = await ReadEventsAsync(MapEventReports, eventIds, fabricFiltered, ct);
        return [.. events];
    }

    /// <summary>Subscribe to event reports from this cluster.</summary>
    public Task<MatterEventSubscription<ClusterEvent>> SubscribeEventsAsync(
        uint[]? eventIds = null,
        ushort minInterval = 1,
        ushort maxInterval = 60,
        bool fabricFiltered = false,
        CancellationToken ct = default)
        => SubscribeEventsAsync(MapEventReports, eventIds, minInterval, maxInterval, fabricFiltered, ct);

    internal static ClusterEvent[] MapEventReports(IReadOnlyList<MatterEventReport> reports)
    {
        if (reports.Count == 0)
        {
            return [];
        }

        var events = new List<ClusterEvent>(reports.Count);
        foreach (var report in reports)
        {
            events.Add(MapEventReport(report));
        }

        return [.. events];
    }

    internal static ClusterEvent MapEventReport(MatterEventReport report)
    {
        return report.EventId switch
        {
            Events.StateChanged when TryReadStateChangedEventData(report, out var stateChangedEventData, out _) => new StateChangedEvent(report, stateChangedEventData!),
            Events.StateChanged when TryReadStateChangedEventData(report, out _, out var stateChangedReason) => new UnknownClusterEvent(report, stateChangedReason),
            Events.ActionFailed when TryReadActionFailedEventData(report, out var actionFailedEventData, out _) => new ActionFailedEvent(report, actionFailedEventData!),
            Events.ActionFailed when TryReadActionFailedEventData(report, out _, out var actionFailedReason) => new UnknownClusterEvent(report, actionFailedReason),
            _ => new UnknownClusterEvent(report, "Event ID is not recognized by this cluster."),
        };
    }
}
