// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: application-launcher-cluster.xml
// Cluster: Application Launcher (0x050C)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Application Launcher (0x050C, rev 2)</summary>
public class ApplicationLauncherCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x050C;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ApplicationLauncherCluster"/> bound to the given session and endpoint.</summary>
    public ApplicationLauncherCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Support for attributes and commands required for endpoint to support launching any application within the supported application catalogs</summary>
        ApplicationPlatform = 1u << 0,
    }

    /// <summary>StatusEnum enum values.</summary>
    public enum StatusEnum : byte
    {
        /// <summary>Success value.</summary>
        Success = 0x00,
        /// <summary>AppNotAvailable value.</summary>
        AppNotAvailable = 0x01,
        /// <summary>SystemBusy value.</summary>
        SystemBusy = 0x02,
        /// <summary>PendingUserApproval value.</summary>
        PendingUserApproval = 0x03,
        /// <summary>Downloading value.</summary>
        Downloading = 0x04,
        /// <summary>Installing value.</summary>
        Installing = 0x05,
    }

    /// <summary>ApplicationEPStruct struct.</summary>
    public sealed class ApplicationEPStruct
    {
        /// <summary>Gets or sets Application.</summary>
        public ApplicationStruct Application { get; set; } = default!;
        /// <summary>Gets or sets Endpoint.</summary>
        public ushort? Endpoint { get; set; }
    }

    /// <summary>ApplicationStruct struct.</summary>
    public sealed class ApplicationStruct
    {
        /// <summary>Gets or sets CatalogVendorID.</summary>
        public ushort CatalogVendorID { get; set; }
        /// <summary>Gets or sets ApplicationID.</summary>
        public string ApplicationID { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteApplicationEPStruct(MatterTLV tlv, byte tag, ApplicationEPStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteApplicationEPStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteApplicationEPStruct(MatterTLV tlv, ApplicationEPStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteApplicationEPStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteApplicationEPStructFields(MatterTLV tlv, ApplicationEPStruct value)
    {
        WriteApplicationStruct(tlv, 0, value.Application);
        if (value.Endpoint != null) tlv.AddUInt16(1, value.Endpoint.Value);
    }

    private static void WriteApplicationStruct(MatterTLV tlv, byte tag, ApplicationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteApplicationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteApplicationStruct(MatterTLV tlv, ApplicationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteApplicationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteApplicationStructFields(MatterTLV tlv, ApplicationStruct value)
    {
        tlv.AddUInt16(0, value.CatalogVendorID);
        tlv.AddUTF8String(1, value.ApplicationID);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>CatalogList (0x0000).</summary>
        public const uint CatalogList = 0x0000;
        /// <summary>CurrentApp (0x0001).</summary>
        public const uint CurrentApp = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>LaunchApp (0x0000).</summary>
        public const uint LaunchApp = 0x0000;
        /// <summary>StopApp (0x0001).</summary>
        public const uint StopApp = 0x0001;
        /// <summary>HideApp (0x0002).</summary>
        public const uint HideApp = 0x0002;
    }

    // Async command methods

    /// <summary>Send LaunchApp command (0x0000).</summary>
    public Task<InvokeResponse> LaunchAppAsync(
        ApplicationStruct? application = default,
        byte[]? data = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            if (application != null) WriteApplicationStruct(tlv, 0, application);
            if (data != null) tlv.AddOctetString(1, data);
        }, ct);

    /// <summary>Send StopApp command (0x0001).</summary>
    public Task<InvokeResponse> StopAppAsync(
        ApplicationStruct? application = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv => { if (application != null) WriteApplicationStruct(tlv, 0, application); }, ct);

    /// <summary>Send HideApp command (0x0002).</summary>
    public Task<InvokeResponse> HideAppAsync(
        ApplicationStruct? application = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv => { if (application != null) WriteApplicationStruct(tlv, 0, application); }, ct);

    // Attribute readers

    /// <summary>Read CatalogList attribute (0x0000).</summary>
    public Task<ushort[]?> ReadCatalogListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ushort[]>(0x0000, ct);

    /// <summary>Read CurrentApp attribute (0x0001).</summary>
    public Task<object?> ReadCurrentAppAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0001, ct);
}
