// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: audio-output-cluster.xml
// Cluster: Audio Output (0x050B)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Audio Output (0x050B, rev 1)</summary>
public class AudioOutputCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x050B;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="AudioOutputCluster"/> bound to the given session and endpoint.</summary>
    public AudioOutputCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Supports updates to output names</summary>
        NameUpdates = 1u << 0,
    }

    /// <summary>OutputTypeEnum enum values.</summary>
    public enum OutputTypeEnum : byte
    {
        /// <summary>HDMI value.</summary>
        HDMI = 0x00,
        /// <summary>BT value.</summary>
        BT = 0x01,
        /// <summary>Optical value.</summary>
        Optical = 0x02,
        /// <summary>Headphone value.</summary>
        Headphone = 0x03,
        /// <summary>Internal value.</summary>
        Internal = 0x04,
        /// <summary>Other value.</summary>
        Other = 0x05,
    }

    /// <summary>OutputInfoStruct struct.</summary>
    public sealed class OutputInfoStruct
    {
        /// <summary>Gets or sets Index.</summary>
        public byte Index { get; set; }
        /// <summary>Gets or sets OutputType.</summary>
        public OutputTypeEnum OutputType { get; set; } = default!;
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteOutputInfoStruct(MatterTLV tlv, byte tag, OutputInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteOutputInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOutputInfoStruct(MatterTLV tlv, OutputInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteOutputInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOutputInfoStructFields(MatterTLV tlv, OutputInfoStruct value)
    {
        tlv.AddUInt8(0, value.Index);
        tlv.AddUInt8(1, (byte)value.OutputType);
        tlv.AddUTF8String(2, value.Name);
    }

    // TLV struct deserializers

    private static OutputInfoStruct ReadOutputInfoStruct(MatterTLV tlv)
        => ReadOutputInfoStruct(tlv, null);

    private static OutputInfoStruct ReadOutputInfoStruct(MatterTLV tlv, int? tag)
    {
        var value = new OutputInfoStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.Index = (byte)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.OutputType = (OutputTypeEnum)tlv.GetUnsignedIntAny(1);
                    break;
                case 2:
                    value.Name = tlv.GetUTF8String(2);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>OutputList (0x0000).</summary>
        public const uint OutputList = 0x0000;
        /// <summary>CurrentOutput (0x0001).</summary>
        public const uint CurrentOutput = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>SelectOutput (0x0000).</summary>
        public const uint SelectOutput = 0x0000;
        /// <summary>RenameOutput (0x0001).</summary>
        public const uint RenameOutput = 0x0001;
    }

    // Async command methods

    /// <summary>Send SelectOutput command (0x0000).</summary>
    public Task<InvokeResponse> SelectOutputAsync(
        byte index,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { tlv.AddUInt8(0, index); }, ct);

    /// <summary>Send RenameOutput command (0x0001).</summary>
    public Task<InvokeResponse> RenameOutputAsync(
        byte index,
        string name,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            tlv.AddUInt8(0, index);
            tlv.AddUTF8String(1, name);
        }, ct);

    // Attribute readers

    /// <summary>Read OutputList attribute (0x0000).</summary>
    public Task<OutputInfoStruct[]?> ReadOutputListAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0000, ReadOutputInfoStruct, ct);

    /// <summary>Read CurrentOutput attribute (0x0001).</summary>
    public Task<byte> ReadCurrentOutputAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);
}
