// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: basic-information-cluster.xml (+1 merged XML file(s))
// Cluster: Basic Information (0x0028)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Basic Information (0x0028, rev 5)</summary>
public class BasicInformationCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0028;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="BasicInformationCluster"/> bound to the given session and endpoint.</summary>
    public BasicInformationCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>ProductFinishEnum enum values.</summary>
    public enum ProductFinishEnum : byte
    {
        /// <summary>Other value.</summary>
        Other = 0x00,
        /// <summary>Matte value.</summary>
        Matte = 0x01,
        /// <summary>Satin value.</summary>
        Satin = 0x02,
        /// <summary>Polished value.</summary>
        Polished = 0x03,
        /// <summary>Rugged value.</summary>
        Rugged = 0x04,
        /// <summary>Fabric value.</summary>
        Fabric = 0x05,
    }

    /// <summary>ColorEnum enum values.</summary>
    public enum ColorEnum : byte
    {
        /// <summary>Black value.</summary>
        Black = 0x00,
        /// <summary>Navy value.</summary>
        Navy = 0x01,
        /// <summary>Green value.</summary>
        Green = 0x02,
        /// <summary>Teal value.</summary>
        Teal = 0x03,
        /// <summary>Maroon value.</summary>
        Maroon = 0x04,
        /// <summary>Purple value.</summary>
        Purple = 0x05,
        /// <summary>Olive value.</summary>
        Olive = 0x06,
        /// <summary>Gray value.</summary>
        Gray = 0x07,
        /// <summary>Blue value.</summary>
        Blue = 0x08,
        /// <summary>Lime value.</summary>
        Lime = 0x09,
        /// <summary>Aqua value.</summary>
        Aqua = 0x0A,
        /// <summary>Red value.</summary>
        Red = 0x0B,
        /// <summary>Fuchsia value.</summary>
        Fuchsia = 0x0C,
        /// <summary>Yellow value.</summary>
        Yellow = 0x0D,
        /// <summary>White value.</summary>
        White = 0x0E,
        /// <summary>Nickel value.</summary>
        Nickel = 0x0F,
        /// <summary>Chrome value.</summary>
        Chrome = 0x10,
        /// <summary>Brass value.</summary>
        Brass = 0x11,
        /// <summary>Copper value.</summary>
        Copper = 0x12,
        /// <summary>Silver value.</summary>
        Silver = 0x13,
        /// <summary>Gold value.</summary>
        Gold = 0x14,
    }

    /// <summary>CapabilityMinimaStruct struct.</summary>
    public sealed class CapabilityMinimaStruct
    {
        /// <summary>Gets or sets CaseSessionsPerFabric.</summary>
        public ushort CaseSessionsPerFabric { get; set; }
        /// <summary>Gets or sets SubscriptionsPerFabric.</summary>
        public ushort SubscriptionsPerFabric { get; set; }
    }

    /// <summary>ProductAppearanceStruct struct.</summary>
    public sealed class ProductAppearanceStruct
    {
        /// <summary>Gets or sets Finish.</summary>
        public ProductFinishEnum Finish { get; set; } = default!;
        /// <summary>Gets or sets PrimaryColor.</summary>
        public ColorEnum PrimaryColor { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteCapabilityMinimaStruct(MatterTLV tlv, byte tag, CapabilityMinimaStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteCapabilityMinimaStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCapabilityMinimaStruct(MatterTLV tlv, CapabilityMinimaStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteCapabilityMinimaStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCapabilityMinimaStructFields(MatterTLV tlv, CapabilityMinimaStruct value)
    {
        tlv.AddUInt16(0, value.CaseSessionsPerFabric);
        tlv.AddUInt16(1, value.SubscriptionsPerFabric);
    }

    private static void WriteProductAppearanceStruct(MatterTLV tlv, byte tag, ProductAppearanceStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteProductAppearanceStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteProductAppearanceStruct(MatterTLV tlv, ProductAppearanceStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteProductAppearanceStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteProductAppearanceStructFields(MatterTLV tlv, ProductAppearanceStruct value)
    {
        tlv.AddUInt8(0, (byte)value.Finish);
        tlv.AddUInt8(1, (byte)value.PrimaryColor);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>DataModelRevision (0x0000).</summary>
        public const uint DataModelRevision = 0x0000;
        /// <summary>VendorName (0x0001).</summary>
        public const uint VendorName = 0x0001;
        /// <summary>VendorID (0x0002).</summary>
        public const uint VendorID = 0x0002;
        /// <summary>ProductName (0x0003).</summary>
        public const uint ProductName = 0x0003;
        /// <summary>ProductID (0x0004).</summary>
        public const uint ProductID = 0x0004;
        /// <summary>NodeLabel (0x0005).</summary>
        public const uint NodeLabel = 0x0005;
        /// <summary>Location (0x0006).</summary>
        public const uint Location = 0x0006;
        /// <summary>HardwareVersion (0x0007).</summary>
        public const uint HardwareVersion = 0x0007;
        /// <summary>HardwareVersionString (0x0008).</summary>
        public const uint HardwareVersionString = 0x0008;
        /// <summary>SoftwareVersion (0x0009).</summary>
        public const uint SoftwareVersion = 0x0009;
        /// <summary>SoftwareVersionString (0x000A).</summary>
        public const uint SoftwareVersionString = 0x000A;
        /// <summary>ManufacturingDate (0x000B).</summary>
        public const uint ManufacturingDate = 0x000B;
        /// <summary>PartNumber (0x000C).</summary>
        public const uint PartNumber = 0x000C;
        /// <summary>ProductURL (0x000D).</summary>
        public const uint ProductURL = 0x000D;
        /// <summary>ProductLabel (0x000E).</summary>
        public const uint ProductLabel = 0x000E;
        /// <summary>SerialNumber (0x000F).</summary>
        public const uint SerialNumber = 0x000F;
        /// <summary>LocalConfigDisabled (0x0010).</summary>
        public const uint LocalConfigDisabled = 0x0010;
        /// <summary>Reachable (0x0011).</summary>
        public const uint Reachable = 0x0011;
        /// <summary>UniqueID (0x0012).</summary>
        public const uint UniqueID = 0x0012;
        /// <summary>CapabilityMinima (0x0013).</summary>
        public const uint CapabilityMinima = 0x0013;
        /// <summary>ProductAppearance (0x0014).</summary>
        public const uint ProductAppearance = 0x0014;
        /// <summary>SpecificationVersion (0x0015).</summary>
        public const uint SpecificationVersion = 0x0015;
        /// <summary>MaxPathsPerInvoke (0x0016).</summary>
        public const uint MaxPathsPerInvoke = 0x0016;
        /// <summary>ConfigurationVersion (0x0018).</summary>
        public const uint ConfigurationVersion = 0x0018;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>MfgSpecificPing (0x0000).</summary>
        public const uint MfgSpecificPing = 0x0000;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>StartUp (0x0000).</summary>
        public const uint StartUp = 0x0000;
        /// <summary>ShutDown (0x0001).</summary>
        public const uint ShutDown = 0x0001;
        /// <summary>Leave (0x0002).</summary>
        public const uint Leave = 0x0002;
        /// <summary>ReachableChanged (0x0003).</summary>
        public const uint ReachableChanged = 0x0003;
    }

    // Async command methods

    /// <summary>Send MfgSpecificPing command (0x0000).</summary>
    public Task<InvokeResponse> MfgSpecificPingAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    // Attribute readers

    /// <summary>Read DataModelRevision attribute (0x0000).</summary>
    public Task<ushort> ReadDataModelRevisionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0000, ct);

    /// <summary>Read VendorName attribute (0x0001).</summary>
    public Task<string?> ReadVendorNameAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0001, ct);

    /// <summary>Read VendorID attribute (0x0002).</summary>
    public Task<ushort> ReadVendorIDAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0002, ct);

    /// <summary>Read ProductName attribute (0x0003).</summary>
    public Task<string?> ReadProductNameAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0003, ct);

    /// <summary>Read ProductID attribute (0x0004).</summary>
    public Task<ushort> ReadProductIDAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0004, ct);

    /// <summary>Read NodeLabel attribute (0x0005).</summary>
    public Task<string?> ReadNodeLabelAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0005, ct);

    /// <summary>Read Location attribute (0x0006).</summary>
    public Task<string?> ReadLocationAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0006, ct);

    /// <summary>Read HardwareVersion attribute (0x0007).</summary>
    public Task<ushort> ReadHardwareVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0007, ct);

    /// <summary>Read HardwareVersionString attribute (0x0008).</summary>
    public Task<string?> ReadHardwareVersionStringAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0008, ct);

    /// <summary>Read SoftwareVersion attribute (0x0009).</summary>
    public Task<uint> ReadSoftwareVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0009, ct);

    /// <summary>Read SoftwareVersionString attribute (0x000A).</summary>
    public Task<string?> ReadSoftwareVersionStringAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000A, ct);

    /// <summary>Read ManufacturingDate attribute (0x000B).</summary>
    public Task<string?> ReadManufacturingDateAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000B, ct);

    /// <summary>Read PartNumber attribute (0x000C).</summary>
    public Task<string?> ReadPartNumberAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000C, ct);

    /// <summary>Read ProductURL attribute (0x000D).</summary>
    public Task<string?> ReadProductURLAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000D, ct);

    /// <summary>Read ProductLabel attribute (0x000E).</summary>
    public Task<string?> ReadProductLabelAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000E, ct);

    /// <summary>Read SerialNumber attribute (0x000F).</summary>
    public Task<string?> ReadSerialNumberAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x000F, ct);

    /// <summary>Read LocalConfigDisabled attribute (0x0010).</summary>
    public Task<bool> ReadLocalConfigDisabledAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0010, ct);

    /// <summary>Read Reachable attribute (0x0011).</summary>
    public Task<bool> ReadReachableAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0011, ct);

    /// <summary>Read UniqueID attribute (0x0012).</summary>
    public Task<string?> ReadUniqueIDAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0012, ct);

    /// <summary>Read CapabilityMinima attribute (0x0013).</summary>
    public Task<object?> ReadCapabilityMinimaAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0013, ct);

    /// <summary>Read ProductAppearance attribute (0x0014).</summary>
    public Task<object?> ReadProductAppearanceAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0014, ct);

    /// <summary>Read SpecificationVersion attribute (0x0015).</summary>
    public Task<uint> ReadSpecificationVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0015, ct);

    /// <summary>Read MaxPathsPerInvoke attribute (0x0016).</summary>
    public Task<ushort> ReadMaxPathsPerInvokeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0016, ct);

    /// <summary>Read ConfigurationVersion attribute (0x0018).</summary>
    public Task<uint> ReadConfigurationVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0018, ct);

    // Attribute writers

    /// <summary>Write NodeLabel attribute (0x0005).</summary>
    public Task<WriteResponse> WriteNodeLabelAsync(
        string nodeLabel,
        bool timedRequest = true,
        ushort timedTimeoutMs = 5000,
        CancellationToken ct = default)
        => WriteAttributeAsync(0x0005, tlv =>
        {
            ArgumentNullException.ThrowIfNull(nodeLabel);
            tlv.AddUTF8String(2, nodeLabel);
        }, timedRequest, timedTimeoutMs, ct);

    /// <summary>Write Location attribute (0x0006).</summary>
    public Task<WriteResponse> WriteLocationAsync(
        string location,
        bool timedRequest = true,
        ushort timedTimeoutMs = 5000,
        CancellationToken ct = default)
        => WriteAttributeAsync(0x0006, tlv =>
        {
            ArgumentNullException.ThrowIfNull(location);
            tlv.AddUTF8String(2, location);
        }, timedRequest, timedTimeoutMs, ct);

    /// <summary>Write LocalConfigDisabled attribute (0x0010).</summary>
    public Task<WriteResponse> WriteLocalConfigDisabledAsync(
        bool localConfigDisabled,
        bool timedRequest = true,
        ushort timedTimeoutMs = 5000,
        CancellationToken ct = default)
        => WriteAttributeAsync(0x0010, tlv =>
        {
            tlv.AddBool(2, localConfigDisabled);
        }, timedRequest, timedTimeoutMs, ct);
}
