// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: boolean-state-configuration-cluster.xml
// Cluster: Boolean State Configuration (0x0080)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Boolean State Configuration (0x0080, rev 1)</summary>
public class BooleanStateConfigurationCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0080;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="BooleanStateConfigurationCluster"/> bound to the given session and endpoint.</summary>
    public BooleanStateConfigurationCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Supports visual alarms</summary>
        Visual = 1u << 0,
        /// <summary>Supports audible alarms</summary>
        Audible = 1u << 1,
        /// <summary>Supports ability to suppress or acknowledge alarms</summary>
        AlarmSuppress = 1u << 2,
        /// <summary>Supports ability to set sensor sensitivity</summary>
        SensitivityLevel = 1u << 3,
    }

    /// <summary>AlarmModeBitmap bitmap flags.</summary>
    [System.Flags]
    public enum AlarmModeBitmap : uint
    {
        /// <summary>Visual flag.</summary>
        Visual = 1u << 0,
        /// <summary>Audible flag.</summary>
        Audible = 1u << 1,
    }

    /// <summary>SensorFaultBitmap bitmap flags.</summary>
    [System.Flags]
    public enum SensorFaultBitmap : uint
    {
        /// <summary>GeneralFault flag.</summary>
        GeneralFault = 1u << 0,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>CurrentSensitivityLevel (0x0000).</summary>
        public const uint CurrentSensitivityLevel = 0x0000;
        /// <summary>SupportedSensitivityLevels (0x0001).</summary>
        public const uint SupportedSensitivityLevels = 0x0001;
        /// <summary>DefaultSensitivityLevel (0x0002).</summary>
        public const uint DefaultSensitivityLevel = 0x0002;
        /// <summary>AlarmsActive (0x0003).</summary>
        public const uint AlarmsActive = 0x0003;
        /// <summary>AlarmsSuppressed (0x0004).</summary>
        public const uint AlarmsSuppressed = 0x0004;
        /// <summary>AlarmsEnabled (0x0005).</summary>
        public const uint AlarmsEnabled = 0x0005;
        /// <summary>AlarmsSupported (0x0006).</summary>
        public const uint AlarmsSupported = 0x0006;
        /// <summary>SensorFault (0x0007).</summary>
        public const uint SensorFault = 0x0007;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>SuppressAlarm (0x0000).</summary>
        public const uint SuppressAlarm = 0x0000;
        /// <summary>EnableDisableAlarm (0x0001).</summary>
        public const uint EnableDisableAlarm = 0x0001;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>AlarmsStateChanged (0x0000).</summary>
        public const uint AlarmsStateChanged = 0x0000;
        /// <summary>SensorFault (0x0001).</summary>
        public const uint SensorFault = 0x0001;
    }

    // Async command methods

    /// <summary>Send SuppressAlarm command (0x0000).</summary>
    public Task<InvokeResponse> SuppressAlarmAsync(
        AlarmModeBitmap alarmsToSuppress,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { tlv.AddUInt8(0, (byte)alarmsToSuppress); }, ct);

    /// <summary>Send EnableDisableAlarm command (0x0001).</summary>
    public Task<InvokeResponse> EnableDisableAlarmAsync(
        AlarmModeBitmap alarmsToEnableDisable,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv => { tlv.AddUInt8(0, (byte)alarmsToEnableDisable); }, ct);

    // Attribute readers

    /// <summary>Read CurrentSensitivityLevel attribute (0x0000).</summary>
    public Task<byte> ReadCurrentSensitivityLevelAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0000, ct);

    /// <summary>Read SupportedSensitivityLevels attribute (0x0001).</summary>
    public Task<byte> ReadSupportedSensitivityLevelsAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read DefaultSensitivityLevel attribute (0x0002).</summary>
    public Task<byte> ReadDefaultSensitivityLevelAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0002, ct);

    /// <summary>Read AlarmsActive attribute (0x0003).</summary>
    public Task<AlarmModeBitmap> ReadAlarmsActiveAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmModeBitmap>(0x0003, ct);

    /// <summary>Read AlarmsSuppressed attribute (0x0004).</summary>
    public Task<AlarmModeBitmap> ReadAlarmsSuppressedAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmModeBitmap>(0x0004, ct);

    /// <summary>Read AlarmsEnabled attribute (0x0005).</summary>
    public Task<AlarmModeBitmap> ReadAlarmsEnabledAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmModeBitmap>(0x0005, ct);

    /// <summary>Read AlarmsSupported attribute (0x0006).</summary>
    public Task<AlarmModeBitmap> ReadAlarmsSupportedAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmModeBitmap>(0x0006, ct);

    /// <summary>Read SensorFault attribute (0x0007).</summary>
    public Task<SensorFaultBitmap> ReadSensorFaultAsync(CancellationToken ct = default)
        => ReadAttributeAsync<SensorFaultBitmap>(0x0007, ct);
}
