// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: camera-av-settings-user-level-management-cluster.xml
// Cluster: Camera AV Settings User Level Management (0x0552)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Camera AV Settings User Level Management (0x0552, rev 1)</summary>
public class CameraAVSettingsUserLevelManagementCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0552;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="CameraAVSettingsUserLevelManagementCluster"/> bound to the given session and endpoint.</summary>
    public CameraAVSettingsUserLevelManagementCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Digital PTZ support</summary>
        DigitalPTZ = 1u << 0,
        /// <summary>Mechanical Pan support</summary>
        MechanicalPan = 1u << 1,
        /// <summary>Mechanical Tilt support</summary>
        MechanicalTilt = 1u << 2,
        /// <summary>Mechanical Zoom support</summary>
        MechanicalZoom = 1u << 3,
        /// <summary>Mechanical saved presets support</summary>
        MechanicalPresets = 1u << 4,
    }

    /// <summary>PhysicalMovementEnum enum values.</summary>
    public enum PhysicalMovementEnum : byte
    {
        /// <summary>Idle value.</summary>
        Idle = 0x00,
        /// <summary>Moving value.</summary>
        Moving = 0x01,
    }

    /// <summary>DPTZStruct struct.</summary>
    public sealed class DPTZStruct
    {
        /// <summary>Gets or sets VideoStreamID.</summary>
        public ushort VideoStreamID { get; set; }
        /// <summary>Gets or sets Viewport.</summary>
        public ViewportStruct Viewport { get; set; } = default!;
    }

    /// <summary>MPTZPresetStruct struct.</summary>
    public sealed class MPTZPresetStruct
    {
        /// <summary>Gets or sets PresetID.</summary>
        public byte PresetID { get; set; }
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
        /// <summary>Gets or sets Settings.</summary>
        public MPTZStruct Settings { get; set; } = default!;
    }

    /// <summary>MPTZStruct struct.</summary>
    public sealed class MPTZStruct
    {
        /// <summary>Gets or sets Pan.</summary>
        public short? Pan { get; set; }
        /// <summary>Gets or sets Tilt.</summary>
        public short? Tilt { get; set; }
        /// <summary>Gets or sets Zoom.</summary>
        public byte? Zoom { get; set; }
    }

    /// <summary>ViewportStruct struct.</summary>
    public sealed class ViewportStruct
    {
        /// <summary>Gets or sets X1.</summary>
        public ushort X1 { get; set; }
        /// <summary>Gets or sets Y1.</summary>
        public ushort Y1 { get; set; }
        /// <summary>Gets or sets X2.</summary>
        public ushort X2 { get; set; }
        /// <summary>Gets or sets Y2.</summary>
        public ushort Y2 { get; set; }
    }

    // TLV struct serializers

    private static void WriteDPTZStruct(MatterTLV tlv, byte tag, DPTZStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDPTZStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDPTZStruct(MatterTLV tlv, DPTZStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDPTZStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDPTZStructFields(MatterTLV tlv, DPTZStruct value)
    {
        tlv.AddUInt16(0, value.VideoStreamID);
        WriteViewportStruct(tlv, 1, value.Viewport);
    }

    private static void WriteMPTZPresetStruct(MatterTLV tlv, byte tag, MPTZPresetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMPTZPresetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMPTZPresetStruct(MatterTLV tlv, MPTZPresetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMPTZPresetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMPTZPresetStructFields(MatterTLV tlv, MPTZPresetStruct value)
    {
        tlv.AddUInt8(0, value.PresetID);
        tlv.AddUTF8String(1, value.Name);
        WriteMPTZStruct(tlv, 2, value.Settings);
    }

    private static void WriteMPTZStruct(MatterTLV tlv, byte tag, MPTZStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMPTZStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMPTZStruct(MatterTLV tlv, MPTZStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMPTZStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMPTZStructFields(MatterTLV tlv, MPTZStruct value)
    {
        if (value.Pan != null) tlv.AddInt16(0, value.Pan.Value);
        if (value.Tilt != null) tlv.AddInt16(1, value.Tilt.Value);
        if (value.Zoom != null) tlv.AddUInt8(2, value.Zoom.Value);
    }

    private static void WriteViewportStruct(MatterTLV tlv, byte tag, ViewportStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteViewportStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteViewportStruct(MatterTLV tlv, ViewportStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteViewportStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteViewportStructFields(MatterTLV tlv, ViewportStruct value)
    {
        tlv.AddUInt16(0, value.X1);
        tlv.AddUInt16(1, value.Y1);
        tlv.AddUInt16(2, value.X2);
        tlv.AddUInt16(3, value.Y2);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>MPTZPosition (0x0000).</summary>
        public const uint MPTZPosition = 0x0000;
        /// <summary>MaxPresets (0x0001).</summary>
        public const uint MaxPresets = 0x0001;
        /// <summary>MPTZPresets (0x0002).</summary>
        public const uint MPTZPresets = 0x0002;
        /// <summary>DPTZStreams (0x0003).</summary>
        public const uint DPTZStreams = 0x0003;
        /// <summary>ZoomMax (0x0004).</summary>
        public const uint ZoomMax = 0x0004;
        /// <summary>TiltMin (0x0005).</summary>
        public const uint TiltMin = 0x0005;
        /// <summary>TiltMax (0x0006).</summary>
        public const uint TiltMax = 0x0006;
        /// <summary>PanMin (0x0007).</summary>
        public const uint PanMin = 0x0007;
        /// <summary>PanMax (0x0008).</summary>
        public const uint PanMax = 0x0008;
        /// <summary>MovementState (0x0009).</summary>
        public const uint MovementState = 0x0009;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>MPTZSetPosition (0x0000).</summary>
        public const uint MPTZSetPosition = 0x0000;
        /// <summary>MPTZRelativeMove (0x0001).</summary>
        public const uint MPTZRelativeMove = 0x0001;
        /// <summary>MPTZMoveToPreset (0x0002).</summary>
        public const uint MPTZMoveToPreset = 0x0002;
        /// <summary>MPTZSavePreset (0x0003).</summary>
        public const uint MPTZSavePreset = 0x0003;
        /// <summary>MPTZRemovePreset (0x0004).</summary>
        public const uint MPTZRemovePreset = 0x0004;
        /// <summary>DPTZSetViewport (0x0005).</summary>
        public const uint DPTZSetViewport = 0x0005;
        /// <summary>DPTZRelativeMove (0x0006).</summary>
        public const uint DPTZRelativeMove = 0x0006;
    }

    // Async command methods

    /// <summary>Send MPTZSetPosition command (0x0000).</summary>
    public Task<InvokeResponse> MPTZSetPositionAsync(
        short? pan = default,
        short? tilt = default,
        byte? zoom = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            if (pan != null) tlv.AddInt16(0, pan.Value);
            if (tilt != null) tlv.AddInt16(1, tilt.Value);
            if (zoom != null) tlv.AddUInt8(2, zoom.Value);
        }, ct);

    /// <summary>Send MPTZRelativeMove command (0x0001).</summary>
    public Task<InvokeResponse> MPTZRelativeMoveAsync(
        short? panDelta = default,
        short? tiltDelta = default,
        sbyte? zoomDelta = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            if (panDelta != null) tlv.AddInt16(0, panDelta.Value);
            if (tiltDelta != null) tlv.AddInt16(1, tiltDelta.Value);
            if (zoomDelta != null) tlv.AddInt8(2, zoomDelta.Value);
        }, ct);

    /// <summary>Send MPTZMoveToPreset command (0x0002).</summary>
    public Task<InvokeResponse> MPTZMoveToPresetAsync(
        byte presetID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv => { tlv.AddUInt8(0, presetID); }, ct);

    /// <summary>Send MPTZSavePreset command (0x0003).</summary>
    public Task<InvokeResponse> MPTZSavePresetAsync(
        string name,
        byte? presetID = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv =>
        {
            if (presetID != null) tlv.AddUInt8(0, presetID.Value);
            tlv.AddUTF8String(1, name);
        }, ct);

    /// <summary>Send MPTZRemovePreset command (0x0004).</summary>
    public Task<InvokeResponse> MPTZRemovePresetAsync(
        byte presetID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, tlv => { tlv.AddUInt8(0, presetID); }, ct);

    /// <summary>Send DPTZSetViewport command (0x0005).</summary>
    public Task<InvokeResponse> DPTZSetViewportAsync(
        ushort videoStreamID,
        ViewportStruct viewport,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv =>
        {
            tlv.AddUInt16(0, videoStreamID);
            WriteViewportStruct(tlv, 1, viewport);
        }, ct);

    /// <summary>Send DPTZRelativeMove command (0x0006).</summary>
    public Task<InvokeResponse> DPTZRelativeMoveAsync(
        ushort videoStreamID,
        short? deltaX = default,
        short? deltaY = default,
        sbyte? zoomDelta = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv =>
        {
            tlv.AddUInt16(0, videoStreamID);
            if (deltaX != null) tlv.AddInt16(1, deltaX.Value);
            if (deltaY != null) tlv.AddInt16(2, deltaY.Value);
            if (zoomDelta != null) tlv.AddInt8(3, zoomDelta.Value);
        }, ct);

    // Attribute readers

    /// <summary>Read MPTZPosition attribute (0x0000).</summary>
    public Task<object?> ReadMPTZPositionAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0000, ct);

    /// <summary>Read MaxPresets attribute (0x0001).</summary>
    public Task<byte> ReadMaxPresetsAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read MPTZPresets attribute (0x0002).</summary>
    public Task<MPTZPresetStruct[]?> ReadMPTZPresetsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<MPTZPresetStruct[]>(0x0002, ct);

    /// <summary>Read DPTZStreams attribute (0x0003).</summary>
    public Task<DPTZStruct[]?> ReadDPTZStreamsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DPTZStruct[]>(0x0003, ct);

    /// <summary>Read ZoomMax attribute (0x0004).</summary>
    public Task<byte> ReadZoomMaxAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0004, ct);

    /// <summary>Read TiltMin attribute (0x0005).</summary>
    public Task<short> ReadTiltMinAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0005, ct);

    /// <summary>Read TiltMax attribute (0x0006).</summary>
    public Task<short> ReadTiltMaxAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0006, ct);

    /// <summary>Read PanMin attribute (0x0007).</summary>
    public Task<short> ReadPanMinAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0007, ct);

    /// <summary>Read PanMax attribute (0x0008).</summary>
    public Task<short> ReadPanMaxAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0008, ct);

    /// <summary>Read MovementState attribute (0x0009).</summary>
    public Task<PhysicalMovementEnum> ReadMovementStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<PhysicalMovementEnum>(0x0009, ct);
}
