// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: closure-control-cluster.xml
// Cluster: Closure Control (0x0104)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Closure Control (0x0104, rev 1)</summary>
public class ClosureControlCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0104;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ClosureControlCluster"/> bound to the given session and endpoint.</summary>
    public ClosureControlCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Supports Positioning with at least Fully Opened (0%) and Fully Closed (100%) discrete positions</summary>
        Positioning = 1u << 0,
        /// <summary>Supports a latch (securing a position, or a state)</summary>
        MotionLatching = 1u << 1,
        /// <summary>Supports the Instantaneous feature</summary>
        Instantaneous = 1u << 2,
        /// <summary>Supports Speed motion throttling</summary>
        Speed = 1u << 3,
        /// <summary>Supports Ventilation discrete state</summary>
        Ventilation = 1u << 4,
        /// <summary>Supports Pedestrian discrete state</summary>
        Pedestrian = 1u << 5,
        /// <summary>Supports the Calibration feature</summary>
        Calibration = 1u << 6,
        /// <summary>Supports the Protection feature</summary>
        Protection = 1u << 7,
        /// <summary>Supports the manual operation feature</summary>
        ManuallyOperable = 1u << 8,
    }

    /// <summary>ClosureErrorEnum enum values.</summary>
    public enum ClosureErrorEnum : byte
    {
        /// <summary>PhysicallyBlocked value.</summary>
        PhysicallyBlocked = 0x00,
        /// <summary>BlockedBySensor value.</summary>
        BlockedBySensor = 0x01,
        /// <summary>TemperatureLimited value.</summary>
        TemperatureLimited = 0x02,
        /// <summary>MaintenanceRequired value.</summary>
        MaintenanceRequired = 0x03,
        /// <summary>InternalInterference value.</summary>
        InternalInterference = 0x04,
    }

    /// <summary>CurrentPositionEnum enum values.</summary>
    public enum CurrentPositionEnum : byte
    {
        /// <summary>FullyClosed value.</summary>
        FullyClosed = 0x00,
        /// <summary>FullyOpened value.</summary>
        FullyOpened = 0x01,
        /// <summary>PartiallyOpened value.</summary>
        PartiallyOpened = 0x02,
        /// <summary>OpenedForPedestrian value.</summary>
        OpenedForPedestrian = 0x03,
        /// <summary>OpenedForVentilation value.</summary>
        OpenedForVentilation = 0x04,
        /// <summary>OpenedAtSignature value.</summary>
        OpenedAtSignature = 0x05,
    }

    /// <summary>MainStateEnum enum values.</summary>
    public enum MainStateEnum : byte
    {
        /// <summary>Stopped value.</summary>
        Stopped = 0x00,
        /// <summary>Moving value.</summary>
        Moving = 0x01,
        /// <summary>WaitingForMotion value.</summary>
        WaitingForMotion = 0x02,
        /// <summary>Error value.</summary>
        Error = 0x03,
        /// <summary>Calibrating value.</summary>
        Calibrating = 0x04,
        /// <summary>Protected value.</summary>
        Protected = 0x05,
        /// <summary>Disengaged value.</summary>
        Disengaged = 0x06,
        /// <summary>SetupRequired value.</summary>
        SetupRequired = 0x07,
    }

    /// <summary>TargetPositionEnum enum values.</summary>
    public enum TargetPositionEnum : byte
    {
        /// <summary>MoveToFullyClosed value.</summary>
        MoveToFullyClosed = 0x00,
        /// <summary>MoveToFullyOpen value.</summary>
        MoveToFullyOpen = 0x01,
        /// <summary>MoveToPedestrianPosition value.</summary>
        MoveToPedestrianPosition = 0x02,
        /// <summary>MoveToVentilationPosition value.</summary>
        MoveToVentilationPosition = 0x03,
        /// <summary>MoveToSignaturePosition value.</summary>
        MoveToSignaturePosition = 0x04,
    }

    /// <summary>ThreeLevelAutoEnum enum values.</summary>
    public enum ThreeLevelAutoEnum : byte
    {
        /// <summary>Auto value.</summary>
        Auto = 0x00,
        /// <summary>Low value.</summary>
        Low = 0x01,
        /// <summary>Medium value.</summary>
        Medium = 0x02,
        /// <summary>High value.</summary>
        High = 0x03,
    }

    /// <summary>LatchControlModesBitmap bitmap flags.</summary>
    [System.Flags]
    public enum LatchControlModesBitmap : uint
    {
        /// <summary>RemoteLatching flag.</summary>
        RemoteLatching = 1u << 0,
        /// <summary>RemoteUnlatching flag.</summary>
        RemoteUnlatching = 1u << 1,
    }

    /// <summary>OverallCurrentStateStruct struct.</summary>
    public sealed class OverallCurrentStateStruct
    {
        /// <summary>Gets or sets Position.</summary>
        public CurrentPositionEnum? Position { get; set; }
        /// <summary>Gets or sets Latch.</summary>
        public bool? Latch { get; set; }
        /// <summary>Gets or sets Speed.</summary>
        public ThreeLevelAutoEnum? Speed { get; set; }
        /// <summary>Gets or sets SecureState.</summary>
        public bool? SecureState { get; set; }
    }

    /// <summary>OverallTargetStateStruct struct.</summary>
    public sealed class OverallTargetStateStruct
    {
        /// <summary>Gets or sets Position.</summary>
        public TargetPositionEnum? Position { get; set; }
        /// <summary>Gets or sets Latch.</summary>
        public bool? Latch { get; set; }
        /// <summary>Gets or sets Speed.</summary>
        public ThreeLevelAutoEnum? Speed { get; set; }
    }

    // TLV struct serializers

    private static void WriteOverallCurrentStateStruct(MatterTLV tlv, byte tag, OverallCurrentStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteOverallCurrentStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOverallCurrentStateStruct(MatterTLV tlv, OverallCurrentStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteOverallCurrentStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOverallCurrentStateStructFields(MatterTLV tlv, OverallCurrentStateStruct value)
    {
        if (value.Position != null) tlv.AddUInt8(0, (byte)value.Position);
        if (value.Latch != null) tlv.AddBool(1, value.Latch.Value);
        if (value.Speed != null) tlv.AddUInt8(2, (byte)value.Speed);
        if (value.SecureState != null) tlv.AddBool(3, value.SecureState.Value);
    }

    private static void WriteOverallTargetStateStruct(MatterTLV tlv, byte tag, OverallTargetStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteOverallTargetStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOverallTargetStateStruct(MatterTLV tlv, OverallTargetStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteOverallTargetStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOverallTargetStateStructFields(MatterTLV tlv, OverallTargetStateStruct value)
    {
        if (value.Position != null) tlv.AddUInt8(0, (byte)value.Position);
        if (value.Latch != null) tlv.AddBool(1, value.Latch.Value);
        if (value.Speed != null) tlv.AddUInt8(2, (byte)value.Speed);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>CountdownTime (0x0000).</summary>
        public const uint CountdownTime = 0x0000;
        /// <summary>MainState (0x0001).</summary>
        public const uint MainState = 0x0001;
        /// <summary>CurrentErrorList (0x0002).</summary>
        public const uint CurrentErrorList = 0x0002;
        /// <summary>OverallCurrentState (0x0003).</summary>
        public const uint OverallCurrentState = 0x0003;
        /// <summary>OverallTargetState (0x0004).</summary>
        public const uint OverallTargetState = 0x0004;
        /// <summary>LatchControlModes (0x0005).</summary>
        public const uint LatchControlModes = 0x0005;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>Stop (0x0000).</summary>
        public const uint Stop = 0x0000;
        /// <summary>MoveTo (0x0001).</summary>
        public const uint MoveTo = 0x0001;
        /// <summary>Calibrate (0x0002).</summary>
        public const uint Calibrate = 0x0002;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>OperationalError (0x0000).</summary>
        public const uint OperationalError = 0x0000;
        /// <summary>MovementCompleted (0x0001).</summary>
        public const uint MovementCompleted = 0x0001;
        /// <summary>EngageStateChanged (0x0002).</summary>
        public const uint EngageStateChanged = 0x0002;
        /// <summary>SecureStateChanged (0x0003).</summary>
        public const uint SecureStateChanged = 0x0003;
    }

    // Async command methods

    /// <summary>Send Stop command (0x0000).</summary>
    public Task<InvokeResponse> StopAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    /// <summary>Send MoveTo command (0x0001).</summary>
    public Task<InvokeResponse> MoveToAsync(
        TargetPositionEnum? position = default,
        bool? latch = default,
        ThreeLevelAutoEnum? speed = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            if (position != null) tlv.AddUInt8(0, (byte)position);
            if (latch != null) tlv.AddBool(1, latch.Value);
            if (speed != null) tlv.AddUInt8(2, (byte)speed);
        }, ct);

    /// <summary>Send Calibrate command (0x0002).</summary>
    public Task<InvokeResponse> CalibrateAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, ct: ct);

    // Attribute readers

    /// <summary>Read CountdownTime attribute (0x0000).</summary>
    public Task<uint?> ReadCountdownTimeAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0000, ct);

    /// <summary>Read MainState attribute (0x0001).</summary>
    public Task<MainStateEnum> ReadMainStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<MainStateEnum>(0x0001, ct);

    /// <summary>Read CurrentErrorList attribute (0x0002).</summary>
    public Task<ClosureErrorEnum[]?> ReadCurrentErrorListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ClosureErrorEnum[]>(0x0002, ct);

    /// <summary>Read OverallCurrentState attribute (0x0003).</summary>
    public Task<object?> ReadOverallCurrentStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0003, ct);

    /// <summary>Read OverallTargetState attribute (0x0004).</summary>
    public Task<object?> ReadOverallTargetStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0004, ct);

    /// <summary>Read LatchControlModes attribute (0x0005).</summary>
    public Task<LatchControlModesBitmap> ReadLatchControlModesAsync(CancellationToken ct = default)
        => ReadAttributeAsync<LatchControlModesBitmap>(0x0005, ct);
}
