// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: commodity-metering-cluster.xml
// Cluster: Commodity Metering (0x0B07)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Commodity Metering (0x0B07, rev 1)</summary>
public class CommodityMeteringCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0B07;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="CommodityMeteringCluster"/> bound to the given session and endpoint.</summary>
    public CommodityMeteringCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>TariffUnitEnum enum values.</summary>
    public enum TariffUnitEnum : byte
    {
        /// <summary>kWh value.</summary>
        KWh = 0x00,
        /// <summary>kVAh value.</summary>
        KVAh = 0x01,
    }

    /// <summary>MeteredQuantityStruct struct.</summary>
    public sealed class MeteredQuantityStruct
    {
        /// <summary>Gets or sets TariffComponentIDs.</summary>
        public uint[] TariffComponentIDs { get; set; } = default!;
        /// <summary>Gets or sets Quantity.</summary>
        public long Quantity { get; set; }
    }

    // TLV struct serializers

    private static void WriteMeteredQuantityStruct(MatterTLV tlv, byte tag, MeteredQuantityStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMeteredQuantityStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeteredQuantityStruct(MatterTLV tlv, MeteredQuantityStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMeteredQuantityStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeteredQuantityStructFields(MatterTLV tlv, MeteredQuantityStruct value)
    {
        if (value.TariffComponentIDs != null) { tlv.AddArray(0); foreach (var item in value.TariffComponentIDs) { tlv.AddUInt32(item); } tlv.EndContainer(); }
        tlv.AddInt64(1, value.Quantity);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>MeteredQuantity (0x0000).</summary>
        public const uint MeteredQuantity = 0x0000;
        /// <summary>MeteredQuantityTimestamp (0x0001).</summary>
        public const uint MeteredQuantityTimestamp = 0x0001;
        /// <summary>TariffUnit (0x0002).</summary>
        public const uint TariffUnit = 0x0002;
        /// <summary>MaximumMeteredQuantities (0x0003).</summary>
        public const uint MaximumMeteredQuantities = 0x0003;
    }

    // Attribute readers

    /// <summary>Read MeteredQuantity attribute (0x0000).</summary>
    public Task<MeteredQuantityStruct[]?> ReadMeteredQuantityAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<MeteredQuantityStruct[]>(0x0000, ct);

    /// <summary>Read MeteredQuantityTimestamp attribute (0x0001).</summary>
    public Task<uint?> ReadMeteredQuantityTimestampAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0001, ct);

    /// <summary>Read TariffUnit attribute (0x0002).</summary>
    public Task<TariffUnitEnum> ReadTariffUnitAsync(CancellationToken ct = default)
        => ReadAttributeAsync<TariffUnitEnum>(0x0002, ct);

    /// <summary>Read MaximumMeteredQuantities attribute (0x0003).</summary>
    public Task<ushort?> ReadMaximumMeteredQuantitiesAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0003, ct);
}
