// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: content-control-cluster.xml
// Cluster: Content Control (0x050F)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Content Control (0x050F, rev 1)</summary>
public class ContentControlCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x050F;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ContentControlCluster"/> bound to the given session and endpoint.</summary>
    public ContentControlCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Supports managing screen time limits.</summary>
        ScreenTime = 1u << 0,
        /// <summary>Supports managing a PIN code which is used for restricting access to configuration of this feature.</summary>
        PINManagement = 1u << 1,
        /// <summary>Supports managing content controls for unrated content.</summary>
        BlockUnrated = 1u << 2,
        /// <summary>Supports managing content controls based upon rating threshold for on demand content.</summary>
        OnDemandContentRating = 1u << 3,
        /// <summary>Supports managing content controls based upon rating threshold for scheduled content.</summary>
        ScheduledContentRating = 1u << 4,
        /// <summary>Supports managing a set of channels that are prohibited.</summary>
        BlockChannels = 1u << 5,
        /// <summary>Supports managing a set of applications that are prohibited.</summary>
        BlockApplications = 1u << 6,
        /// <summary>Supports managing content controls based upon setting time window in which all contents and applications SHALL be blocked.</summary>
        BlockContentTimeWindow = 1u << 7,
    }

    /// <summary>StatusCodeEnum enum values.</summary>
    public enum StatusCodeEnum : byte
    {
        /// <summary>InvalidPINCode value.</summary>
        InvalidPINCode = 0x02,
        /// <summary>InvalidRating value.</summary>
        InvalidRating = 0x03,
        /// <summary>InvalidChannel value.</summary>
        InvalidChannel = 0x04,
        /// <summary>ChannelAlreadyExist value.</summary>
        ChannelAlreadyExist = 0x05,
        /// <summary>ChannelNotExist value.</summary>
        ChannelNotExist = 0x06,
        /// <summary>UnidentifiableApplication value.</summary>
        UnidentifiableApplication = 0x07,
        /// <summary>ApplicationAlreadyExist value.</summary>
        ApplicationAlreadyExist = 0x08,
        /// <summary>ApplicationNotExist value.</summary>
        ApplicationNotExist = 0x09,
        /// <summary>TimeWindowAlreadyExist value.</summary>
        TimeWindowAlreadyExist = 0x0A,
        /// <summary>TimeWindowNotExist value.</summary>
        TimeWindowNotExist = 0x0B,
    }

    /// <summary>DayOfWeekBitmap bitmap flags.</summary>
    [System.Flags]
    public enum DayOfWeekBitmap : uint
    {
        /// <summary>Sunday flag.</summary>
        Sunday = 1u << 0,
        /// <summary>Monday flag.</summary>
        Monday = 1u << 1,
        /// <summary>Tuesday flag.</summary>
        Tuesday = 1u << 2,
        /// <summary>Wednesday flag.</summary>
        Wednesday = 1u << 3,
        /// <summary>Thursday flag.</summary>
        Thursday = 1u << 4,
        /// <summary>Friday flag.</summary>
        Friday = 1u << 5,
        /// <summary>Saturday flag.</summary>
        Saturday = 1u << 6,
    }

    /// <summary>AppInfoStruct struct.</summary>
    public sealed class AppInfoStruct
    {
        /// <summary>Gets or sets CatalogVendorID.</summary>
        public ushort CatalogVendorID { get; set; }
        /// <summary>Gets or sets ApplicationID.</summary>
        public string ApplicationID { get; set; } = default!;
    }

    /// <summary>BlockChannelStruct struct.</summary>
    public sealed class BlockChannelStruct
    {
        /// <summary>Gets or sets BlockChannelIndex.</summary>
        public ushort? BlockChannelIndex { get; set; }
        /// <summary>Gets or sets MajorNumber.</summary>
        public ushort MajorNumber { get; set; }
        /// <summary>Gets or sets MinorNumber.</summary>
        public ushort MinorNumber { get; set; }
        /// <summary>Gets or sets Identifier.</summary>
        public string? Identifier { get; set; }
    }

    /// <summary>RatingNameStruct struct.</summary>
    public sealed class RatingNameStruct
    {
        /// <summary>Gets or sets RatingName.</summary>
        public string RatingName { get; set; } = default!;
        /// <summary>Gets or sets RatingNameDesc.</summary>
        public string? RatingNameDesc { get; set; }
    }

    /// <summary>TimePeriodStruct struct.</summary>
    public sealed class TimePeriodStruct
    {
        /// <summary>Gets or sets StartHour.</summary>
        public byte StartHour { get; set; }
        /// <summary>Gets or sets StartMinute.</summary>
        public byte StartMinute { get; set; }
        /// <summary>Gets or sets EndHour.</summary>
        public byte EndHour { get; set; }
        /// <summary>Gets or sets EndMinute.</summary>
        public byte EndMinute { get; set; }
    }

    /// <summary>TimeWindowStruct struct.</summary>
    public sealed class TimeWindowStruct
    {
        /// <summary>Gets or sets TimeWindowIndex.</summary>
        public ushort? TimeWindowIndex { get; set; }
        /// <summary>Gets or sets DayOfWeek.</summary>
        public DayOfWeekBitmap DayOfWeek { get; set; } = default!;
        /// <summary>Gets or sets TimePeriod.</summary>
        public TimePeriodStruct[] TimePeriod { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteAppInfoStruct(MatterTLV tlv, byte tag, AppInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteAppInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAppInfoStruct(MatterTLV tlv, AppInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteAppInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAppInfoStructFields(MatterTLV tlv, AppInfoStruct value)
    {
        tlv.AddUInt16(0, value.CatalogVendorID);
        tlv.AddUTF8String(1, value.ApplicationID);
    }

    private static void WriteBlockChannelStruct(MatterTLV tlv, byte tag, BlockChannelStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteBlockChannelStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBlockChannelStruct(MatterTLV tlv, BlockChannelStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteBlockChannelStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBlockChannelStructFields(MatterTLV tlv, BlockChannelStruct value)
    {
        if (value.BlockChannelIndex != null) { tlv.AddUInt16(0, value.BlockChannelIndex.Value); } else { tlv.AddNull(0); }
        tlv.AddUInt16(1, value.MajorNumber);
        tlv.AddUInt16(2, value.MinorNumber);
        if (value.Identifier != null) tlv.AddUTF8String(3, value.Identifier);
    }

    private static void WriteRatingNameStruct(MatterTLV tlv, byte tag, RatingNameStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteRatingNameStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteRatingNameStruct(MatterTLV tlv, RatingNameStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteRatingNameStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteRatingNameStructFields(MatterTLV tlv, RatingNameStruct value)
    {
        tlv.AddUTF8String(0, value.RatingName);
        if (value.RatingNameDesc != null) tlv.AddUTF8String(1, value.RatingNameDesc);
    }

    private static void WriteTimePeriodStruct(MatterTLV tlv, byte tag, TimePeriodStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteTimePeriodStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTimePeriodStruct(MatterTLV tlv, TimePeriodStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteTimePeriodStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTimePeriodStructFields(MatterTLV tlv, TimePeriodStruct value)
    {
        tlv.AddUInt8(0, value.StartHour);
        tlv.AddUInt8(1, value.StartMinute);
        tlv.AddUInt8(2, value.EndHour);
        tlv.AddUInt8(3, value.EndMinute);
    }

    private static void WriteTimeWindowStruct(MatterTLV tlv, byte tag, TimeWindowStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteTimeWindowStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTimeWindowStruct(MatterTLV tlv, TimeWindowStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteTimeWindowStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTimeWindowStructFields(MatterTLV tlv, TimeWindowStruct value)
    {
        if (value.TimeWindowIndex != null) { tlv.AddUInt16(0, value.TimeWindowIndex.Value); } else { tlv.AddNull(0); }
        tlv.AddUInt8(1, (byte)value.DayOfWeek);
        if (value.TimePeriod != null) { tlv.AddArray(2); foreach (var item in value.TimePeriod) { WriteTimePeriodStruct(tlv, item); } tlv.EndContainer(); }
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>Enabled (0x0000).</summary>
        public const uint Enabled = 0x0000;
        /// <summary>OnDemandRatings (0x0001).</summary>
        public const uint OnDemandRatings = 0x0001;
        /// <summary>OnDemandRatingThreshold (0x0002).</summary>
        public const uint OnDemandRatingThreshold = 0x0002;
        /// <summary>ScheduledContentRatings (0x0003).</summary>
        public const uint ScheduledContentRatings = 0x0003;
        /// <summary>ScheduledContentRatingThreshold (0x0004).</summary>
        public const uint ScheduledContentRatingThreshold = 0x0004;
        /// <summary>ScreenDailyTime (0x0005).</summary>
        public const uint ScreenDailyTime = 0x0005;
        /// <summary>RemainingScreenTime (0x0006).</summary>
        public const uint RemainingScreenTime = 0x0006;
        /// <summary>BlockUnrated (0x0007).</summary>
        public const uint BlockUnrated = 0x0007;
        /// <summary>BlockChannelList (0x0008).</summary>
        public const uint BlockChannelList = 0x0008;
        /// <summary>BlockApplicationList (0x0009).</summary>
        public const uint BlockApplicationList = 0x0009;
        /// <summary>BlockContentTimeWindow (0x000A).</summary>
        public const uint BlockContentTimeWindow = 0x000A;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>UpdatePIN (0x0000).</summary>
        public const uint UpdatePIN = 0x0000;
        /// <summary>ResetPIN (0x0001).</summary>
        public const uint ResetPIN = 0x0001;
        /// <summary>Enable (0x0003).</summary>
        public const uint Enable = 0x0003;
        /// <summary>Disable (0x0004).</summary>
        public const uint Disable = 0x0004;
        /// <summary>AddBonusTime (0x0005).</summary>
        public const uint AddBonusTime = 0x0005;
        /// <summary>SetScreenDailyTime (0x0006).</summary>
        public const uint SetScreenDailyTime = 0x0006;
        /// <summary>BlockUnratedContent (0x0007).</summary>
        public const uint BlockUnratedContent = 0x0007;
        /// <summary>UnblockUnratedContent (0x0008).</summary>
        public const uint UnblockUnratedContent = 0x0008;
        /// <summary>SetOnDemandRatingThreshold (0x0009).</summary>
        public const uint SetOnDemandRatingThreshold = 0x0009;
        /// <summary>SetScheduledContentRatingThreshold (0x000A).</summary>
        public const uint SetScheduledContentRatingThreshold = 0x000A;
        /// <summary>AddBlockChannels (0x000B).</summary>
        public const uint AddBlockChannels = 0x000B;
        /// <summary>RemoveBlockChannels (0x000C).</summary>
        public const uint RemoveBlockChannels = 0x000C;
        /// <summary>AddBlockApplications (0x000D).</summary>
        public const uint AddBlockApplications = 0x000D;
        /// <summary>RemoveBlockApplications (0x000E).</summary>
        public const uint RemoveBlockApplications = 0x000E;
        /// <summary>SetBlockContentTimeWindow (0x000F).</summary>
        public const uint SetBlockContentTimeWindow = 0x000F;
        /// <summary>RemoveBlockContentTimeWindow (0x0010).</summary>
        public const uint RemoveBlockContentTimeWindow = 0x0010;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>RemainingScreenTimeExpired (0x0000).</summary>
        public const uint RemainingScreenTimeExpired = 0x0000;
        /// <summary>EnteringBlockContentTimeWindow (0x0001).</summary>
        public const uint EnteringBlockContentTimeWindow = 0x0001;
    }

    // Async command methods

    /// <summary>Send UpdatePIN command (0x0000).</summary>
    public Task<InvokeResponse> UpdatePINAsync(
        string oldPIN,
        string newPIN,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUTF8String(0, oldPIN);
            tlv.AddUTF8String(1, newPIN);
        }, ct);

    /// <summary>Send ResetPIN command (0x0001).</summary>
    public Task<InvokeResponse> ResetPINAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, ct: ct);

    /// <summary>Send Enable command (0x0003).</summary>
    public Task<InvokeResponse> EnableAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, ct: ct);

    /// <summary>Send Disable command (0x0004).</summary>
    public Task<InvokeResponse> DisableAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, ct: ct);

    /// <summary>Send AddBonusTime command (0x0005).</summary>
    public Task<InvokeResponse> AddBonusTimeAsync(
        uint bonusTime,
        string? pINCode = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv =>
        {
            if (pINCode != null) tlv.AddUTF8String(0, pINCode);
            tlv.AddUInt32(1, bonusTime);
        }, ct);

    /// <summary>Send SetScreenDailyTime command (0x0006).</summary>
    public Task<InvokeResponse> SetScreenDailyTimeAsync(
        uint screenTime,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv => { tlv.AddUInt32(0, screenTime); }, ct);

    /// <summary>Send BlockUnratedContent command (0x0007).</summary>
    public Task<InvokeResponse> BlockUnratedContentAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0007, ct: ct);

    /// <summary>Send UnblockUnratedContent command (0x0008).</summary>
    public Task<InvokeResponse> UnblockUnratedContentAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0008, ct: ct);

    /// <summary>Send SetOnDemandRatingThreshold command (0x0009).</summary>
    public Task<InvokeResponse> SetOnDemandRatingThresholdAsync(
        string rating,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0009, tlv => { tlv.AddUTF8String(0, rating); }, ct);

    /// <summary>Send SetScheduledContentRatingThreshold command (0x000A).</summary>
    public Task<InvokeResponse> SetScheduledContentRatingThresholdAsync(
        string rating,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000A, tlv => { tlv.AddUTF8String(0, rating); }, ct);

    /// <summary>Send AddBlockChannels command (0x000B).</summary>
    public Task<InvokeResponse> AddBlockChannelsAsync(
        BlockChannelStruct[] channels,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000B, tlv => { if (channels != null) { tlv.AddArray(0); foreach (var item in channels) { WriteBlockChannelStruct(tlv, item); } tlv.EndContainer(); } }, ct);

    /// <summary>Send RemoveBlockChannels command (0x000C).</summary>
    public Task<InvokeResponse> RemoveBlockChannelsAsync(
        ushort[] channelIndexes,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000C, tlv => { if (channelIndexes != null) { tlv.AddArray(0); foreach (var item in channelIndexes) { tlv.AddUInt16(item); } tlv.EndContainer(); } }, ct);

    /// <summary>Send AddBlockApplications command (0x000D).</summary>
    public Task<InvokeResponse> AddBlockApplicationsAsync(
        AppInfoStruct[] applications,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000D, tlv => { if (applications != null) { tlv.AddArray(0); foreach (var item in applications) { WriteAppInfoStruct(tlv, item); } tlv.EndContainer(); } }, ct);

    /// <summary>Send RemoveBlockApplications command (0x000E).</summary>
    public Task<InvokeResponse> RemoveBlockApplicationsAsync(
        AppInfoStruct[] applications,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000E, tlv => { if (applications != null) { tlv.AddArray(0); foreach (var item in applications) { WriteAppInfoStruct(tlv, item); } tlv.EndContainer(); } }, ct);

    /// <summary>Send SetBlockContentTimeWindow command (0x000F).</summary>
    public Task<InvokeResponse> SetBlockContentTimeWindowAsync(
        TimeWindowStruct timeWindow,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000F, tlv => { WriteTimeWindowStruct(tlv, 0, timeWindow); }, ct);

    /// <summary>Send RemoveBlockContentTimeWindow command (0x0010).</summary>
    public Task<InvokeResponse> RemoveBlockContentTimeWindowAsync(
        ushort[] timeWindowIndexes,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0010, tlv => { if (timeWindowIndexes != null) { tlv.AddArray(0); foreach (var item in timeWindowIndexes) { tlv.AddUInt16(item); } tlv.EndContainer(); } }, ct);

    // Attribute readers

    /// <summary>Read Enabled attribute (0x0000).</summary>
    public Task<bool> ReadEnabledAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0000, ct);

    /// <summary>Read OnDemandRatings attribute (0x0001).</summary>
    public Task<RatingNameStruct[]?> ReadOnDemandRatingsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<RatingNameStruct[]>(0x0001, ct);

    /// <summary>Read OnDemandRatingThreshold attribute (0x0002).</summary>
    public Task<string?> ReadOnDemandRatingThresholdAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0002, ct);

    /// <summary>Read ScheduledContentRatings attribute (0x0003).</summary>
    public Task<RatingNameStruct[]?> ReadScheduledContentRatingsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<RatingNameStruct[]>(0x0003, ct);

    /// <summary>Read ScheduledContentRatingThreshold attribute (0x0004).</summary>
    public Task<string?> ReadScheduledContentRatingThresholdAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0004, ct);

    /// <summary>Read ScreenDailyTime attribute (0x0005).</summary>
    public Task<uint> ReadScreenDailyTimeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0005, ct);

    /// <summary>Read RemainingScreenTime attribute (0x0006).</summary>
    public Task<uint> ReadRemainingScreenTimeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0006, ct);

    /// <summary>Read BlockUnrated attribute (0x0007).</summary>
    public Task<bool> ReadBlockUnratedAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0007, ct);

    /// <summary>Read BlockChannelList attribute (0x0008).</summary>
    public Task<BlockChannelStruct[]?> ReadBlockChannelListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<BlockChannelStruct[]>(0x0008, ct);

    /// <summary>Read BlockApplicationList attribute (0x0009).</summary>
    public Task<AppInfoStruct[]?> ReadBlockApplicationListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<AppInfoStruct[]>(0x0009, ct);

    /// <summary>Read BlockContentTimeWindow attribute (0x000A).</summary>
    public Task<TimeWindowStruct[]?> ReadBlockContentTimeWindowAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<TimeWindowStruct[]>(0x000A, ct);
}
