// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: content-launch-cluster.xml
// Cluster: Content Launcher (0x050A)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Content Launcher (0x050A, rev 1)</summary>
public class ContentLauncherCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x050A;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ContentLauncherCluster"/> bound to the given session and endpoint.</summary>
    public ContentLauncherCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>MetricTypeEnum enum values.</summary>
    public enum MetricTypeEnum : byte
    {
        /// <summary>Pixels value.</summary>
        Pixels = 0x00,
        /// <summary>Percentage value.</summary>
        Percentage = 0x01,
    }

    /// <summary>ParameterEnum enum values.</summary>
    public enum ParameterEnum : byte
    {
        /// <summary>Actor value.</summary>
        Actor = 0x00,
        /// <summary>Channel value.</summary>
        Channel = 0x01,
        /// <summary>Character value.</summary>
        Character = 0x02,
        /// <summary>Director value.</summary>
        Director = 0x03,
        /// <summary>Event value.</summary>
        Event = 0x04,
        /// <summary>Franchise value.</summary>
        Franchise = 0x05,
        /// <summary>Genre value.</summary>
        Genre = 0x06,
        /// <summary>League value.</summary>
        League = 0x07,
        /// <summary>Popularity value.</summary>
        Popularity = 0x08,
        /// <summary>Provider value.</summary>
        Provider = 0x09,
        /// <summary>Sport value.</summary>
        Sport = 0x0A,
        /// <summary>SportsTeam value.</summary>
        SportsTeam = 0x0B,
        /// <summary>Type value.</summary>
        Type = 0x0C,
        /// <summary>Video value.</summary>
        Video = 0x0D,
        /// <summary>Season value.</summary>
        Season = 0x0E,
        /// <summary>Episode value.</summary>
        Episode = 0x0F,
        /// <summary>Any value.</summary>
        Any = 0x10,
    }

    /// <summary>StatusEnum enum values.</summary>
    public enum StatusEnum : byte
    {
        /// <summary>Success value.</summary>
        Success = 0x00,
        /// <summary>URLNotAvailable value.</summary>
        URLNotAvailable = 0x01,
        /// <summary>AuthFailed value.</summary>
        AuthFailed = 0x02,
        /// <summary>TextTrackNotAvailable value.</summary>
        TextTrackNotAvailable = 0x03,
        /// <summary>AudioTrackNotAvailable value.</summary>
        AudioTrackNotAvailable = 0x04,
    }

    /// <summary>CharacteristicEnum enum values.</summary>
    public enum CharacteristicEnum : byte
    {
        /// <summary>ForcedSubtitles value.</summary>
        ForcedSubtitles = 0x00,
        /// <summary>DescribesVideo value.</summary>
        DescribesVideo = 0x01,
        /// <summary>EasyToRead value.</summary>
        EasyToRead = 0x02,
        /// <summary>FrameBased value.</summary>
        FrameBased = 0x03,
        /// <summary>MainProgram value.</summary>
        MainProgram = 0x04,
        /// <summary>OriginalContent value.</summary>
        OriginalContent = 0x05,
        /// <summary>VoiceOverTranslation value.</summary>
        VoiceOverTranslation = 0x06,
        /// <summary>Caption value.</summary>
        Caption = 0x07,
        /// <summary>Subtitle value.</summary>
        Subtitle = 0x08,
        /// <summary>Alternate value.</summary>
        Alternate = 0x09,
        /// <summary>Supplementary value.</summary>
        Supplementary = 0x0A,
        /// <summary>Commentary value.</summary>
        Commentary = 0x0B,
        /// <summary>DubbedTranslation value.</summary>
        DubbedTranslation = 0x0C,
        /// <summary>Description value.</summary>
        Description = 0x0D,
        /// <summary>Metadata value.</summary>
        Metadata = 0x0E,
        /// <summary>EnhancedAudioIntelligibility value.</summary>
        EnhancedAudioIntelligibility = 0x0F,
        /// <summary>Emergency value.</summary>
        Emergency = 0x10,
        /// <summary>Karaoke value.</summary>
        Karaoke = 0x11,
    }

    /// <summary>SupportedProtocolsBitmap bitmap flags.</summary>
    [System.Flags]
    public enum SupportedProtocolsBitmap : uint
    {
        /// <summary>DASH flag.</summary>
        DASH = 1u << 0,
        /// <summary>HLS flag.</summary>
        HLS = 1u << 1,
    }

    /// <summary>Feature bitmap flags.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>ContentSearch flag.</summary>
        ContentSearch = 1u << 0,
        /// <summary>URLPlayback flag.</summary>
        URLPlayback = 1u << 1,
        /// <summary>AdvancedSeek flag.</summary>
        AdvancedSeek = 1u << 2,
        /// <summary>TextTracks flag.</summary>
        TextTracks = 1u << 3,
        /// <summary>AudioTracks flag.</summary>
        AudioTracks = 1u << 4,
    }

    /// <summary>ContentSearchStruct struct.</summary>
    public sealed class ContentSearchStruct
    {
        /// <summary>Gets or sets ParameterList.</summary>
        public ParameterStruct[] ParameterList { get; set; } = default!;
    }

    /// <summary>AdditionalInfoStruct struct.</summary>
    public sealed class AdditionalInfoStruct
    {
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
        /// <summary>Gets or sets Value.</summary>
        public string Value { get; set; } = default!;
    }

    /// <summary>DimensionStruct struct.</summary>
    public sealed class DimensionStruct
    {
        /// <summary>Gets or sets Width.</summary>
        public double Width { get; set; }
        /// <summary>Gets or sets Height.</summary>
        public double Height { get; set; }
        /// <summary>Gets or sets Metric.</summary>
        public MetricTypeEnum Metric { get; set; } = default!;
    }

    /// <summary>StyleInformationStruct struct.</summary>
    public sealed class StyleInformationStruct
    {
        /// <summary>Gets or sets ImageURL.</summary>
        public string? ImageURL { get; set; }
        /// <summary>Gets or sets Color.</summary>
        public string? Color { get; set; }
        /// <summary>Gets or sets Size.</summary>
        public DimensionStruct? Size { get; set; }
    }

    /// <summary>BrandingInformationStruct struct.</summary>
    public sealed class BrandingInformationStruct
    {
        /// <summary>Gets or sets ProviderName.</summary>
        public string ProviderName { get; set; } = default!;
        /// <summary>Gets or sets Background.</summary>
        public StyleInformationStruct? Background { get; set; }
        /// <summary>Gets or sets Logo.</summary>
        public StyleInformationStruct? Logo { get; set; }
        /// <summary>Gets or sets ProgressBar.</summary>
        public StyleInformationStruct? ProgressBar { get; set; }
        /// <summary>Gets or sets Splash.</summary>
        public StyleInformationStruct? Splash { get; set; }
        /// <summary>Gets or sets WaterMark.</summary>
        public StyleInformationStruct? WaterMark { get; set; }
    }

    /// <summary>ParameterStruct struct.</summary>
    public sealed class ParameterStruct
    {
        /// <summary>Gets or sets Type.</summary>
        public ParameterEnum Type { get; set; } = default!;
        /// <summary>Gets or sets Value.</summary>
        public string Value { get; set; } = default!;
        /// <summary>Gets or sets ExternalIDList.</summary>
        public AdditionalInfoStruct[]? ExternalIDList { get; set; }
    }

    /// <summary>PlaybackPreferencesStruct struct.</summary>
    public sealed class PlaybackPreferencesStruct
    {
        /// <summary>Gets or sets PlaybackPosition.</summary>
        public ulong PlaybackPosition { get; set; }
        /// <summary>Gets or sets TextTrack.</summary>
        public TrackPreferenceStruct TextTrack { get; set; } = default!;
        /// <summary>Gets or sets AudioTracks.</summary>
        public TrackPreferenceStruct[]? AudioTracks { get; set; }
    }

    /// <summary>TrackPreferenceStruct struct.</summary>
    public sealed class TrackPreferenceStruct
    {
        /// <summary>Gets or sets LanguageCode.</summary>
        public string LanguageCode { get; set; } = default!;
        /// <summary>Gets or sets Characteristics.</summary>
        public CharacteristicEnum[]? Characteristics { get; set; }
        /// <summary>Gets or sets AudioOutputIndex.</summary>
        public byte AudioOutputIndex { get; set; }
    }

    // TLV struct serializers

    private static void WriteContentSearchStruct(MatterTLV tlv, byte tag, ContentSearchStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteContentSearchStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteContentSearchStruct(MatterTLV tlv, ContentSearchStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteContentSearchStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteContentSearchStructFields(MatterTLV tlv, ContentSearchStruct value)
    {
        if (value.ParameterList != null) { tlv.AddArray(0); foreach (var item in value.ParameterList) { WriteParameterStruct(tlv, item); } tlv.EndContainer(); }
    }

    private static void WriteAdditionalInfoStruct(MatterTLV tlv, byte tag, AdditionalInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteAdditionalInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAdditionalInfoStruct(MatterTLV tlv, AdditionalInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteAdditionalInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAdditionalInfoStructFields(MatterTLV tlv, AdditionalInfoStruct value)
    {
        tlv.AddUTF8String(0, value.Name);
        tlv.AddUTF8String(1, value.Value);
    }

    private static void WriteDimensionStruct(MatterTLV tlv, byte tag, DimensionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDimensionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDimensionStruct(MatterTLV tlv, DimensionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDimensionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDimensionStructFields(MatterTLV tlv, DimensionStruct value)
    {
        tlv.AddDouble(0, value.Width);
        tlv.AddDouble(1, value.Height);
        tlv.AddUInt8(2, (byte)value.Metric);
    }

    private static void WriteStyleInformationStruct(MatterTLV tlv, byte tag, StyleInformationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteStyleInformationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteStyleInformationStruct(MatterTLV tlv, StyleInformationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteStyleInformationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteStyleInformationStructFields(MatterTLV tlv, StyleInformationStruct value)
    {
        if (value.ImageURL != null) tlv.AddUTF8String(0, value.ImageURL);
        if (value.Color != null) tlv.AddUTF8String(1, value.Color);
        if (value.Size != null) WriteDimensionStruct(tlv, 2, value.Size);
    }

    private static void WriteBrandingInformationStruct(MatterTLV tlv, byte tag, BrandingInformationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteBrandingInformationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBrandingInformationStruct(MatterTLV tlv, BrandingInformationStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteBrandingInformationStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBrandingInformationStructFields(MatterTLV tlv, BrandingInformationStruct value)
    {
        tlv.AddUTF8String(0, value.ProviderName);
        if (value.Background != null) WriteStyleInformationStruct(tlv, 1, value.Background);
        if (value.Logo != null) WriteStyleInformationStruct(tlv, 2, value.Logo);
        if (value.ProgressBar != null) WriteStyleInformationStruct(tlv, 3, value.ProgressBar);
        if (value.Splash != null) WriteStyleInformationStruct(tlv, 4, value.Splash);
        if (value.WaterMark != null) WriteStyleInformationStruct(tlv, 5, value.WaterMark);
    }

    private static void WriteParameterStruct(MatterTLV tlv, byte tag, ParameterStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteParameterStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteParameterStruct(MatterTLV tlv, ParameterStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteParameterStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteParameterStructFields(MatterTLV tlv, ParameterStruct value)
    {
        tlv.AddUInt8(0, (byte)value.Type);
        tlv.AddUTF8String(1, value.Value);
        if (value.ExternalIDList != null) { tlv.AddArray(2); foreach (var item in value.ExternalIDList) { WriteAdditionalInfoStruct(tlv, item); } tlv.EndContainer(); }
    }

    private static void WritePlaybackPreferencesStruct(MatterTLV tlv, byte tag, PlaybackPreferencesStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WritePlaybackPreferencesStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePlaybackPreferencesStruct(MatterTLV tlv, PlaybackPreferencesStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WritePlaybackPreferencesStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePlaybackPreferencesStructFields(MatterTLV tlv, PlaybackPreferencesStruct value)
    {
        tlv.AddUInt64(0, value.PlaybackPosition);
        WriteTrackPreferenceStruct(tlv, 1, value.TextTrack);
        if (value.AudioTracks != null) { tlv.AddArray(2); foreach (var item in value.AudioTracks) { WriteTrackPreferenceStruct(tlv, item); } tlv.EndContainer(); }
    }

    private static void WriteTrackPreferenceStruct(MatterTLV tlv, byte tag, TrackPreferenceStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteTrackPreferenceStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTrackPreferenceStruct(MatterTLV tlv, TrackPreferenceStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteTrackPreferenceStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTrackPreferenceStructFields(MatterTLV tlv, TrackPreferenceStruct value)
    {
        tlv.AddUTF8String(0, value.LanguageCode);
        if (value.Characteristics != null) { tlv.AddArray(1); foreach (var item in value.Characteristics) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
        tlv.AddUInt8(2, value.AudioOutputIndex);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>AcceptHeader (0x0000).</summary>
        public const uint AcceptHeader = 0x0000;
        /// <summary>SupportedStreamingProtocols (0x0001).</summary>
        public const uint SupportedStreamingProtocols = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>LaunchContent (0x0000).</summary>
        public const uint LaunchContent = 0x0000;
        /// <summary>LaunchURL (0x0001).</summary>
        public const uint LaunchURL = 0x0001;
    }

    // Async command methods

    /// <summary>Send LaunchContent command (0x0000).</summary>
    public Task<InvokeResponse> LaunchContentAsync(
        ContentSearchStruct search,
        bool autoPlay,
        string? data = default,
        PlaybackPreferencesStruct? playbackPreferences = default,
        bool? useCurrentContext = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            WriteContentSearchStruct(tlv, 0, search);
            tlv.AddBool(1, autoPlay);
            if (data != null) tlv.AddUTF8String(2, data);
            if (playbackPreferences != null) WritePlaybackPreferencesStruct(tlv, 3, playbackPreferences);
            if (useCurrentContext != null) tlv.AddBool(4, useCurrentContext.Value);
        }, ct);

    /// <summary>Send LaunchURL command (0x0001).</summary>
    public Task<InvokeResponse> LaunchURLAsync(
        string contentURL,
        string? displayString = default,
        BrandingInformationStruct? brandingInformation = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            tlv.AddUTF8String(0, contentURL);
            if (displayString != null) tlv.AddUTF8String(1, displayString);
            if (brandingInformation != null) WriteBrandingInformationStruct(tlv, 2, brandingInformation);
        }, ct);

    // Attribute readers

    /// <summary>Read AcceptHeader attribute (0x0000).</summary>
    public Task<string[]?> ReadAcceptHeaderAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string[]>(0x0000, ct);

    /// <summary>Read SupportedStreamingProtocols attribute (0x0001).</summary>
    public Task<SupportedProtocolsBitmap> ReadSupportedStreamingProtocolsAsync(CancellationToken ct = default)
        => ReadAttributeAsync<SupportedProtocolsBitmap>(0x0001, ct);
}
