// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: device-energy-management-cluster.xml
// Cluster: Device Energy Management (0x0098)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Device Energy Management (0x0098, rev 4)</summary>
public class DeviceEnergyManagementCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0098;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="DeviceEnergyManagementCluster"/> bound to the given session and endpoint.</summary>
    public DeviceEnergyManagementCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Allows an EMS to make a temporary power adjustment (within the limits offered by the ESA).</summary>
        PowerAdjustment = 1u << 0,
        /// <summary>Allows an ESA to advertise its indicative future power consumption vs time.</summary>
        PowerForecastReporting = 1u << 1,
        /// <summary>Allows an ESA to advertise its indicative future state vs time.</summary>
        StateForecastReporting = 1u << 2,
        /// <summary>Allows an EMS to delay an ESA's planned operation.</summary>
        StartTimeAdjustment = 1u << 3,
        /// <summary>Allows an EMS to pause an ESA's planned operation.</summary>
        Pausable = 1u << 4,
        /// <summary>Allows an EMS to adjust an ESA's planned operation.</summary>
        ForecastAdjustment = 1u << 5,
        /// <summary>Allows an EMS to request constraints to an ESA's planned operation.</summary>
        ConstraintBasedAdjustment = 1u << 6,
    }

    /// <summary>CostTypeEnum enum values.</summary>
    public enum CostTypeEnum : byte
    {
        /// <summary>Financial value.</summary>
        Financial = 0x00,
        /// <summary>GHGEmissions value.</summary>
        GHGEmissions = 0x01,
        /// <summary>Comfort value.</summary>
        Comfort = 0x02,
        /// <summary>Temperature value.</summary>
        Temperature = 0x03,
    }

    /// <summary>ESATypeEnum enum values.</summary>
    public enum ESATypeEnum : byte
    {
        /// <summary>EVSE value.</summary>
        EVSE = 0x00,
        /// <summary>SpaceHeating value.</summary>
        SpaceHeating = 0x01,
        /// <summary>WaterHeating value.</summary>
        WaterHeating = 0x02,
        /// <summary>SpaceCooling value.</summary>
        SpaceCooling = 0x03,
        /// <summary>SpaceHeatingCooling value.</summary>
        SpaceHeatingCooling = 0x04,
        /// <summary>BatteryStorage value.</summary>
        BatteryStorage = 0x05,
        /// <summary>SolarPV value.</summary>
        SolarPV = 0x06,
        /// <summary>FridgeFreezer value.</summary>
        FridgeFreezer = 0x07,
        /// <summary>WashingMachine value.</summary>
        WashingMachine = 0x08,
        /// <summary>Dishwasher value.</summary>
        Dishwasher = 0x09,
        /// <summary>Cooking value.</summary>
        Cooking = 0x0A,
        /// <summary>HomeWaterPump value.</summary>
        HomeWaterPump = 0x0B,
        /// <summary>IrrigationWaterPump value.</summary>
        IrrigationWaterPump = 0x0C,
        /// <summary>PoolPump value.</summary>
        PoolPump = 0x0D,
        /// <summary>Other value.</summary>
        Other = 0xFF,
    }

    /// <summary>ESAStateEnum enum values.</summary>
    public enum ESAStateEnum : byte
    {
        /// <summary>Offline value.</summary>
        Offline = 0x00,
        /// <summary>Online value.</summary>
        Online = 0x01,
        /// <summary>Fault value.</summary>
        Fault = 0x02,
        /// <summary>PowerAdjustActive value.</summary>
        PowerAdjustActive = 0x03,
        /// <summary>Paused value.</summary>
        Paused = 0x04,
    }

    /// <summary>CauseEnum enum values.</summary>
    public enum CauseEnum : byte
    {
        /// <summary>NormalCompletion value.</summary>
        NormalCompletion = 0x00,
        /// <summary>Offline value.</summary>
        Offline = 0x01,
        /// <summary>Fault value.</summary>
        Fault = 0x02,
        /// <summary>UserOptOut value.</summary>
        UserOptOut = 0x03,
        /// <summary>Cancelled value.</summary>
        Cancelled = 0x04,
    }

    /// <summary>AdjustmentCauseEnum enum values.</summary>
    public enum AdjustmentCauseEnum : byte
    {
        /// <summary>LocalOptimization value.</summary>
        LocalOptimization = 0x00,
        /// <summary>GridOptimization value.</summary>
        GridOptimization = 0x01,
    }

    /// <summary>ForecastUpdateReasonEnum enum values.</summary>
    public enum ForecastUpdateReasonEnum : byte
    {
        /// <summary>InternalOptimization value.</summary>
        InternalOptimization = 0x00,
        /// <summary>LocalOptimization value.</summary>
        LocalOptimization = 0x01,
        /// <summary>GridOptimization value.</summary>
        GridOptimization = 0x02,
    }

    /// <summary>OptOutStateEnum enum values.</summary>
    public enum OptOutStateEnum : byte
    {
        /// <summary>NoOptOut value.</summary>
        NoOptOut = 0x00,
        /// <summary>LocalOptOut value.</summary>
        LocalOptOut = 0x01,
        /// <summary>GridOptOut value.</summary>
        GridOptOut = 0x02,
        /// <summary>OptOut value.</summary>
        OptOut = 0x03,
    }

    /// <summary>PowerAdjustReasonEnum enum values.</summary>
    public enum PowerAdjustReasonEnum : byte
    {
        /// <summary>NoAdjustment value.</summary>
        NoAdjustment = 0x00,
        /// <summary>LocalOptimizationAdjustment value.</summary>
        LocalOptimizationAdjustment = 0x01,
        /// <summary>GridOptimizationAdjustment value.</summary>
        GridOptimizationAdjustment = 0x02,
    }

    /// <summary>CostStruct struct.</summary>
    public sealed class CostStruct
    {
        /// <summary>Gets or sets CostType.</summary>
        public CostTypeEnum CostType { get; set; } = default!;
        /// <summary>Gets or sets Value.</summary>
        public int Value { get; set; }
        /// <summary>Gets or sets DecimalPoints.</summary>
        public byte DecimalPoints { get; set; }
        /// <summary>Gets or sets Currency.</summary>
        public ushort? Currency { get; set; }
    }

    /// <summary>PowerAdjustCapabilityStruct struct.</summary>
    public sealed class PowerAdjustCapabilityStruct
    {
        /// <summary>Gets or sets PowerAdjustCapability.</summary>
        public PowerAdjustStruct[]? PowerAdjustCapability { get; set; }
        /// <summary>Gets or sets Cause.</summary>
        public PowerAdjustReasonEnum Cause { get; set; } = default!;
    }

    /// <summary>PowerAdjustStruct struct.</summary>
    public sealed class PowerAdjustStruct
    {
        /// <summary>Gets or sets MinPower.</summary>
        public ulong MinPower { get; set; }
        /// <summary>Gets or sets MaxPower.</summary>
        public ulong MaxPower { get; set; }
        /// <summary>Gets or sets MinDuration.</summary>
        public uint MinDuration { get; set; }
        /// <summary>Gets or sets MaxDuration.</summary>
        public uint MaxDuration { get; set; }
    }

    /// <summary>ForecastStruct struct.</summary>
    public sealed class ForecastStruct
    {
        /// <summary>Gets or sets ForecastID.</summary>
        public uint ForecastID { get; set; }
        /// <summary>Gets or sets ActiveSlotNumber.</summary>
        public ushort? ActiveSlotNumber { get; set; }
        /// <summary>Gets or sets StartTime.</summary>
        public uint StartTime { get; set; }
        /// <summary>Gets or sets EndTime.</summary>
        public uint EndTime { get; set; }
        /// <summary>Gets or sets EarliestStartTime.</summary>
        public uint? EarliestStartTime { get; set; }
        /// <summary>Gets or sets LatestEndTime.</summary>
        public uint? LatestEndTime { get; set; }
        /// <summary>Gets or sets IsPausable.</summary>
        public bool IsPausable { get; set; }
        /// <summary>Gets or sets Slots.</summary>
        public SlotStruct[] Slots { get; set; } = default!;
        /// <summary>Gets or sets ForecastUpdateReason.</summary>
        public ForecastUpdateReasonEnum ForecastUpdateReason { get; set; } = default!;
    }

    /// <summary>SlotStruct struct.</summary>
    public sealed class SlotStruct
    {
        /// <summary>Gets or sets MinDuration.</summary>
        public uint MinDuration { get; set; }
        /// <summary>Gets or sets MaxDuration.</summary>
        public uint MaxDuration { get; set; }
        /// <summary>Gets or sets DefaultDuration.</summary>
        public uint DefaultDuration { get; set; }
        /// <summary>Gets or sets ElapsedSlotTime.</summary>
        public uint ElapsedSlotTime { get; set; }
        /// <summary>Gets or sets RemainingSlotTime.</summary>
        public uint RemainingSlotTime { get; set; }
        /// <summary>Gets or sets SlotIsPausable.</summary>
        public bool? SlotIsPausable { get; set; }
        /// <summary>Gets or sets MinPauseDuration.</summary>
        public uint? MinPauseDuration { get; set; }
        /// <summary>Gets or sets MaxPauseDuration.</summary>
        public uint? MaxPauseDuration { get; set; }
        /// <summary>Gets or sets ManufacturerESAState.</summary>
        public ushort? ManufacturerESAState { get; set; }
        /// <summary>Gets or sets NominalPower.</summary>
        public ulong? NominalPower { get; set; }
        /// <summary>Gets or sets MinPower.</summary>
        public ulong? MinPower { get; set; }
        /// <summary>Gets or sets MaxPower.</summary>
        public ulong? MaxPower { get; set; }
        /// <summary>Gets or sets NominalEnergy.</summary>
        public ulong? NominalEnergy { get; set; }
        /// <summary>Gets or sets Costs.</summary>
        public CostStruct[]? Costs { get; set; }
        /// <summary>Gets or sets MinPowerAdjustment.</summary>
        public ulong? MinPowerAdjustment { get; set; }
        /// <summary>Gets or sets MaxPowerAdjustment.</summary>
        public ulong? MaxPowerAdjustment { get; set; }
        /// <summary>Gets or sets MinDurationAdjustment.</summary>
        public uint? MinDurationAdjustment { get; set; }
        /// <summary>Gets or sets MaxDurationAdjustment.</summary>
        public uint? MaxDurationAdjustment { get; set; }
    }

    /// <summary>SlotAdjustmentStruct struct.</summary>
    public sealed class SlotAdjustmentStruct
    {
        /// <summary>Gets or sets SlotIndex.</summary>
        public byte SlotIndex { get; set; }
        /// <summary>Gets or sets NominalPower.</summary>
        public ulong? NominalPower { get; set; }
        /// <summary>Gets or sets Duration.</summary>
        public uint Duration { get; set; }
    }

    /// <summary>ConstraintsStruct struct.</summary>
    public sealed class ConstraintsStruct
    {
        /// <summary>Gets or sets StartTime.</summary>
        public uint StartTime { get; set; }
        /// <summary>Gets or sets Duration.</summary>
        public uint Duration { get; set; }
        /// <summary>Gets or sets NominalPower.</summary>
        public ulong? NominalPower { get; set; }
        /// <summary>Gets or sets MaximumEnergy.</summary>
        public ulong? MaximumEnergy { get; set; }
        /// <summary>Gets or sets LoadControl.</summary>
        public sbyte? LoadControl { get; set; }
    }

    // TLV struct serializers

    private static void WriteCostStruct(MatterTLV tlv, byte tag, CostStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteCostStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCostStruct(MatterTLV tlv, CostStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteCostStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCostStructFields(MatterTLV tlv, CostStruct value)
    {
        tlv.AddUInt8(0, (byte)value.CostType);
        tlv.AddInt32(1, value.Value);
        tlv.AddUInt8(2, value.DecimalPoints);
        if (value.Currency != null) tlv.AddUInt16(3, value.Currency.Value);
    }

    private static void WritePowerAdjustCapabilityStruct(MatterTLV tlv, byte tag, PowerAdjustCapabilityStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WritePowerAdjustCapabilityStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePowerAdjustCapabilityStruct(MatterTLV tlv, PowerAdjustCapabilityStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WritePowerAdjustCapabilityStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePowerAdjustCapabilityStructFields(MatterTLV tlv, PowerAdjustCapabilityStruct value)
    {
        if (value.PowerAdjustCapability != null) { tlv.AddArray(0); foreach (var item in value.PowerAdjustCapability) { WritePowerAdjustStruct(tlv, item); } tlv.EndContainer(); } else { tlv.AddNull(0); }
        tlv.AddUInt8(1, (byte)value.Cause);
    }

    private static void WritePowerAdjustStruct(MatterTLV tlv, byte tag, PowerAdjustStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WritePowerAdjustStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePowerAdjustStruct(MatterTLV tlv, PowerAdjustStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WritePowerAdjustStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WritePowerAdjustStructFields(MatterTLV tlv, PowerAdjustStruct value)
    {
        tlv.AddUInt64(0, value.MinPower);
        tlv.AddUInt64(1, value.MaxPower);
        tlv.AddUInt32(2, value.MinDuration);
        tlv.AddUInt32(3, value.MaxDuration);
    }

    private static void WriteForecastStruct(MatterTLV tlv, byte tag, ForecastStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteForecastStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteForecastStruct(MatterTLV tlv, ForecastStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteForecastStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteForecastStructFields(MatterTLV tlv, ForecastStruct value)
    {
        tlv.AddUInt32(0, value.ForecastID);
        if (value.ActiveSlotNumber != null) { tlv.AddUInt16(1, value.ActiveSlotNumber.Value); } else { tlv.AddNull(1); }
        tlv.AddUInt32(2, value.StartTime);
        tlv.AddUInt32(3, value.EndTime);
        if (value.EarliestStartTime != null) tlv.AddUInt32(4, value.EarliestStartTime.Value);
        if (value.LatestEndTime != null) tlv.AddUInt32(5, value.LatestEndTime.Value);
        tlv.AddBool(6, value.IsPausable);
        if (value.Slots != null) { tlv.AddArray(7); foreach (var item in value.Slots) { WriteSlotStruct(tlv, item); } tlv.EndContainer(); }
        tlv.AddUInt8(8, (byte)value.ForecastUpdateReason);
    }

    private static void WriteSlotStruct(MatterTLV tlv, byte tag, SlotStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteSlotStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSlotStruct(MatterTLV tlv, SlotStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteSlotStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSlotStructFields(MatterTLV tlv, SlotStruct value)
    {
        tlv.AddUInt32(0, value.MinDuration);
        tlv.AddUInt32(1, value.MaxDuration);
        tlv.AddUInt32(2, value.DefaultDuration);
        tlv.AddUInt32(3, value.ElapsedSlotTime);
        tlv.AddUInt32(4, value.RemainingSlotTime);
        if (value.SlotIsPausable != null) tlv.AddBool(5, value.SlotIsPausable.Value);
        if (value.MinPauseDuration != null) tlv.AddUInt32(6, value.MinPauseDuration.Value);
        if (value.MaxPauseDuration != null) tlv.AddUInt32(7, value.MaxPauseDuration.Value);
        if (value.ManufacturerESAState != null) tlv.AddUInt16(8, value.ManufacturerESAState.Value);
        if (value.NominalPower != null) tlv.AddUInt64(9, value.NominalPower.Value);
        if (value.MinPower != null) tlv.AddUInt64(10, value.MinPower.Value);
        if (value.MaxPower != null) tlv.AddUInt64(11, value.MaxPower.Value);
        if (value.NominalEnergy != null) tlv.AddUInt64(12, value.NominalEnergy.Value);
        if (value.Costs != null) { tlv.AddArray(13); foreach (var item in value.Costs) { WriteCostStruct(tlv, item); } tlv.EndContainer(); }
        if (value.MinPowerAdjustment != null) tlv.AddUInt64(14, value.MinPowerAdjustment.Value);
        if (value.MaxPowerAdjustment != null) tlv.AddUInt64(15, value.MaxPowerAdjustment.Value);
        if (value.MinDurationAdjustment != null) tlv.AddUInt32(16, value.MinDurationAdjustment.Value);
        if (value.MaxDurationAdjustment != null) tlv.AddUInt32(17, value.MaxDurationAdjustment.Value);
    }

    private static void WriteSlotAdjustmentStruct(MatterTLV tlv, byte tag, SlotAdjustmentStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteSlotAdjustmentStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSlotAdjustmentStruct(MatterTLV tlv, SlotAdjustmentStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteSlotAdjustmentStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSlotAdjustmentStructFields(MatterTLV tlv, SlotAdjustmentStruct value)
    {
        tlv.AddUInt8(0, value.SlotIndex);
        if (value.NominalPower != null) tlv.AddUInt64(1, value.NominalPower.Value);
        tlv.AddUInt32(2, value.Duration);
    }

    private static void WriteConstraintsStruct(MatterTLV tlv, byte tag, ConstraintsStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteConstraintsStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteConstraintsStruct(MatterTLV tlv, ConstraintsStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteConstraintsStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteConstraintsStructFields(MatterTLV tlv, ConstraintsStruct value)
    {
        tlv.AddUInt32(0, value.StartTime);
        tlv.AddUInt32(1, value.Duration);
        if (value.NominalPower != null) tlv.AddUInt64(2, value.NominalPower.Value);
        if (value.MaximumEnergy != null) tlv.AddUInt64(3, value.MaximumEnergy.Value);
        if (value.LoadControl != null) tlv.AddInt8(4, value.LoadControl.Value);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>ESAType (0x0000).</summary>
        public const uint ESAType = 0x0000;
        /// <summary>ESACanGenerate (0x0001).</summary>
        public const uint ESACanGenerate = 0x0001;
        /// <summary>ESAState (0x0002).</summary>
        public const uint ESAState = 0x0002;
        /// <summary>AbsMinPower (0x0003).</summary>
        public const uint AbsMinPower = 0x0003;
        /// <summary>AbsMaxPower (0x0004).</summary>
        public const uint AbsMaxPower = 0x0004;
        /// <summary>PowerAdjustmentCapability (0x0005).</summary>
        public const uint PowerAdjustmentCapability = 0x0005;
        /// <summary>Forecast (0x0006).</summary>
        public const uint Forecast = 0x0006;
        /// <summary>OptOutState (0x0007).</summary>
        public const uint OptOutState = 0x0007;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>PowerAdjustRequest (0x0000).</summary>
        public const uint PowerAdjustRequest = 0x0000;
        /// <summary>CancelPowerAdjustRequest (0x0001).</summary>
        public const uint CancelPowerAdjustRequest = 0x0001;
        /// <summary>StartTimeAdjustRequest (0x0002).</summary>
        public const uint StartTimeAdjustRequest = 0x0002;
        /// <summary>PauseRequest (0x0003).</summary>
        public const uint PauseRequest = 0x0003;
        /// <summary>ResumeRequest (0x0004).</summary>
        public const uint ResumeRequest = 0x0004;
        /// <summary>ModifyForecastRequest (0x0005).</summary>
        public const uint ModifyForecastRequest = 0x0005;
        /// <summary>RequestConstraintBasedForecast (0x0006).</summary>
        public const uint RequestConstraintBasedForecast = 0x0006;
        /// <summary>CancelRequest (0x0007).</summary>
        public const uint CancelRequest = 0x0007;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>PowerAdjustStart (0x0000).</summary>
        public const uint PowerAdjustStart = 0x0000;
        /// <summary>PowerAdjustEnd (0x0001).</summary>
        public const uint PowerAdjustEnd = 0x0001;
        /// <summary>Paused (0x0002).</summary>
        public const uint Paused = 0x0002;
        /// <summary>Resumed (0x0003).</summary>
        public const uint Resumed = 0x0003;
    }

    // Async command methods

    /// <summary>Send PowerAdjustRequest command (0x0000).</summary>
    public Task<InvokeResponse> PowerAdjustRequestAsync(
        ulong power,
        uint duration,
        AdjustmentCauseEnum cause,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUInt64(0, power);
            tlv.AddUInt32(1, duration);
            tlv.AddUInt8(2, (byte)cause);
        }, ct);

    /// <summary>Send CancelPowerAdjustRequest command (0x0001).</summary>
    public Task<InvokeResponse> CancelPowerAdjustRequestAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, ct: ct);

    /// <summary>Send StartTimeAdjustRequest command (0x0002).</summary>
    public Task<InvokeResponse> StartTimeAdjustRequestAsync(
        uint requestedStartTime,
        AdjustmentCauseEnum cause,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv =>
        {
            tlv.AddUInt32(0, requestedStartTime);
            tlv.AddUInt8(1, (byte)cause);
        }, ct);

    /// <summary>Send PauseRequest command (0x0003).</summary>
    public Task<InvokeResponse> PauseRequestAsync(
        uint duration,
        AdjustmentCauseEnum cause,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv =>
        {
            tlv.AddUInt32(0, duration);
            tlv.AddUInt8(1, (byte)cause);
        }, ct);

    /// <summary>Send ResumeRequest command (0x0004).</summary>
    public Task<InvokeResponse> ResumeRequestAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, ct: ct);

    /// <summary>Send ModifyForecastRequest command (0x0005).</summary>
    public Task<InvokeResponse> ModifyForecastRequestAsync(
        uint forecastID,
        SlotAdjustmentStruct[] slotAdjustments,
        AdjustmentCauseEnum cause,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv =>
        {
            tlv.AddUInt32(0, forecastID);
            if (slotAdjustments != null) { tlv.AddArray(1); foreach (var item in slotAdjustments) { WriteSlotAdjustmentStruct(tlv, item); } tlv.EndContainer(); }
            tlv.AddUInt8(2, (byte)cause);
        }, ct);

    /// <summary>Send RequestConstraintBasedForecast command (0x0006).</summary>
    public Task<InvokeResponse> RequestConstraintBasedForecastAsync(
        ConstraintsStruct[] constraints,
        AdjustmentCauseEnum cause,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv =>
        {
            if (constraints != null) { tlv.AddArray(0); foreach (var item in constraints) { WriteConstraintsStruct(tlv, item); } tlv.EndContainer(); }
            tlv.AddUInt8(1, (byte)cause);
        }, ct);

    /// <summary>Send CancelRequest command (0x0007).</summary>
    public Task<InvokeResponse> CancelRequestAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0007, ct: ct);

    // Attribute readers

    /// <summary>Read ESAType attribute (0x0000).</summary>
    public Task<ESATypeEnum> ReadESATypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ESATypeEnum>(0x0000, ct);

    /// <summary>Read ESACanGenerate attribute (0x0001).</summary>
    public Task<bool> ReadESACanGenerateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0001, ct);

    /// <summary>Read ESAState attribute (0x0002).</summary>
    public Task<ESAStateEnum> ReadESAStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ESAStateEnum>(0x0002, ct);

    /// <summary>Read AbsMinPower attribute (0x0003).</summary>
    public Task<ulong> ReadAbsMinPowerAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0003, ct);

    /// <summary>Read AbsMaxPower attribute (0x0004).</summary>
    public Task<ulong> ReadAbsMaxPowerAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0004, ct);

    /// <summary>Read PowerAdjustmentCapability attribute (0x0005).</summary>
    public Task<object?> ReadPowerAdjustmentCapabilityAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0005, ct);

    /// <summary>Read Forecast attribute (0x0006).</summary>
    public Task<object?> ReadForecastAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0006, ct);

    /// <summary>Read OptOutState attribute (0x0007).</summary>
    public Task<OptOutStateEnum> ReadOptOutStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<OptOutStateEnum>(0x0007, ct);
}
