// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: diagnostic-logs-cluster.xml
// Cluster: Diagnostic Logs (0x0032)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Diagnostic Logs (0x0032, rev 1)</summary>
public class DiagnosticLogsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0032;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="DiagnosticLogsCluster"/> bound to the given session and endpoint.</summary>
    public DiagnosticLogsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>IntentEnum enum values.</summary>
    public enum IntentEnum : byte
    {
        /// <summary>EndUserSupport value.</summary>
        EndUserSupport = 0x00,
        /// <summary>NetworkDiag value.</summary>
        NetworkDiag = 0x01,
        /// <summary>CrashLogs value.</summary>
        CrashLogs = 0x02,
    }

    /// <summary>StatusEnum enum values.</summary>
    public enum StatusEnum : byte
    {
        /// <summary>Success value.</summary>
        Success = 0x00,
        /// <summary>Exhausted value.</summary>
        Exhausted = 0x01,
        /// <summary>NoLogs value.</summary>
        NoLogs = 0x02,
        /// <summary>Busy value.</summary>
        Busy = 0x03,
        /// <summary>Denied value.</summary>
        Denied = 0x04,
    }

    /// <summary>TransferProtocolEnum enum values.</summary>
    public enum TransferProtocolEnum : byte
    {
        /// <summary>ResponsePayload value.</summary>
        ResponsePayload = 0x00,
        /// <summary>BDX value.</summary>
        BDX = 0x01,
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>RetrieveLogsRequest (0x0000).</summary>
        public const uint RetrieveLogsRequest = 0x0000;
    }

    // Async command methods

    /// <summary>Send RetrieveLogsRequest command (0x0000).</summary>
    public Task<InvokeResponse> RetrieveLogsRequestAsync(
        IntentEnum intent,
        TransferProtocolEnum requestedProtocol,
        string? transferFileDesignator = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUInt8(0, (byte)intent);
            tlv.AddUInt8(1, (byte)requestedProtocol);
            if (transferFileDesignator != null) tlv.AddUTF8String(2, transferFileDesignator);
        }, ct);
}
