// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: electrical-power-measurement-cluster.xml (+1 merged XML file(s))
// Cluster: Electrical Power Measurement (0x0090)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Electrical Power Measurement (0x0090, rev 3)</summary>
public class ElectricalPowerMeasurementCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0090;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ElectricalPowerMeasurementCluster"/> bound to the given session and endpoint.</summary>
    public ElectricalPowerMeasurementCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Supports measurement of direct current</summary>
        DirectCurrent = 1u << 0,
        /// <summary>Supports measurement of alternating current</summary>
        AlternatingCurrent = 1u << 1,
        /// <summary>Supports polyphase measurements</summary>
        PolyphasePower = 1u << 2,
        /// <summary>Supports measurement of AC harmonics</summary>
        Harmonics = 1u << 3,
        /// <summary>Supports measurement of AC harmonic phases</summary>
        PowerQuality = 1u << 4,
    }

    /// <summary>PowerModeEnum enum values.</summary>
    public enum PowerModeEnum : byte
    {
        /// <summary>Unknown value.</summary>
        Unknown = 0x00,
        /// <summary>DC value.</summary>
        DC = 0x01,
        /// <summary>AC value.</summary>
        AC = 0x02,
    }

    /// <summary>MeasurementTypeEnum enum values.</summary>
    public enum MeasurementTypeEnum : ushort
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x0000,
        /// <summary>Voltage value.</summary>
        Voltage = 0x0001,
        /// <summary>ActiveCurrent value.</summary>
        ActiveCurrent = 0x0002,
        /// <summary>ReactiveCurrent value.</summary>
        ReactiveCurrent = 0x0003,
        /// <summary>ApparentCurrent value.</summary>
        ApparentCurrent = 0x0004,
        /// <summary>ActivePower value.</summary>
        ActivePower = 0x0005,
        /// <summary>ReactivePower value.</summary>
        ReactivePower = 0x0006,
        /// <summary>ApparentPower value.</summary>
        ApparentPower = 0x0007,
        /// <summary>RMSVoltage value.</summary>
        RMSVoltage = 0x0008,
        /// <summary>RMSCurrent value.</summary>
        RMSCurrent = 0x0009,
        /// <summary>RMSPower value.</summary>
        RMSPower = 0x000A,
        /// <summary>Frequency value.</summary>
        Frequency = 0x000B,
        /// <summary>PowerFactor value.</summary>
        PowerFactor = 0x000C,
        /// <summary>NeutralCurrent value.</summary>
        NeutralCurrent = 0x000D,
        /// <summary>ElectricalEnergy value.</summary>
        ElectricalEnergy = 0x000E,
        /// <summary>ReactiveEnergy value.</summary>
        ReactiveEnergy = 0x000F,
        /// <summary>ApparentEnergy value.</summary>
        ApparentEnergy = 0x0010,
    }

    /// <summary>MeasurementRangeStruct struct.</summary>
    public sealed class MeasurementRangeStruct
    {
        /// <summary>Gets or sets MeasurementType.</summary>
        public MeasurementTypeEnum MeasurementType { get; set; } = default!;
        /// <summary>Gets or sets Min.</summary>
        public long Min { get; set; }
        /// <summary>Gets or sets Max.</summary>
        public long Max { get; set; }
        /// <summary>Gets or sets StartTimestamp.</summary>
        public uint? StartTimestamp { get; set; }
        /// <summary>Gets or sets EndTimestamp.</summary>
        public uint? EndTimestamp { get; set; }
        /// <summary>Gets or sets MinTimestamp.</summary>
        public uint? MinTimestamp { get; set; }
        /// <summary>Gets or sets MaxTimestamp.</summary>
        public uint? MaxTimestamp { get; set; }
        /// <summary>Gets or sets StartSystime.</summary>
        public ulong? StartSystime { get; set; }
        /// <summary>Gets or sets EndSystime.</summary>
        public ulong? EndSystime { get; set; }
        /// <summary>Gets or sets MinSystime.</summary>
        public ulong? MinSystime { get; set; }
        /// <summary>Gets or sets MaxSystime.</summary>
        public ulong? MaxSystime { get; set; }
    }

    /// <summary>HarmonicMeasurementStruct struct.</summary>
    public sealed class HarmonicMeasurementStruct
    {
        /// <summary>Gets or sets Order.</summary>
        public byte Order { get; set; }
        /// <summary>Gets or sets Measurement.</summary>
        public long? Measurement { get; set; }
    }

    /// <summary>MeasurementAccuracyRangeStruct struct.</summary>
    public sealed class MeasurementAccuracyRangeStruct
    {
        /// <summary>Gets or sets RangeMin.</summary>
        public long RangeMin { get; set; }
        /// <summary>Gets or sets RangeMax.</summary>
        public long RangeMax { get; set; }
        /// <summary>Gets or sets PercentMax.</summary>
        public ushort? PercentMax { get; set; }
        /// <summary>Gets or sets PercentMin.</summary>
        public ushort? PercentMin { get; set; }
        /// <summary>Gets or sets PercentTypical.</summary>
        public ushort? PercentTypical { get; set; }
        /// <summary>Gets or sets FixedMax.</summary>
        public ulong? FixedMax { get; set; }
        /// <summary>Gets or sets FixedMin.</summary>
        public ulong? FixedMin { get; set; }
        /// <summary>Gets or sets FixedTypical.</summary>
        public ulong? FixedTypical { get; set; }
    }

    /// <summary>MeasurementAccuracyStruct struct.</summary>
    public sealed class MeasurementAccuracyStruct
    {
        /// <summary>Gets or sets MeasurementType.</summary>
        public MeasurementTypeEnum MeasurementType { get; set; } = default!;
        /// <summary>Gets or sets Measured.</summary>
        public bool Measured { get; set; }
        /// <summary>Gets or sets MinMeasuredValue.</summary>
        public long MinMeasuredValue { get; set; }
        /// <summary>Gets or sets MaxMeasuredValue.</summary>
        public long MaxMeasuredValue { get; set; }
        /// <summary>Gets or sets AccuracyRanges.</summary>
        public MeasurementAccuracyRangeStruct[] AccuracyRanges { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteMeasurementRangeStruct(MatterTLV tlv, byte tag, MeasurementRangeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMeasurementRangeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementRangeStruct(MatterTLV tlv, MeasurementRangeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMeasurementRangeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementRangeStructFields(MatterTLV tlv, MeasurementRangeStruct value)
    {
        tlv.AddUInt16(0, (ushort)value.MeasurementType);
        tlv.AddInt64(1, value.Min);
        tlv.AddInt64(2, value.Max);
        if (value.StartTimestamp != null) tlv.AddUInt32(3, value.StartTimestamp.Value);
        if (value.EndTimestamp != null) tlv.AddUInt32(4, value.EndTimestamp.Value);
        if (value.MinTimestamp != null) tlv.AddUInt32(5, value.MinTimestamp.Value);
        if (value.MaxTimestamp != null) tlv.AddUInt32(6, value.MaxTimestamp.Value);
        if (value.StartSystime != null) tlv.AddUInt64(7, value.StartSystime.Value);
        if (value.EndSystime != null) tlv.AddUInt64(8, value.EndSystime.Value);
        if (value.MinSystime != null) tlv.AddUInt64(9, value.MinSystime.Value);
        if (value.MaxSystime != null) tlv.AddUInt64(10, value.MaxSystime.Value);
    }

    private static void WriteHarmonicMeasurementStruct(MatterTLV tlv, byte tag, HarmonicMeasurementStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteHarmonicMeasurementStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteHarmonicMeasurementStruct(MatterTLV tlv, HarmonicMeasurementStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteHarmonicMeasurementStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteHarmonicMeasurementStructFields(MatterTLV tlv, HarmonicMeasurementStruct value)
    {
        tlv.AddUInt8(0, value.Order);
        if (value.Measurement != null) { tlv.AddInt64(1, value.Measurement.Value); } else { tlv.AddNull(1); }
    }

    private static void WriteMeasurementAccuracyRangeStruct(MatterTLV tlv, byte tag, MeasurementAccuracyRangeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMeasurementAccuracyRangeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementAccuracyRangeStruct(MatterTLV tlv, MeasurementAccuracyRangeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMeasurementAccuracyRangeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementAccuracyRangeStructFields(MatterTLV tlv, MeasurementAccuracyRangeStruct value)
    {
        tlv.AddInt64(0, value.RangeMin);
        tlv.AddInt64(1, value.RangeMax);
        if (value.PercentMax != null) tlv.AddUInt16(2, value.PercentMax.Value);
        if (value.PercentMin != null) tlv.AddUInt16(3, value.PercentMin.Value);
        if (value.PercentTypical != null) tlv.AddUInt16(4, value.PercentTypical.Value);
        if (value.FixedMax != null) tlv.AddUInt64(5, value.FixedMax.Value);
        if (value.FixedMin != null) tlv.AddUInt64(6, value.FixedMin.Value);
        if (value.FixedTypical != null) tlv.AddUInt64(7, value.FixedTypical.Value);
    }

    private static void WriteMeasurementAccuracyStruct(MatterTLV tlv, byte tag, MeasurementAccuracyStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteMeasurementAccuracyStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementAccuracyStruct(MatterTLV tlv, MeasurementAccuracyStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteMeasurementAccuracyStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteMeasurementAccuracyStructFields(MatterTLV tlv, MeasurementAccuracyStruct value)
    {
        tlv.AddUInt16(0, (ushort)value.MeasurementType);
        tlv.AddBool(1, value.Measured);
        tlv.AddInt64(2, value.MinMeasuredValue);
        tlv.AddInt64(3, value.MaxMeasuredValue);
        if (value.AccuracyRanges != null) { tlv.AddArray(4); foreach (var item in value.AccuracyRanges) { WriteMeasurementAccuracyRangeStruct(tlv, item); } tlv.EndContainer(); }
    }

    // TLV struct deserializers

    private static MeasurementRangeStruct ReadMeasurementRangeStruct(MatterTLV tlv)
        => ReadMeasurementRangeStruct(tlv, null);

    private static MeasurementRangeStruct ReadMeasurementRangeStruct(MatterTLV tlv, int? tag)
    {
        var value = new MeasurementRangeStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.MeasurementType = (MeasurementTypeEnum)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.Min = tlv.GetSignedInt(1);
                    break;
                case 2:
                    value.Max = tlv.GetSignedInt(2);
                    break;
                case 3:
                    if (tlv.IsNextNull()) { tlv.GetNull(3); } else { value.StartTimestamp = tlv.GetUnsignedIntAny(3); }
                    break;
                case 4:
                    if (tlv.IsNextNull()) { tlv.GetNull(4); } else { value.EndTimestamp = tlv.GetUnsignedIntAny(4); }
                    break;
                case 5:
                    if (tlv.IsNextNull()) { tlv.GetNull(5); } else { value.MinTimestamp = tlv.GetUnsignedIntAny(5); }
                    break;
                case 6:
                    if (tlv.IsNextNull()) { tlv.GetNull(6); } else { value.MaxTimestamp = tlv.GetUnsignedIntAny(6); }
                    break;
                case 7:
                    if (tlv.IsNextNull()) { tlv.GetNull(7); } else { value.StartSystime = tlv.GetUnsignedInt(7); }
                    break;
                case 8:
                    if (tlv.IsNextNull()) { tlv.GetNull(8); } else { value.EndSystime = tlv.GetUnsignedInt(8); }
                    break;
                case 9:
                    if (tlv.IsNextNull()) { tlv.GetNull(9); } else { value.MinSystime = tlv.GetUnsignedInt(9); }
                    break;
                case 10:
                    if (tlv.IsNextNull()) { tlv.GetNull(10); } else { value.MaxSystime = tlv.GetUnsignedInt(10); }
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static HarmonicMeasurementStruct ReadHarmonicMeasurementStruct(MatterTLV tlv)
        => ReadHarmonicMeasurementStruct(tlv, null);

    private static HarmonicMeasurementStruct ReadHarmonicMeasurementStruct(MatterTLV tlv, int? tag)
    {
        var value = new HarmonicMeasurementStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.Order = (byte)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    if (tlv.IsNextNull()) { tlv.GetNull(1); } else { value.Measurement = tlv.GetSignedInt(1); }
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static MeasurementAccuracyRangeStruct ReadMeasurementAccuracyRangeStruct(MatterTLV tlv)
        => ReadMeasurementAccuracyRangeStruct(tlv, null);

    private static MeasurementAccuracyRangeStruct ReadMeasurementAccuracyRangeStruct(MatterTLV tlv, int? tag)
    {
        var value = new MeasurementAccuracyRangeStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.RangeMin = tlv.GetSignedInt(0);
                    break;
                case 1:
                    value.RangeMax = tlv.GetSignedInt(1);
                    break;
                case 2:
                    if (tlv.IsNextNull()) { tlv.GetNull(2); } else { value.PercentMax = (ushort)tlv.GetUnsignedIntAny(2); }
                    break;
                case 3:
                    if (tlv.IsNextNull()) { tlv.GetNull(3); } else { value.PercentMin = (ushort)tlv.GetUnsignedIntAny(3); }
                    break;
                case 4:
                    if (tlv.IsNextNull()) { tlv.GetNull(4); } else { value.PercentTypical = (ushort)tlv.GetUnsignedIntAny(4); }
                    break;
                case 5:
                    if (tlv.IsNextNull()) { tlv.GetNull(5); } else { value.FixedMax = tlv.GetUnsignedInt(5); }
                    break;
                case 6:
                    if (tlv.IsNextNull()) { tlv.GetNull(6); } else { value.FixedMin = tlv.GetUnsignedInt(6); }
                    break;
                case 7:
                    if (tlv.IsNextNull()) { tlv.GetNull(7); } else { value.FixedTypical = tlv.GetUnsignedInt(7); }
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static MeasurementAccuracyStruct ReadMeasurementAccuracyStruct(MatterTLV tlv)
        => ReadMeasurementAccuracyStruct(tlv, null);

    private static MeasurementAccuracyStruct ReadMeasurementAccuracyStruct(MatterTLV tlv, int? tag)
    {
        var value = new MeasurementAccuracyStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.MeasurementType = (MeasurementTypeEnum)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.Measured = tlv.GetBoolean(1);
                    break;
                case 2:
                    value.MinMeasuredValue = tlv.GetSignedInt(2);
                    break;
                case 3:
                    value.MaxMeasuredValue = tlv.GetSignedInt(3);
                    break;
                case 4:
                    var items4 = new List<MeasurementAccuracyRangeStruct>();
                    tlv.OpenArray(4);
                    while (!tlv.IsEndContainerNext())
                    {
                        items4.Add(ReadMeasurementAccuracyRangeStruct(tlv));
                    }
                    tlv.CloseContainer();
                    value.AccuracyRanges = [.. items4];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>PowerMode (0x0000).</summary>
        public const uint PowerMode = 0x0000;
        /// <summary>NumberOfMeasurementTypes (0x0001).</summary>
        public const uint NumberOfMeasurementTypes = 0x0001;
        /// <summary>Accuracy (0x0002).</summary>
        public const uint Accuracy = 0x0002;
        /// <summary>Ranges (0x0003).</summary>
        public const uint Ranges = 0x0003;
        /// <summary>Voltage (0x0004).</summary>
        public const uint Voltage = 0x0004;
        /// <summary>ActiveCurrent (0x0005).</summary>
        public const uint ActiveCurrent = 0x0005;
        /// <summary>ReactiveCurrent (0x0006).</summary>
        public const uint ReactiveCurrent = 0x0006;
        /// <summary>ApparentCurrent (0x0007).</summary>
        public const uint ApparentCurrent = 0x0007;
        /// <summary>ActivePower (0x0008).</summary>
        public const uint ActivePower = 0x0008;
        /// <summary>ReactivePower (0x0009).</summary>
        public const uint ReactivePower = 0x0009;
        /// <summary>ApparentPower (0x000A).</summary>
        public const uint ApparentPower = 0x000A;
        /// <summary>RMSVoltage (0x000B).</summary>
        public const uint RMSVoltage = 0x000B;
        /// <summary>RMSCurrent (0x000C).</summary>
        public const uint RMSCurrent = 0x000C;
        /// <summary>RMSPower (0x000D).</summary>
        public const uint RMSPower = 0x000D;
        /// <summary>Frequency (0x000E).</summary>
        public const uint Frequency = 0x000E;
        /// <summary>HarmonicCurrents (0x000F).</summary>
        public const uint HarmonicCurrents = 0x000F;
        /// <summary>HarmonicPhases (0x0010).</summary>
        public const uint HarmonicPhases = 0x0010;
        /// <summary>PowerFactor (0x0011).</summary>
        public const uint PowerFactor = 0x0011;
        /// <summary>NeutralCurrent (0x0012).</summary>
        public const uint NeutralCurrent = 0x0012;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>MeasurementPeriodRanges (0x0000).</summary>
        public const uint MeasurementPeriodRanges = 0x0000;
    }

    /// <summary>Base type for this cluster's event reports.</summary>
    public abstract class ClusterEvent
        : MatterClusterEvent
    {
        /// <summary>Initializes a new cluster event wrapper.</summary>
        protected ClusterEvent(MatterEventReport report, string eventName)
            : base(report, "Electrical Power Measurement", eventName) { }
    }

    /// <summary>Fallback event wrapper when DotMatter cannot parse a typed payload.</summary>
    public sealed class UnknownClusterEvent(MatterEventReport report, string? reason = null)
        : ClusterEvent(report, "Unknown")
    {
        /// <summary>Gets the reason the typed payload parser could not materialize this event.</summary>
        public override string? Reason { get; } = reason;
    }

    /// <summary>MeasurementPeriodRanges event payload.</summary>
    public sealed class MeasurementPeriodRangesEventData
    {
        /// <summary>Gets or sets Ranges.</summary>
        public MeasurementRangeStruct[] Ranges { get; set; } = default!;
    }

    /// <summary>MeasurementPeriodRanges event report.</summary>
    public sealed class MeasurementPeriodRangesEvent(MatterEventReport report, MeasurementPeriodRangesEventData payload)
        : ClusterEvent(report, "MeasurementPeriodRanges")
    {
        /// <summary>Gets the typed MeasurementPeriodRanges payload.</summary>
        public MeasurementPeriodRangesEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    // Attribute readers

    /// <summary>Read PowerMode attribute (0x0000).</summary>
    public Task<PowerModeEnum> ReadPowerModeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<PowerModeEnum>(0x0000, ct);

    /// <summary>Read NumberOfMeasurementTypes attribute (0x0001).</summary>
    public Task<byte> ReadNumberOfMeasurementTypesAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read Accuracy attribute (0x0002).</summary>
    public Task<MeasurementAccuracyStruct[]?> ReadAccuracyAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0002, ReadMeasurementAccuracyStruct, ct);

    /// <summary>Read Ranges attribute (0x0003).</summary>
    public Task<MeasurementRangeStruct[]?> ReadRangesAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0003, ReadMeasurementRangeStruct, ct);

    /// <summary>Read Voltage attribute (0x0004).</summary>
    public Task<ulong?> ReadVoltageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0004, ct);

    /// <summary>Read ActiveCurrent attribute (0x0005).</summary>
    public Task<ulong?> ReadActiveCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0005, ct);

    /// <summary>Read ReactiveCurrent attribute (0x0006).</summary>
    public Task<ulong?> ReadReactiveCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0006, ct);

    /// <summary>Read ApparentCurrent attribute (0x0007).</summary>
    public Task<ulong?> ReadApparentCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0007, ct);

    /// <summary>Read ActivePower attribute (0x0008).</summary>
    public Task<ulong?> ReadActivePowerAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0008, ct);

    /// <summary>Read ReactivePower attribute (0x0009).</summary>
    public Task<long?> ReadReactivePowerAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<long>(0x0009, ct);

    /// <summary>Read ApparentPower attribute (0x000A).</summary>
    public Task<long?> ReadApparentPowerAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<long>(0x000A, ct);

    /// <summary>Read RMSVoltage attribute (0x000B).</summary>
    public Task<ulong?> ReadRMSVoltageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000B, ct);

    /// <summary>Read RMSCurrent attribute (0x000C).</summary>
    public Task<ulong?> ReadRMSCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000C, ct);

    /// <summary>Read RMSPower attribute (0x000D).</summary>
    public Task<ulong?> ReadRMSPowerAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000D, ct);

    /// <summary>Read Frequency attribute (0x000E).</summary>
    public Task<long?> ReadFrequencyAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<long>(0x000E, ct);

    /// <summary>Read HarmonicCurrents attribute (0x000F).</summary>
    public Task<HarmonicMeasurementStruct[]?> ReadHarmonicCurrentsAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x000F, ReadHarmonicMeasurementStruct, ct);

    /// <summary>Read HarmonicPhases attribute (0x0010).</summary>
    public Task<HarmonicMeasurementStruct[]?> ReadHarmonicPhasesAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0010, ReadHarmonicMeasurementStruct, ct);

    /// <summary>Read PowerFactor attribute (0x0011).</summary>
    public Task<long?> ReadPowerFactorAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<long>(0x0011, ct);

    /// <summary>Read NeutralCurrent attribute (0x0012).</summary>
    public Task<ulong?> ReadNeutralCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x0012, ct);

    // Event payload parsers

    private static MeasurementPeriodRangesEventData ReadMeasurementPeriodRangesEventData(MatterTLV tlv)
    {
        var value = new MeasurementPeriodRangesEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    var items0 = new List<MeasurementRangeStruct>();
                    tlv.OpenArray(0);
                    while (!tlv.IsEndContainerNext())
                    {
                        items0.Add(ReadMeasurementRangeStruct(tlv));
                    }
                    tlv.CloseContainer();
                    value.Ranges = [.. items0];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadMeasurementPeriodRangesEventData(MatterEventReport report, out MeasurementPeriodRangesEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadMeasurementPeriodRangesEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "MeasurementPeriodRanges payload parse failed: " + ex.Message;
            return false;
        }
    }

    // Event payload JSON projectors

    private static JsonObject CreateMeasurementRangeStructJson(MeasurementRangeStruct value)
    {
        var json = new JsonObject();
        if (value.MeasurementType is { } measurementType)
        {
            json["measurementType"] = CreateJsonValue(measurementType.ToString());
        }
        json["min"] = CreateJsonValue(value.Min);
        json["max"] = CreateJsonValue(value.Max);
        if (value.StartTimestamp is { } startTimestamp)
        {
            json["startTimestamp"] = CreateJsonValue(startTimestamp);
        }
        if (value.EndTimestamp is { } endTimestamp)
        {
            json["endTimestamp"] = CreateJsonValue(endTimestamp);
        }
        if (value.MinTimestamp is { } minTimestamp)
        {
            json["minTimestamp"] = CreateJsonValue(minTimestamp);
        }
        if (value.MaxTimestamp is { } maxTimestamp)
        {
            json["maxTimestamp"] = CreateJsonValue(maxTimestamp);
        }
        if (value.StartSystime is { } startSystime)
        {
            json["startSystime"] = CreateJsonValue(startSystime);
        }
        if (value.EndSystime is { } endSystime)
        {
            json["endSystime"] = CreateJsonValue(endSystime);
        }
        if (value.MinSystime is { } minSystime)
        {
            json["minSystime"] = CreateJsonValue(minSystime);
        }
        if (value.MaxSystime is { } maxSystime)
        {
            json["maxSystime"] = CreateJsonValue(maxSystime);
        }
        return json;
    }

    private static JsonObject CreateHarmonicMeasurementStructJson(HarmonicMeasurementStruct value)
    {
        var json = new JsonObject();
        json["order"] = CreateJsonValue(value.Order);
        if (value.Measurement is { } measurement)
        {
            json["measurement"] = CreateJsonValue(measurement);
        }
        return json;
    }

    private static JsonObject CreateMeasurementAccuracyRangeStructJson(MeasurementAccuracyRangeStruct value)
    {
        var json = new JsonObject();
        json["rangeMin"] = CreateJsonValue(value.RangeMin);
        json["rangeMax"] = CreateJsonValue(value.RangeMax);
        if (value.PercentMax is { } percentMax)
        {
            json["percentMax"] = CreateJsonValue(percentMax);
        }
        if (value.PercentMin is { } percentMin)
        {
            json["percentMin"] = CreateJsonValue(percentMin);
        }
        if (value.PercentTypical is { } percentTypical)
        {
            json["percentTypical"] = CreateJsonValue(percentTypical);
        }
        if (value.FixedMax is { } fixedMax)
        {
            json["fixedMax"] = CreateJsonValue(fixedMax);
        }
        if (value.FixedMin is { } fixedMin)
        {
            json["fixedMin"] = CreateJsonValue(fixedMin);
        }
        if (value.FixedTypical is { } fixedTypical)
        {
            json["fixedTypical"] = CreateJsonValue(fixedTypical);
        }
        return json;
    }

    private static JsonObject CreateMeasurementAccuracyStructJson(MeasurementAccuracyStruct value)
    {
        var json = new JsonObject();
        if (value.MeasurementType is { } measurementType)
        {
            json["measurementType"] = CreateJsonValue(measurementType.ToString());
        }
        json["measured"] = CreateJsonValue(value.Measured);
        json["minMeasuredValue"] = CreateJsonValue(value.MinMeasuredValue);
        json["maxMeasuredValue"] = CreateJsonValue(value.MaxMeasuredValue);
        if (value.AccuracyRanges is { } accuracyRangesValues)
        {
            var accuracyRangesItems = new JsonArray();
            foreach (var item in accuracyRangesValues)
            {
                accuracyRangesItems.Add((JsonNode?)CreateMeasurementAccuracyRangeStructJson(item));
            }
            json["accuracyRanges"] = accuracyRangesItems;
        }
        return json;
    }

    private static JsonObject CreateMeasurementPeriodRangesEventDataJson(MeasurementPeriodRangesEventData value)
    {
        var json = new JsonObject();
        if (value.Ranges is { } rangesValues)
        {
            var rangesItems = new JsonArray();
            foreach (var item in rangesValues)
            {
                rangesItems.Add((JsonNode?)CreateMeasurementRangeStructJson(item));
            }
            json["ranges"] = rangesItems;
        }
        return json;
    }

    internal static JsonObject? MapEventPayloadJson(ClusterEvent evt)
    {
        return evt switch
        {
            MeasurementPeriodRangesEvent typed => CreateMeasurementPeriodRangesEventDataJson(typed.Payload),
            _ => null,
        };
    }

    // Event readers and subscriptions

    /// <summary>Read event reports from this cluster.</summary>
    public async Task<ClusterEvent[]> ReadEventsAsync(
        uint[]? eventIds = null,
        bool fabricFiltered = false,
        CancellationToken ct = default)
    {
        var events = await ReadEventsAsync(MapEventReports, eventIds, fabricFiltered, ct);
        return [.. events];
    }

    /// <summary>Subscribe to event reports from this cluster.</summary>
    public Task<MatterEventSubscription<ClusterEvent>> SubscribeEventsAsync(
        uint[]? eventIds = null,
        ushort minInterval = 1,
        ushort maxInterval = 60,
        bool fabricFiltered = false,
        CancellationToken ct = default)
        => SubscribeEventsAsync(MapEventReports, eventIds, minInterval, maxInterval, fabricFiltered, ct);

    internal static ClusterEvent[] MapEventReports(IReadOnlyList<MatterEventReport> reports)
    {
        if (reports.Count == 0)
        {
            return [];
        }

        var events = new List<ClusterEvent>(reports.Count);
        foreach (var report in reports)
        {
            events.Add(MapEventReport(report));
        }

        return [.. events];
    }

    internal static ClusterEvent MapEventReport(MatterEventReport report)
    {
        return report.EventId switch
        {
            Events.MeasurementPeriodRanges when TryReadMeasurementPeriodRangesEventData(report, out var measurementPeriodRangesEventData, out _) => new MeasurementPeriodRangesEvent(report, measurementPeriodRangesEventData!),
            Events.MeasurementPeriodRanges when TryReadMeasurementPeriodRangesEventData(report, out _, out var measurementPeriodRangesReason) => new UnknownClusterEvent(report, measurementPeriodRangesReason),
            _ => new UnknownClusterEvent(report, "Event ID is not recognized by this cluster."),
        };
    }
}
