// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: ethernet-network-diagnostics-cluster.xml
// Cluster: Ethernet Network Diagnostics (0x0037)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Ethernet Network Diagnostics (0x0037, rev 1)</summary>
public class EthernetNetworkDiagnosticsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0037;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="EthernetNetworkDiagnosticsCluster"/> bound to the given session and endpoint.</summary>
    public EthernetNetworkDiagnosticsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Node makes available the counts for the number of received and transmitted packets on the ethernet interface.</summary>
        PacketCounts = 1u << 0,
        /// <summary>Node makes available the counts for the number of errors that have occurred during the reception and transmission of packets on the ethernet interface.</summary>
        ErrorCounts = 1u << 1,
    }

    /// <summary>PHYRateEnum enum values.</summary>
    public enum PHYRateEnum : byte
    {
        /// <summary>Rate10M value.</summary>
        Rate10M = 0x00,
        /// <summary>Rate100M value.</summary>
        Rate100M = 0x01,
        /// <summary>Rate1G value.</summary>
        Rate1G = 0x02,
        /// <summary>Rate2_5G value.</summary>
        Rate25G = 0x03,
        /// <summary>Rate5G value.</summary>
        Rate5G = 0x04,
        /// <summary>Rate10G value.</summary>
        Rate10G = 0x05,
        /// <summary>Rate40G value.</summary>
        Rate40G = 0x06,
        /// <summary>Rate100G value.</summary>
        Rate100G = 0x07,
        /// <summary>Rate200G value.</summary>
        Rate200G = 0x08,
        /// <summary>Rate400G value.</summary>
        Rate400G = 0x09,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>PHYRate (0x0000).</summary>
        public const uint PHYRate = 0x0000;
        /// <summary>FullDuplex (0x0001).</summary>
        public const uint FullDuplex = 0x0001;
        /// <summary>PacketRxCount (0x0002).</summary>
        public const uint PacketRxCount = 0x0002;
        /// <summary>PacketTxCount (0x0003).</summary>
        public const uint PacketTxCount = 0x0003;
        /// <summary>TxErrCount (0x0004).</summary>
        public const uint TxErrCount = 0x0004;
        /// <summary>CollisionCount (0x0005).</summary>
        public const uint CollisionCount = 0x0005;
        /// <summary>OverrunCount (0x0006).</summary>
        public const uint OverrunCount = 0x0006;
        /// <summary>CarrierDetect (0x0007).</summary>
        public const uint CarrierDetect = 0x0007;
        /// <summary>TimeSinceReset (0x0008).</summary>
        public const uint TimeSinceReset = 0x0008;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>ResetCounts (0x0000).</summary>
        public const uint ResetCounts = 0x0000;
    }

    // Async command methods

    /// <summary>Send ResetCounts command (0x0000).</summary>
    public Task<InvokeResponse> ResetCountsAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    // Attribute readers

    /// <summary>Read PHYRate attribute (0x0000).</summary>
    public Task<PHYRateEnum> ReadPHYRateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<PHYRateEnum>(0x0000, ct);

    /// <summary>Read FullDuplex attribute (0x0001).</summary>
    public Task<bool?> ReadFullDuplexAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<bool>(0x0001, ct);

    /// <summary>Read PacketRxCount attribute (0x0002).</summary>
    public Task<ulong> ReadPacketRxCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0002, ct);

    /// <summary>Read PacketTxCount attribute (0x0003).</summary>
    public Task<ulong> ReadPacketTxCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0003, ct);

    /// <summary>Read TxErrCount attribute (0x0004).</summary>
    public Task<ulong> ReadTxErrCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0004, ct);

    /// <summary>Read CollisionCount attribute (0x0005).</summary>
    public Task<ulong> ReadCollisionCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0005, ct);

    /// <summary>Read OverrunCount attribute (0x0006).</summary>
    public Task<ulong> ReadOverrunCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0006, ct);

    /// <summary>Read CarrierDetect attribute (0x0007).</summary>
    public Task<bool?> ReadCarrierDetectAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<bool>(0x0007, ct);

    /// <summary>Read TimeSinceReset attribute (0x0008).</summary>
    public Task<ulong> ReadTimeSinceResetAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0008, ct);
}
