// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: general-diagnostics-cluster.xml
// Cluster: General Diagnostics (0x0033)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>General Diagnostics (0x0033, rev 2)</summary>
public class GeneralDiagnosticsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0033;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="GeneralDiagnosticsCluster"/> bound to the given session and endpoint.</summary>
    public GeneralDiagnosticsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Support specific testing needs for extended Data Model features</summary>
        DataModelTest = 1u << 0,
    }

    /// <summary>HardwareFaultEnum enum values.</summary>
    public enum HardwareFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>Radio value.</summary>
        Radio = 0x01,
        /// <summary>Sensor value.</summary>
        Sensor = 0x02,
        /// <summary>ResettableOverTemp value.</summary>
        ResettableOverTemp = 0x03,
        /// <summary>NonResettableOverTemp value.</summary>
        NonResettableOverTemp = 0x04,
        /// <summary>PowerSource value.</summary>
        PowerSource = 0x05,
        /// <summary>VisualDisplayFault value.</summary>
        VisualDisplayFault = 0x06,
        /// <summary>AudioOutputFault value.</summary>
        AudioOutputFault = 0x07,
        /// <summary>UserInterfaceFault value.</summary>
        UserInterfaceFault = 0x08,
        /// <summary>NonVolatileMemoryError value.</summary>
        NonVolatileMemoryError = 0x09,
        /// <summary>TamperDetected value.</summary>
        TamperDetected = 0x0A,
    }

    /// <summary>RadioFaultEnum enum values.</summary>
    public enum RadioFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>WiFiFault value.</summary>
        WiFiFault = 0x01,
        /// <summary>CellularFault value.</summary>
        CellularFault = 0x02,
        /// <summary>ThreadFault value.</summary>
        ThreadFault = 0x03,
        /// <summary>NFCFault value.</summary>
        NFCFault = 0x04,
        /// <summary>BLEFault value.</summary>
        BLEFault = 0x05,
        /// <summary>EthernetFault value.</summary>
        EthernetFault = 0x06,
    }

    /// <summary>NetworkFaultEnum enum values.</summary>
    public enum NetworkFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>HardwareFailure value.</summary>
        HardwareFailure = 0x01,
        /// <summary>NetworkJammed value.</summary>
        NetworkJammed = 0x02,
        /// <summary>ConnectionFailed value.</summary>
        ConnectionFailed = 0x03,
    }

    /// <summary>BootReasonEnum enum values.</summary>
    public enum BootReasonEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>PowerOnReboot value.</summary>
        PowerOnReboot = 0x01,
        /// <summary>BrownOutReset value.</summary>
        BrownOutReset = 0x02,
        /// <summary>SoftwareWatchdogReset value.</summary>
        SoftwareWatchdogReset = 0x03,
        /// <summary>HardwareWatchdogReset value.</summary>
        HardwareWatchdogReset = 0x04,
        /// <summary>SoftwareUpdateCompleted value.</summary>
        SoftwareUpdateCompleted = 0x05,
        /// <summary>SoftwareReset value.</summary>
        SoftwareReset = 0x06,
    }

    /// <summary>InterfaceTypeEnum enum values.</summary>
    public enum InterfaceTypeEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>WiFi value.</summary>
        WiFi = 0x01,
        /// <summary>Ethernet value.</summary>
        Ethernet = 0x02,
        /// <summary>Cellular value.</summary>
        Cellular = 0x03,
        /// <summary>Thread value.</summary>
        Thread = 0x04,
    }

    /// <summary>NetworkInterface struct.</summary>
    public sealed class NetworkInterface
    {
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
        /// <summary>Gets or sets IsOperational.</summary>
        public bool IsOperational { get; set; }
        /// <summary>Gets or sets OffPremiseServicesReachableIPv4.</summary>
        public bool? OffPremiseServicesReachableIPv4 { get; set; }
        /// <summary>Gets or sets OffPremiseServicesReachableIPv6.</summary>
        public bool? OffPremiseServicesReachableIPv6 { get; set; }
        /// <summary>Gets or sets HardwareAddress.</summary>
        public byte[] HardwareAddress { get; set; } = default!;
        /// <summary>Gets or sets IPv4Addresses.</summary>
        public byte[][] IPv4Addresses { get; set; } = default!;
        /// <summary>Gets or sets IPv6Addresses.</summary>
        public byte[][] IPv6Addresses { get; set; } = default!;
        /// <summary>Gets or sets Type.</summary>
        public InterfaceTypeEnum Type { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteNetworkInterface(MatterTLV tlv, byte tag, NetworkInterface value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteNetworkInterfaceFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteNetworkInterface(MatterTLV tlv, NetworkInterface value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteNetworkInterfaceFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteNetworkInterfaceFields(MatterTLV tlv, NetworkInterface value)
    {
        tlv.AddUTF8String(0, value.Name);
        tlv.AddBool(1, value.IsOperational);
        if (value.OffPremiseServicesReachableIPv4 != null) { tlv.AddBool(2, value.OffPremiseServicesReachableIPv4.Value); } else { tlv.AddNull(2); }
        if (value.OffPremiseServicesReachableIPv6 != null) { tlv.AddBool(3, value.OffPremiseServicesReachableIPv6.Value); } else { tlv.AddNull(3); }
        tlv.AddOctetString(4, value.HardwareAddress);
        if (value.IPv4Addresses != null) { tlv.AddArray(5); foreach (var item in value.IPv4Addresses) { tlv.AddOctetString(item); } tlv.EndContainer(); }
        if (value.IPv6Addresses != null) { tlv.AddArray(6); foreach (var item in value.IPv6Addresses) { tlv.AddOctetString(item); } tlv.EndContainer(); }
        tlv.AddUInt8(7, (byte)value.Type);
    }

    // TLV struct deserializers

    private static NetworkInterface ReadNetworkInterface(MatterTLV tlv)
    {
        var value = new NetworkInterface();
        tlv.OpenStructure();
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.Name = tlv.GetUTF8String(0);
                    break;
                case 1:
                    value.IsOperational = tlv.GetBoolean(1);
                    break;
                case 2:
                    if (tlv.IsNextNull()) { tlv.GetNull(2); } else { value.OffPremiseServicesReachableIPv4 = tlv.GetBoolean(2); }
                    break;
                case 3:
                    if (tlv.IsNextNull()) { tlv.GetNull(3); } else { value.OffPremiseServicesReachableIPv6 = tlv.GetBoolean(3); }
                    break;
                case 4:
                    value.HardwareAddress = tlv.GetOctetString(4);
                    break;
                case 5:
                    var items5 = new List<byte[]>();
                    tlv.OpenArray(5);
                    while (!tlv.IsEndContainerNext())
                    {
                        items5.Add((byte[])tlv.GetData(null)!);
                    }
                    tlv.CloseContainer();
                    value.IPv4Addresses = [.. items5];
                    break;
                case 6:
                    var items6 = new List<byte[]>();
                    tlv.OpenArray(6);
                    while (!tlv.IsEndContainerNext())
                    {
                        items6.Add((byte[])tlv.GetData(null)!);
                    }
                    tlv.CloseContainer();
                    value.IPv6Addresses = [.. items6];
                    break;
                case 7:
                    value.Type = (InterfaceTypeEnum)tlv.GetUnsignedIntAny(7);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>NetworkInterfaces (0x0000).</summary>
        public const uint NetworkInterfaces = 0x0000;
        /// <summary>RebootCount (0x0001).</summary>
        public const uint RebootCount = 0x0001;
        /// <summary>UpTime (0x0002).</summary>
        public const uint UpTime = 0x0002;
        /// <summary>TotalOperationalHours (0x0003).</summary>
        public const uint TotalOperationalHours = 0x0003;
        /// <summary>BootReason (0x0004).</summary>
        public const uint BootReason = 0x0004;
        /// <summary>ActiveHardwareFaults (0x0005).</summary>
        public const uint ActiveHardwareFaults = 0x0005;
        /// <summary>ActiveRadioFaults (0x0006).</summary>
        public const uint ActiveRadioFaults = 0x0006;
        /// <summary>ActiveNetworkFaults (0x0007).</summary>
        public const uint ActiveNetworkFaults = 0x0007;
        /// <summary>TestEventTriggersEnabled (0x0008).</summary>
        public const uint TestEventTriggersEnabled = 0x0008;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>TestEventTrigger (0x0000).</summary>
        public const uint TestEventTrigger = 0x0000;
        /// <summary>TimeSnapshot (0x0001).</summary>
        public const uint TimeSnapshot = 0x0001;
        /// <summary>PayloadTestRequest (0x0003).</summary>
        public const uint PayloadTestRequest = 0x0003;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>HardwareFaultChange (0x0000).</summary>
        public const uint HardwareFaultChange = 0x0000;
        /// <summary>RadioFaultChange (0x0001).</summary>
        public const uint RadioFaultChange = 0x0001;
        /// <summary>NetworkFaultChange (0x0002).</summary>
        public const uint NetworkFaultChange = 0x0002;
        /// <summary>BootReason (0x0003).</summary>
        public const uint BootReason = 0x0003;
    }

    /// <summary>Base type for this cluster's event reports.</summary>
    public abstract class ClusterEvent
        : MatterClusterEvent
    {
        /// <summary>Initializes a new cluster event wrapper.</summary>
        protected ClusterEvent(MatterEventReport report, string eventName)
            : base(report, "General Diagnostics", eventName) { }
    }

    /// <summary>Fallback event wrapper when DotMatter cannot parse a typed payload.</summary>
    public sealed class UnknownClusterEvent(MatterEventReport report, string? reason = null)
        : ClusterEvent(report, "Unknown")
    {
        /// <summary>Gets the reason the typed payload parser could not materialize this event.</summary>
        public override string? Reason { get; } = reason;
    }

    /// <summary>HardwareFaultChange event payload.</summary>
    public sealed class HardwareFaultChangeEventData
    {
        /// <summary>Gets or sets Current.</summary>
        public HardwareFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets Previous.</summary>
        public HardwareFaultEnum[] Previous { get; set; } = default!;
    }

    /// <summary>HardwareFaultChange event report.</summary>
    public sealed class HardwareFaultChangeEvent(MatterEventReport report, HardwareFaultChangeEventData payload)
        : ClusterEvent(report, "HardwareFaultChange")
    {
        /// <summary>Gets the typed HardwareFaultChange payload.</summary>
        public HardwareFaultChangeEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>RadioFaultChange event payload.</summary>
    public sealed class RadioFaultChangeEventData
    {
        /// <summary>Gets or sets Current.</summary>
        public RadioFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets Previous.</summary>
        public RadioFaultEnum[] Previous { get; set; } = default!;
    }

    /// <summary>RadioFaultChange event report.</summary>
    public sealed class RadioFaultChangeEvent(MatterEventReport report, RadioFaultChangeEventData payload)
        : ClusterEvent(report, "RadioFaultChange")
    {
        /// <summary>Gets the typed RadioFaultChange payload.</summary>
        public RadioFaultChangeEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>NetworkFaultChange event payload.</summary>
    public sealed class NetworkFaultChangeEventData
    {
        /// <summary>Gets or sets Current.</summary>
        public NetworkFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets Previous.</summary>
        public NetworkFaultEnum[] Previous { get; set; } = default!;
    }

    /// <summary>NetworkFaultChange event report.</summary>
    public sealed class NetworkFaultChangeEvent(MatterEventReport report, NetworkFaultChangeEventData payload)
        : ClusterEvent(report, "NetworkFaultChange")
    {
        /// <summary>Gets the typed NetworkFaultChange payload.</summary>
        public NetworkFaultChangeEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>BootReason event payload.</summary>
    public sealed class BootReasonEventData
    {
        /// <summary>Gets or sets BootReason.</summary>
        public BootReasonEnum BootReason { get; set; } = default!;
    }

    /// <summary>BootReason event report.</summary>
    public sealed class BootReasonEvent(MatterEventReport report, BootReasonEventData payload)
        : ClusterEvent(report, "BootReason")
    {
        /// <summary>Gets the typed BootReason payload.</summary>
        public BootReasonEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    // Async command methods

    /// <summary>Send TestEventTrigger command (0x0000).</summary>
    public Task<InvokeResponse> TestEventTriggerAsync(
        byte[] enableKey,
        ulong eventTrigger,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddOctetString(0, enableKey);
            tlv.AddUInt64(1, eventTrigger);
        }, ct);

    /// <summary>Send TimeSnapshot command (0x0001).</summary>
    public Task<InvokeResponse> TimeSnapshotAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, ct: ct);

    /// <summary>Send PayloadTestRequest command (0x0003).</summary>
    public Task<InvokeResponse> PayloadTestRequestAsync(
        byte[] enableKey,
        byte value,
        ushort count,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv =>
        {
            tlv.AddOctetString(0, enableKey);
            tlv.AddUInt8(1, value);
            tlv.AddUInt16(2, count);
        }, ct);

    // Attribute readers

    /// <summary>Read NetworkInterfaces attribute (0x0000).</summary>
    public Task<NetworkInterface[]?> ReadNetworkInterfacesAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<NetworkInterface[]>(0x0000, ct);

    /// <summary>Read RebootCount attribute (0x0001).</summary>
    public Task<ushort> ReadRebootCountAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0001, ct);

    /// <summary>Read UpTime attribute (0x0002).</summary>
    public Task<ulong> ReadUpTimeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0002, ct);

    /// <summary>Read TotalOperationalHours attribute (0x0003).</summary>
    public Task<uint> ReadTotalOperationalHoursAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0003, ct);

    /// <summary>Read BootReason attribute (0x0004).</summary>
    public Task<BootReasonEnum> ReadBootReasonAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BootReasonEnum>(0x0004, ct);

    /// <summary>Read ActiveHardwareFaults attribute (0x0005).</summary>
    public Task<HardwareFaultEnum[]?> ReadActiveHardwareFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<HardwareFaultEnum[]>(0x0005, ct);

    /// <summary>Read ActiveRadioFaults attribute (0x0006).</summary>
    public Task<RadioFaultEnum[]?> ReadActiveRadioFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<RadioFaultEnum[]>(0x0006, ct);

    /// <summary>Read ActiveNetworkFaults attribute (0x0007).</summary>
    public Task<NetworkFaultEnum[]?> ReadActiveNetworkFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<NetworkFaultEnum[]>(0x0007, ct);

    /// <summary>Read TestEventTriggersEnabled attribute (0x0008).</summary>
    public Task<bool> ReadTestEventTriggersEnabledAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0008, ct);

    // Event payload parsers

    private static HardwareFaultChangeEventData ReadHardwareFaultChangeEventData(MatterTLV tlv)
    {
        var value = new HardwareFaultChangeEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    var items0 = new List<HardwareFaultEnum>();
                    tlv.OpenArray(0);
                    while (!tlv.IsEndContainerNext())
                    {
                        items0.Add((HardwareFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Current = [.. items0];
                    break;
                case 1:
                    var items1 = new List<HardwareFaultEnum>();
                    tlv.OpenArray(1);
                    while (!tlv.IsEndContainerNext())
                    {
                        items1.Add((HardwareFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Previous = [.. items1];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadHardwareFaultChangeEventData(MatterEventReport report, out HardwareFaultChangeEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadHardwareFaultChangeEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "HardwareFaultChange payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static RadioFaultChangeEventData ReadRadioFaultChangeEventData(MatterTLV tlv)
    {
        var value = new RadioFaultChangeEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    var items0 = new List<RadioFaultEnum>();
                    tlv.OpenArray(0);
                    while (!tlv.IsEndContainerNext())
                    {
                        items0.Add((RadioFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Current = [.. items0];
                    break;
                case 1:
                    var items1 = new List<RadioFaultEnum>();
                    tlv.OpenArray(1);
                    while (!tlv.IsEndContainerNext())
                    {
                        items1.Add((RadioFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Previous = [.. items1];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadRadioFaultChangeEventData(MatterEventReport report, out RadioFaultChangeEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadRadioFaultChangeEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "RadioFaultChange payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static NetworkFaultChangeEventData ReadNetworkFaultChangeEventData(MatterTLV tlv)
    {
        var value = new NetworkFaultChangeEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    var items0 = new List<NetworkFaultEnum>();
                    tlv.OpenArray(0);
                    while (!tlv.IsEndContainerNext())
                    {
                        items0.Add((NetworkFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Current = [.. items0];
                    break;
                case 1:
                    var items1 = new List<NetworkFaultEnum>();
                    tlv.OpenArray(1);
                    while (!tlv.IsEndContainerNext())
                    {
                        items1.Add((NetworkFaultEnum)tlv.GetUnsignedInt(null));
                    }
                    tlv.CloseContainer();
                    value.Previous = [.. items1];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadNetworkFaultChangeEventData(MatterEventReport report, out NetworkFaultChangeEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadNetworkFaultChangeEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "NetworkFaultChange payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static BootReasonEventData ReadBootReasonEventData(MatterTLV tlv)
    {
        var value = new BootReasonEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.BootReason = (BootReasonEnum)tlv.GetUnsignedIntAny(0);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadBootReasonEventData(MatterEventReport report, out BootReasonEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadBootReasonEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "BootReason payload parse failed: " + ex.Message;
            return false;
        }
    }

    // Event payload JSON projectors

    private static JsonObject CreateNetworkInterfaceJson(NetworkInterface value)
    {
        var json = new JsonObject();
        if (value.Name is { } name)
        {
            json["name"] = CreateJsonValue(name);
        }
        json["isOperational"] = CreateJsonValue(value.IsOperational);
        if (value.OffPremiseServicesReachableIPv4 is { } offPremiseServicesReachableIPv4)
        {
            json["offPremiseServicesReachableIPv4"] = CreateJsonValue(offPremiseServicesReachableIPv4);
        }
        if (value.OffPremiseServicesReachableIPv6 is { } offPremiseServicesReachableIPv6)
        {
            json["offPremiseServicesReachableIPv6"] = CreateJsonValue(offPremiseServicesReachableIPv6);
        }
        if (value.HardwareAddress is { } hardwareAddress)
        {
            json["hardwareAddress"] = CreateJsonValue(hardwareAddress);
        }
        if (value.IPv4Addresses is { } iPv4AddressesValues)
        {
            var iPv4AddressesItems = new JsonArray();
            foreach (var item in iPv4AddressesValues)
            {
                iPv4AddressesItems.Add((JsonNode?)CreateJsonValue(item));
            }
            json["iPv4Addresses"] = iPv4AddressesItems;
        }
        if (value.IPv6Addresses is { } iPv6AddressesValues)
        {
            var iPv6AddressesItems = new JsonArray();
            foreach (var item in iPv6AddressesValues)
            {
                iPv6AddressesItems.Add((JsonNode?)CreateJsonValue(item));
            }
            json["iPv6Addresses"] = iPv6AddressesItems;
        }
        if (value.Type is { } type)
        {
            json["type"] = CreateJsonValue(type.ToString());
        }
        return json;
    }

    private static JsonObject CreateHardwareFaultChangeEventDataJson(HardwareFaultChangeEventData value)
    {
        var json = new JsonObject();
        if (value.Current is { } currentValues)
        {
            var currentItems = new JsonArray();
            foreach (var item in currentValues)
            {
                currentItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["current"] = currentItems;
        }
        if (value.Previous is { } previousValues)
        {
            var previousItems = new JsonArray();
            foreach (var item in previousValues)
            {
                previousItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["previous"] = previousItems;
        }
        return json;
    }

    private static JsonObject CreateRadioFaultChangeEventDataJson(RadioFaultChangeEventData value)
    {
        var json = new JsonObject();
        if (value.Current is { } currentValues)
        {
            var currentItems = new JsonArray();
            foreach (var item in currentValues)
            {
                currentItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["current"] = currentItems;
        }
        if (value.Previous is { } previousValues)
        {
            var previousItems = new JsonArray();
            foreach (var item in previousValues)
            {
                previousItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["previous"] = previousItems;
        }
        return json;
    }

    private static JsonObject CreateNetworkFaultChangeEventDataJson(NetworkFaultChangeEventData value)
    {
        var json = new JsonObject();
        if (value.Current is { } currentValues)
        {
            var currentItems = new JsonArray();
            foreach (var item in currentValues)
            {
                currentItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["current"] = currentItems;
        }
        if (value.Previous is { } previousValues)
        {
            var previousItems = new JsonArray();
            foreach (var item in previousValues)
            {
                previousItems.Add((JsonNode?)CreateJsonValue(item.ToString()));
            }
            json["previous"] = previousItems;
        }
        return json;
    }

    private static JsonObject CreateBootReasonEventDataJson(BootReasonEventData value)
    {
        var json = new JsonObject();
        if (value.BootReason is { } bootReason)
        {
            json["bootReason"] = CreateJsonValue(bootReason.ToString());
        }
        return json;
    }

    internal static JsonObject? MapEventPayloadJson(ClusterEvent evt)
    {
        return evt switch
        {
            HardwareFaultChangeEvent typed => CreateHardwareFaultChangeEventDataJson(typed.Payload),
            RadioFaultChangeEvent typed => CreateRadioFaultChangeEventDataJson(typed.Payload),
            NetworkFaultChangeEvent typed => CreateNetworkFaultChangeEventDataJson(typed.Payload),
            BootReasonEvent typed => CreateBootReasonEventDataJson(typed.Payload),
            _ => null,
        };
    }

    // Event readers and subscriptions

    /// <summary>Read event reports from this cluster.</summary>
    public async Task<ClusterEvent[]> ReadEventsAsync(
        uint[]? eventIds = null,
        bool fabricFiltered = false,
        CancellationToken ct = default)
    {
        var events = await ReadEventsAsync(MapEventReports, eventIds, fabricFiltered, ct);
        return [.. events];
    }

    /// <summary>Subscribe to event reports from this cluster.</summary>
    public Task<MatterEventSubscription<ClusterEvent>> SubscribeEventsAsync(
        uint[]? eventIds = null,
        ushort minInterval = 1,
        ushort maxInterval = 60,
        bool fabricFiltered = false,
        CancellationToken ct = default)
        => SubscribeEventsAsync(MapEventReports, eventIds, minInterval, maxInterval, fabricFiltered, ct);

    internal static ClusterEvent[] MapEventReports(IReadOnlyList<MatterEventReport> reports)
    {
        if (reports.Count == 0)
        {
            return [];
        }

        var events = new List<ClusterEvent>(reports.Count);
        foreach (var report in reports)
        {
            events.Add(MapEventReport(report));
        }

        return [.. events];
    }

    internal static ClusterEvent MapEventReport(MatterEventReport report)
    {
        return report.EventId switch
        {
            Events.HardwareFaultChange when TryReadHardwareFaultChangeEventData(report, out var hardwareFaultChangeEventData, out _) => new HardwareFaultChangeEvent(report, hardwareFaultChangeEventData!),
            Events.HardwareFaultChange when TryReadHardwareFaultChangeEventData(report, out _, out var hardwareFaultChangeReason) => new UnknownClusterEvent(report, hardwareFaultChangeReason),
            Events.RadioFaultChange when TryReadRadioFaultChangeEventData(report, out var radioFaultChangeEventData, out _) => new RadioFaultChangeEvent(report, radioFaultChangeEventData!),
            Events.RadioFaultChange when TryReadRadioFaultChangeEventData(report, out _, out var radioFaultChangeReason) => new UnknownClusterEvent(report, radioFaultChangeReason),
            Events.NetworkFaultChange when TryReadNetworkFaultChangeEventData(report, out var networkFaultChangeEventData, out _) => new NetworkFaultChangeEvent(report, networkFaultChangeEventData!),
            Events.NetworkFaultChange when TryReadNetworkFaultChangeEventData(report, out _, out var networkFaultChangeReason) => new UnknownClusterEvent(report, networkFaultChangeReason),
            Events.BootReason when TryReadBootReasonEventData(report, out var bootReasonEventData, out _) => new BootReasonEvent(report, bootReasonEventData!),
            Events.BootReason when TryReadBootReasonEventData(report, out _, out var bootReasonReason) => new UnknownClusterEvent(report, bootReasonReason),
            _ => new UnknownClusterEvent(report, "Event ID is not recognized by this cluster."),
        };
    }
}
