// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: joint-fabric-datastore-cluster.xml
// Cluster: Joint Fabric Datastore (0x0752)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Joint Fabric Datastore (0x0752, rev 1)</summary>
public class JointFabricDatastoreCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0752;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="JointFabricDatastoreCluster"/> bound to the given session and endpoint.</summary>
    public JointFabricDatastoreCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>DatastoreAccessControlEntryAuthModeEnum enum values.</summary>
    public enum DatastoreAccessControlEntryAuthModeEnum : byte
    {
        /// <summary>PASE value.</summary>
        PASE = 0x01,
        /// <summary>CASE value.</summary>
        CASE = 0x02,
        /// <summary>Group value.</summary>
        Group = 0x03,
    }

    /// <summary>DatastoreAccessControlEntryPrivilegeEnum enum values.</summary>
    public enum DatastoreAccessControlEntryPrivilegeEnum : byte
    {
        /// <summary>View value.</summary>
        View = 0x01,
        /// <summary>ProxyView value.</summary>
        ProxyView = 0x02,
        /// <summary>Operate value.</summary>
        Operate = 0x03,
        /// <summary>Manage value.</summary>
        Manage = 0x04,
        /// <summary>Administer value.</summary>
        Administer = 0x05,
    }

    /// <summary>DatastoreGroupKeyMulticastPolicyEnum enum values.</summary>
    public enum DatastoreGroupKeyMulticastPolicyEnum : byte
    {
        /// <summary>PerGroupID value.</summary>
        PerGroupID = 0x00,
        /// <summary>AllNodes value.</summary>
        AllNodes = 0x01,
    }

    /// <summary>DatastoreGroupKeySecurityPolicyEnum enum values.</summary>
    public enum DatastoreGroupKeySecurityPolicyEnum : byte
    {
        /// <summary>TrustFirst value.</summary>
        TrustFirst = 0x00,
    }

    /// <summary>DatastoreStateEnum enum values.</summary>
    public enum DatastoreStateEnum : byte
    {
        /// <summary>Pending value.</summary>
        Pending = 0x00,
        /// <summary>Committed value.</summary>
        Committed = 0x01,
        /// <summary>DeletePending value.</summary>
        DeletePending = 0x02,
        /// <summary>CommitFailed value.</summary>
        CommitFailed = 0x03,
    }

    /// <summary>DatastoreACLEntryStruct struct.</summary>
    public sealed class DatastoreACLEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets ListID.</summary>
        public ushort ListID { get; set; }
        /// <summary>Gets or sets ACLEntry.</summary>
        public DatastoreAccessControlEntryStruct ACLEntry { get; set; } = default!;
        /// <summary>Gets or sets StatusEntry.</summary>
        public DatastoreStatusEntryStruct StatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreAccessControlEntryStruct struct.</summary>
    public sealed class DatastoreAccessControlEntryStruct
    {
        /// <summary>Gets or sets Privilege.</summary>
        public DatastoreAccessControlEntryPrivilegeEnum Privilege { get; set; } = default!;
        /// <summary>Gets or sets AuthMode.</summary>
        public DatastoreAccessControlEntryAuthModeEnum AuthMode { get; set; } = default!;
        /// <summary>Gets or sets Subjects.</summary>
        public ulong[]? Subjects { get; set; }
        /// <summary>Gets or sets Targets.</summary>
        public DatastoreAccessControlTargetStruct[]? Targets { get; set; }
    }

    /// <summary>DatastoreAccessControlTargetStruct struct.</summary>
    public sealed class DatastoreAccessControlTargetStruct
    {
        /// <summary>Gets or sets Cluster.</summary>
        public uint? Cluster { get; set; }
        /// <summary>Gets or sets Endpoint.</summary>
        public ushort? Endpoint { get; set; }
        /// <summary>Gets or sets DeviceType.</summary>
        public uint? DeviceType { get; set; }
    }

    /// <summary>DatastoreAdministratorInformationEntryStruct struct.</summary>
    public sealed class DatastoreAdministratorInformationEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets FriendlyName.</summary>
        public string FriendlyName { get; set; } = default!;
        /// <summary>Gets or sets VendorID.</summary>
        public ushort VendorID { get; set; }
        /// <summary>Gets or sets ICAC.</summary>
        public byte[] ICAC { get; set; } = default!;
    }

    /// <summary>DatastoreBindingTargetStruct struct.</summary>
    public sealed class DatastoreBindingTargetStruct
    {
        /// <summary>Gets or sets Node.</summary>
        public ulong? Node { get; set; }
        /// <summary>Gets or sets Group.</summary>
        public ushort? Group { get; set; }
        /// <summary>Gets or sets Endpoint.</summary>
        public ushort? Endpoint { get; set; }
        /// <summary>Gets or sets Cluster.</summary>
        public uint? Cluster { get; set; }
    }

    /// <summary>DatastoreEndpointBindingEntryStruct struct.</summary>
    public sealed class DatastoreEndpointBindingEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets EndpointID.</summary>
        public ushort EndpointID { get; set; }
        /// <summary>Gets or sets ListID.</summary>
        public ushort ListID { get; set; }
        /// <summary>Gets or sets Binding.</summary>
        public DatastoreBindingTargetStruct Binding { get; set; } = default!;
        /// <summary>Gets or sets StatusEntry.</summary>
        public DatastoreStatusEntryStruct StatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreEndpointEntryStruct struct.</summary>
    public sealed class DatastoreEndpointEntryStruct
    {
        /// <summary>Gets or sets EndpointID.</summary>
        public ushort EndpointID { get; set; }
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets FriendlyName.</summary>
        public string FriendlyName { get; set; } = default!;
        /// <summary>Gets or sets StatusEntry.</summary>
        public DatastoreStatusEntryStruct StatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreEndpointGroupIDEntryStruct struct.</summary>
    public sealed class DatastoreEndpointGroupIDEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets EndpointID.</summary>
        public ushort EndpointID { get; set; }
        /// <summary>Gets or sets GroupID.</summary>
        public ushort GroupID { get; set; }
        /// <summary>Gets or sets StatusEntry.</summary>
        public DatastoreStatusEntryStruct StatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreGroupInformationEntryStruct struct.</summary>
    public sealed class DatastoreGroupInformationEntryStruct
    {
        /// <summary>Gets or sets GroupID.</summary>
        public ulong GroupID { get; set; }
        /// <summary>Gets or sets FriendlyName.</summary>
        public string FriendlyName { get; set; } = default!;
        /// <summary>Gets or sets GroupKeySetID.</summary>
        public ushort? GroupKeySetID { get; set; }
        /// <summary>Gets or sets GroupCAT.</summary>
        public ushort? GroupCAT { get; set; }
        /// <summary>Gets or sets GroupCATVersion.</summary>
        public ushort? GroupCATVersion { get; set; }
        /// <summary>Gets or sets GroupPermission.</summary>
        public DatastoreAccessControlEntryPrivilegeEnum GroupPermission { get; set; } = default!;
    }

    /// <summary>DatastoreGroupKeySetStruct struct.</summary>
    public sealed class DatastoreGroupKeySetStruct
    {
        /// <summary>Gets or sets GroupKeySetID.</summary>
        public ushort GroupKeySetID { get; set; }
        /// <summary>Gets or sets GroupKeySecurityPolicy.</summary>
        public DatastoreGroupKeySecurityPolicyEnum GroupKeySecurityPolicy { get; set; } = default!;
        /// <summary>Gets or sets EpochKey0.</summary>
        public byte[] EpochKey0 { get; set; } = default!;
        /// <summary>Gets or sets EpochStartTime0.</summary>
        public ulong? EpochStartTime0 { get; set; }
        /// <summary>Gets or sets EpochKey1.</summary>
        public byte[] EpochKey1 { get; set; } = default!;
        /// <summary>Gets or sets EpochStartTime1.</summary>
        public ulong? EpochStartTime1 { get; set; }
        /// <summary>Gets or sets EpochKey2.</summary>
        public byte[] EpochKey2 { get; set; } = default!;
        /// <summary>Gets or sets EpochStartTime2.</summary>
        public ulong? EpochStartTime2 { get; set; }
        /// <summary>Gets or sets GroupKeyMulticastPolicy.</summary>
        public DatastoreGroupKeyMulticastPolicyEnum GroupKeyMulticastPolicy { get; set; } = default!;
    }

    /// <summary>DatastoreNodeInformationEntryStruct struct.</summary>
    public sealed class DatastoreNodeInformationEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets FriendlyName.</summary>
        public string FriendlyName { get; set; } = default!;
        /// <summary>Gets or sets CommissioningStatusEntry.</summary>
        public DatastoreStatusEntryStruct CommissioningStatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreNodeKeySetEntryStruct struct.</summary>
    public sealed class DatastoreNodeKeySetEntryStruct
    {
        /// <summary>Gets or sets NodeID.</summary>
        public ulong NodeID { get; set; }
        /// <summary>Gets or sets GroupKeySetID.</summary>
        public ushort GroupKeySetID { get; set; }
        /// <summary>Gets or sets StatusEntry.</summary>
        public DatastoreStatusEntryStruct StatusEntry { get; set; } = default!;
    }

    /// <summary>DatastoreStatusEntryStruct struct.</summary>
    public sealed class DatastoreStatusEntryStruct
    {
        /// <summary>Gets or sets State.</summary>
        public DatastoreStateEnum State { get; set; } = default!;
        /// <summary>Gets or sets UpdateTimestamp.</summary>
        public uint UpdateTimestamp { get; set; }
        /// <summary>Gets or sets FailureCode.</summary>
        public byte FailureCode { get; set; }
    }

    // TLV struct serializers

    private static void WriteDatastoreACLEntryStruct(MatterTLV tlv, byte tag, DatastoreACLEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreACLEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreACLEntryStruct(MatterTLV tlv, DatastoreACLEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreACLEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreACLEntryStructFields(MatterTLV tlv, DatastoreACLEntryStruct value)
    {
        tlv.AddUInt64(0, value.NodeID);
        tlv.AddUInt16(1, value.ListID);
        WriteDatastoreAccessControlEntryStruct(tlv, 2, value.ACLEntry);
        WriteDatastoreStatusEntryStruct(tlv, 3, value.StatusEntry);
    }

    private static void WriteDatastoreAccessControlEntryStruct(MatterTLV tlv, byte tag, DatastoreAccessControlEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreAccessControlEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAccessControlEntryStruct(MatterTLV tlv, DatastoreAccessControlEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreAccessControlEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAccessControlEntryStructFields(MatterTLV tlv, DatastoreAccessControlEntryStruct value)
    {
        tlv.AddUInt8(1, (byte)value.Privilege);
        tlv.AddUInt8(2, (byte)value.AuthMode);
        if (value.Subjects != null) { tlv.AddArray(3); foreach (var item in value.Subjects) { tlv.AddUInt64(item); } tlv.EndContainer(); } else { tlv.AddNull(3); }
        if (value.Targets != null) { tlv.AddArray(4); foreach (var item in value.Targets) { WriteDatastoreAccessControlTargetStruct(tlv, item); } tlv.EndContainer(); } else { tlv.AddNull(4); }
    }

    private static void WriteDatastoreAccessControlTargetStruct(MatterTLV tlv, byte tag, DatastoreAccessControlTargetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreAccessControlTargetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAccessControlTargetStruct(MatterTLV tlv, DatastoreAccessControlTargetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreAccessControlTargetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAccessControlTargetStructFields(MatterTLV tlv, DatastoreAccessControlTargetStruct value)
    {
        if (value.Cluster != null) { tlv.AddUInt32(0, value.Cluster.Value); } else { tlv.AddNull(0); }
        if (value.Endpoint != null) { tlv.AddUInt16(1, value.Endpoint.Value); } else { tlv.AddNull(1); }
        if (value.DeviceType != null) { tlv.AddUInt32(2, value.DeviceType.Value); } else { tlv.AddNull(2); }
    }

    private static void WriteDatastoreAdministratorInformationEntryStruct(MatterTLV tlv, byte tag, DatastoreAdministratorInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreAdministratorInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAdministratorInformationEntryStruct(MatterTLV tlv, DatastoreAdministratorInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreAdministratorInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreAdministratorInformationEntryStructFields(MatterTLV tlv, DatastoreAdministratorInformationEntryStruct value)
    {
        tlv.AddUInt64(1, value.NodeID);
        tlv.AddUTF8String(2, value.FriendlyName);
        tlv.AddUInt16(3, value.VendorID);
        tlv.AddOctetString(4, value.ICAC);
    }

    private static void WriteDatastoreBindingTargetStruct(MatterTLV tlv, byte tag, DatastoreBindingTargetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreBindingTargetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreBindingTargetStruct(MatterTLV tlv, DatastoreBindingTargetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreBindingTargetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreBindingTargetStructFields(MatterTLV tlv, DatastoreBindingTargetStruct value)
    {
        if (value.Node != null) tlv.AddUInt64(1, value.Node.Value);
        if (value.Group != null) tlv.AddUInt16(2, value.Group.Value);
        if (value.Endpoint != null) tlv.AddUInt16(3, value.Endpoint.Value);
        if (value.Cluster != null) tlv.AddUInt32(4, value.Cluster.Value);
    }

    private static void WriteDatastoreEndpointBindingEntryStruct(MatterTLV tlv, byte tag, DatastoreEndpointBindingEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreEndpointBindingEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointBindingEntryStruct(MatterTLV tlv, DatastoreEndpointBindingEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreEndpointBindingEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointBindingEntryStructFields(MatterTLV tlv, DatastoreEndpointBindingEntryStruct value)
    {
        tlv.AddUInt64(0, value.NodeID);
        tlv.AddUInt16(1, value.EndpointID);
        tlv.AddUInt16(2, value.ListID);
        WriteDatastoreBindingTargetStruct(tlv, 3, value.Binding);
        WriteDatastoreStatusEntryStruct(tlv, 4, value.StatusEntry);
    }

    private static void WriteDatastoreEndpointEntryStruct(MatterTLV tlv, byte tag, DatastoreEndpointEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreEndpointEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointEntryStruct(MatterTLV tlv, DatastoreEndpointEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreEndpointEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointEntryStructFields(MatterTLV tlv, DatastoreEndpointEntryStruct value)
    {
        tlv.AddUInt16(0, value.EndpointID);
        tlv.AddUInt64(1, value.NodeID);
        tlv.AddUTF8String(2, value.FriendlyName);
        WriteDatastoreStatusEntryStruct(tlv, 3, value.StatusEntry);
    }

    private static void WriteDatastoreEndpointGroupIDEntryStruct(MatterTLV tlv, byte tag, DatastoreEndpointGroupIDEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreEndpointGroupIDEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointGroupIDEntryStruct(MatterTLV tlv, DatastoreEndpointGroupIDEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreEndpointGroupIDEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreEndpointGroupIDEntryStructFields(MatterTLV tlv, DatastoreEndpointGroupIDEntryStruct value)
    {
        tlv.AddUInt64(0, value.NodeID);
        tlv.AddUInt16(1, value.EndpointID);
        tlv.AddUInt16(2, value.GroupID);
        WriteDatastoreStatusEntryStruct(tlv, 3, value.StatusEntry);
    }

    private static void WriteDatastoreGroupInformationEntryStruct(MatterTLV tlv, byte tag, DatastoreGroupInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreGroupInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreGroupInformationEntryStruct(MatterTLV tlv, DatastoreGroupInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreGroupInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreGroupInformationEntryStructFields(MatterTLV tlv, DatastoreGroupInformationEntryStruct value)
    {
        tlv.AddUInt64(0, value.GroupID);
        tlv.AddUTF8String(1, value.FriendlyName);
        if (value.GroupKeySetID != null) { tlv.AddUInt16(2, value.GroupKeySetID.Value); } else { tlv.AddNull(2); }
        if (value.GroupCAT != null) { tlv.AddUInt16(3, value.GroupCAT.Value); } else { tlv.AddNull(3); }
        if (value.GroupCATVersion != null) { tlv.AddUInt16(4, value.GroupCATVersion.Value); } else { tlv.AddNull(4); }
        tlv.AddUInt8(5, (byte)value.GroupPermission);
    }

    private static void WriteDatastoreGroupKeySetStruct(MatterTLV tlv, byte tag, DatastoreGroupKeySetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreGroupKeySetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreGroupKeySetStruct(MatterTLV tlv, DatastoreGroupKeySetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreGroupKeySetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreGroupKeySetStructFields(MatterTLV tlv, DatastoreGroupKeySetStruct value)
    {
        tlv.AddUInt16(0, value.GroupKeySetID);
        tlv.AddUInt8(1, (byte)value.GroupKeySecurityPolicy);
        tlv.AddOctetString(2, value.EpochKey0);
        if (value.EpochStartTime0 != null) { tlv.AddUInt64(3, value.EpochStartTime0.Value); } else { tlv.AddNull(3); }
        tlv.AddOctetString(4, value.EpochKey1);
        if (value.EpochStartTime1 != null) { tlv.AddUInt64(5, value.EpochStartTime1.Value); } else { tlv.AddNull(5); }
        tlv.AddOctetString(6, value.EpochKey2);
        if (value.EpochStartTime2 != null) { tlv.AddUInt64(7, value.EpochStartTime2.Value); } else { tlv.AddNull(7); }
        tlv.AddUInt8(8, (byte)value.GroupKeyMulticastPolicy);
    }

    private static void WriteDatastoreNodeInformationEntryStruct(MatterTLV tlv, byte tag, DatastoreNodeInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreNodeInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreNodeInformationEntryStruct(MatterTLV tlv, DatastoreNodeInformationEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreNodeInformationEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreNodeInformationEntryStructFields(MatterTLV tlv, DatastoreNodeInformationEntryStruct value)
    {
        tlv.AddUInt64(1, value.NodeID);
        tlv.AddUTF8String(2, value.FriendlyName);
        WriteDatastoreStatusEntryStruct(tlv, 3, value.CommissioningStatusEntry);
    }

    private static void WriteDatastoreNodeKeySetEntryStruct(MatterTLV tlv, byte tag, DatastoreNodeKeySetEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreNodeKeySetEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreNodeKeySetEntryStruct(MatterTLV tlv, DatastoreNodeKeySetEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreNodeKeySetEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreNodeKeySetEntryStructFields(MatterTLV tlv, DatastoreNodeKeySetEntryStruct value)
    {
        tlv.AddUInt64(0, value.NodeID);
        tlv.AddUInt16(1, value.GroupKeySetID);
        WriteDatastoreStatusEntryStruct(tlv, 2, value.StatusEntry);
    }

    private static void WriteDatastoreStatusEntryStruct(MatterTLV tlv, byte tag, DatastoreStatusEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteDatastoreStatusEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreStatusEntryStruct(MatterTLV tlv, DatastoreStatusEntryStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteDatastoreStatusEntryStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteDatastoreStatusEntryStructFields(MatterTLV tlv, DatastoreStatusEntryStruct value)
    {
        tlv.AddUInt8(0, (byte)value.State);
        tlv.AddUInt32(1, value.UpdateTimestamp);
        tlv.AddUInt8(2, value.FailureCode);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>AnchorRootCA (0x0000).</summary>
        public const uint AnchorRootCA = 0x0000;
        /// <summary>AnchorNodeID (0x0001).</summary>
        public const uint AnchorNodeID = 0x0001;
        /// <summary>AnchorVendorID (0x0002).</summary>
        public const uint AnchorVendorID = 0x0002;
        /// <summary>FriendlyName (0x0003).</summary>
        public const uint FriendlyName = 0x0003;
        /// <summary>GroupKeySetList (0x0004).</summary>
        public const uint GroupKeySetList = 0x0004;
        /// <summary>GroupList (0x0005).</summary>
        public const uint GroupList = 0x0005;
        /// <summary>NodeList (0x0006).</summary>
        public const uint NodeList = 0x0006;
        /// <summary>AdminList (0x0007).</summary>
        public const uint AdminList = 0x0007;
        /// <summary>Status (0x0008).</summary>
        public const uint Status = 0x0008;
        /// <summary>EndpointGroupIDList (0x0009).</summary>
        public const uint EndpointGroupIDList = 0x0009;
        /// <summary>EndpointBindingList (0x000A).</summary>
        public const uint EndpointBindingList = 0x000A;
        /// <summary>NodeKeySetList (0x000B).</summary>
        public const uint NodeKeySetList = 0x000B;
        /// <summary>NodeACLList (0x000C).</summary>
        public const uint NodeACLList = 0x000C;
        /// <summary>NodeEndpointList (0x000D).</summary>
        public const uint NodeEndpointList = 0x000D;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>AddKeySet (0x0000).</summary>
        public const uint AddKeySet = 0x0000;
        /// <summary>UpdateKeySet (0x0001).</summary>
        public const uint UpdateKeySet = 0x0001;
        /// <summary>RemoveKeySet (0x0002).</summary>
        public const uint RemoveKeySet = 0x0002;
        /// <summary>AddGroup (0x0003).</summary>
        public const uint AddGroup = 0x0003;
        /// <summary>UpdateGroup (0x0004).</summary>
        public const uint UpdateGroup = 0x0004;
        /// <summary>RemoveGroup (0x0005).</summary>
        public const uint RemoveGroup = 0x0005;
        /// <summary>AddAdmin (0x0006).</summary>
        public const uint AddAdmin = 0x0006;
        /// <summary>UpdateAdmin (0x0007).</summary>
        public const uint UpdateAdmin = 0x0007;
        /// <summary>RemoveAdmin (0x0008).</summary>
        public const uint RemoveAdmin = 0x0008;
        /// <summary>AddPendingNode (0x0009).</summary>
        public const uint AddPendingNode = 0x0009;
        /// <summary>RefreshNode (0x000A).</summary>
        public const uint RefreshNode = 0x000A;
        /// <summary>UpdateNode (0x000B).</summary>
        public const uint UpdateNode = 0x000B;
        /// <summary>RemoveNode (0x000C).</summary>
        public const uint RemoveNode = 0x000C;
        /// <summary>UpdateEndpointForNode (0x000D).</summary>
        public const uint UpdateEndpointForNode = 0x000D;
        /// <summary>AddGroupIDToEndpointForNode (0x000E).</summary>
        public const uint AddGroupIDToEndpointForNode = 0x000E;
        /// <summary>RemoveGroupIDFromEndpointForNode (0x000F).</summary>
        public const uint RemoveGroupIDFromEndpointForNode = 0x000F;
        /// <summary>AddBindingToEndpointForNode (0x0010).</summary>
        public const uint AddBindingToEndpointForNode = 0x0010;
        /// <summary>RemoveBindingFromEndpointForNode (0x0011).</summary>
        public const uint RemoveBindingFromEndpointForNode = 0x0011;
        /// <summary>AddACLToNode (0x0012).</summary>
        public const uint AddACLToNode = 0x0012;
        /// <summary>RemoveACLFromNode (0x0013).</summary>
        public const uint RemoveACLFromNode = 0x0013;
    }

    // Async command methods

    /// <summary>Send AddKeySet command (0x0000).</summary>
    public Task<InvokeResponse> AddKeySetAsync(
        DatastoreGroupKeySetStruct groupKeySet,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { WriteDatastoreGroupKeySetStruct(tlv, 0, groupKeySet); }, ct);

    /// <summary>Send UpdateKeySet command (0x0001).</summary>
    public Task<InvokeResponse> UpdateKeySetAsync(
        DatastoreGroupKeySetStruct groupKeySet,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv => { WriteDatastoreGroupKeySetStruct(tlv, 0, groupKeySet); }, ct);

    /// <summary>Send RemoveKeySet command (0x0002).</summary>
    public Task<InvokeResponse> RemoveKeySetAsync(
        ushort groupKeySetID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv => { tlv.AddUInt16(0, groupKeySetID); }, ct);

    /// <summary>Send AddGroup command (0x0003).</summary>
    public Task<InvokeResponse> AddGroupAsync(
        ushort groupID,
        string friendlyName,
        ushort? groupKeySetID,
        ushort? groupCAT,
        ushort? groupCATVersion,
        DatastoreAccessControlEntryPrivilegeEnum groupPermission,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUTF8String(1, friendlyName);
            if (groupKeySetID != null) { tlv.AddUInt16(2, groupKeySetID.Value); } else { tlv.AddNull(2); }
            if (groupCAT != null) { tlv.AddUInt16(3, groupCAT.Value); } else { tlv.AddNull(3); }
            if (groupCATVersion != null) { tlv.AddUInt16(4, groupCATVersion.Value); } else { tlv.AddNull(4); }
            tlv.AddUInt8(5, (byte)groupPermission);
        }, ct);

    /// <summary>Send UpdateGroup command (0x0004).</summary>
    public Task<InvokeResponse> UpdateGroupAsync(
        ushort groupID,
        string friendlyName,
        ushort? groupKeySetID,
        ushort? groupCAT,
        ushort? groupCATVersion,
        DatastoreAccessControlEntryPrivilegeEnum groupPermission,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUTF8String(1, friendlyName);
            if (groupKeySetID != null) { tlv.AddUInt16(2, groupKeySetID.Value); } else { tlv.AddNull(2); }
            if (groupCAT != null) { tlv.AddUInt16(3, groupCAT.Value); } else { tlv.AddNull(3); }
            if (groupCATVersion != null) { tlv.AddUInt16(4, groupCATVersion.Value); } else { tlv.AddNull(4); }
            tlv.AddUInt8(5, (byte)groupPermission);
        }, ct);

    /// <summary>Send RemoveGroup command (0x0005).</summary>
    public Task<InvokeResponse> RemoveGroupAsync(
        ushort groupID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv => { tlv.AddUInt16(0, groupID); }, ct);

    /// <summary>Send AddAdmin command (0x0006).</summary>
    public Task<InvokeResponse> AddAdminAsync(
        ulong nodeID,
        string friendlyName,
        ushort vendorID,
        byte[] iCAC,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv =>
        {
            tlv.AddUInt64(1, nodeID);
            tlv.AddUTF8String(2, friendlyName);
            tlv.AddUInt16(3, vendorID);
            tlv.AddOctetString(4, iCAC);
        }, ct);

    /// <summary>Send UpdateAdmin command (0x0007).</summary>
    public Task<InvokeResponse> UpdateAdminAsync(
        ulong? nodeID,
        string friendlyName,
        byte[] iCAC,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0007, tlv =>
        {
            if (nodeID != null) { tlv.AddUInt64(0, nodeID.Value); } else { tlv.AddNull(0); }
            tlv.AddUTF8String(1, friendlyName);
            tlv.AddOctetString(2, iCAC);
        }, ct);

    /// <summary>Send RemoveAdmin command (0x0008).</summary>
    public Task<InvokeResponse> RemoveAdminAsync(
        ulong nodeID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0008, tlv => { tlv.AddUInt64(0, nodeID); }, ct);

    /// <summary>Send AddPendingNode command (0x0009).</summary>
    public Task<InvokeResponse> AddPendingNodeAsync(
        ulong nodeID,
        string friendlyName,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0009, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            tlv.AddUTF8String(1, friendlyName);
        }, ct);

    /// <summary>Send RefreshNode command (0x000A).</summary>
    public Task<InvokeResponse> RefreshNodeAsync(
        ulong nodeID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000A, tlv => { tlv.AddUInt64(0, nodeID); }, ct);

    /// <summary>Send UpdateNode command (0x000B).</summary>
    public Task<InvokeResponse> UpdateNodeAsync(
        ulong nodeID,
        string friendlyName,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000B, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            tlv.AddUTF8String(1, friendlyName);
        }, ct);

    /// <summary>Send RemoveNode command (0x000C).</summary>
    public Task<InvokeResponse> RemoveNodeAsync(
        ulong nodeID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000C, tlv => { tlv.AddUInt64(0, nodeID); }, ct);

    /// <summary>Send UpdateEndpointForNode command (0x000D).</summary>
    public Task<InvokeResponse> UpdateEndpointForNodeAsync(
        ushort endpointID,
        ulong nodeID,
        string friendlyName,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000D, tlv =>
        {
            tlv.AddUInt16(0, endpointID);
            tlv.AddUInt64(1, nodeID);
            tlv.AddUTF8String(2, friendlyName);
        }, ct);

    /// <summary>Send AddGroupIDToEndpointForNode command (0x000E).</summary>
    public Task<InvokeResponse> AddGroupIDToEndpointForNodeAsync(
        ulong nodeID,
        ushort endpointID,
        ushort groupID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000E, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            tlv.AddUInt16(1, endpointID);
            tlv.AddUInt16(2, groupID);
        }, ct);

    /// <summary>Send RemoveGroupIDFromEndpointForNode command (0x000F).</summary>
    public Task<InvokeResponse> RemoveGroupIDFromEndpointForNodeAsync(
        ulong nodeID,
        ushort endpointID,
        ushort groupID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x000F, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            tlv.AddUInt16(1, endpointID);
            tlv.AddUInt16(2, groupID);
        }, ct);

    /// <summary>Send AddBindingToEndpointForNode command (0x0010).</summary>
    public Task<InvokeResponse> AddBindingToEndpointForNodeAsync(
        ulong nodeID,
        ushort endpointID,
        DatastoreBindingTargetStruct binding,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0010, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            tlv.AddUInt16(1, endpointID);
            WriteDatastoreBindingTargetStruct(tlv, 2, binding);
        }, ct);

    /// <summary>Send RemoveBindingFromEndpointForNode command (0x0011).</summary>
    public Task<InvokeResponse> RemoveBindingFromEndpointForNodeAsync(
        ushort listID,
        ushort endpointID,
        ulong nodeID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0011, tlv =>
        {
            tlv.AddUInt16(0, listID);
            tlv.AddUInt16(1, endpointID);
            tlv.AddUInt64(2, nodeID);
        }, ct);

    /// <summary>Send AddACLToNode command (0x0012).</summary>
    public Task<InvokeResponse> AddACLToNodeAsync(
        ulong nodeID,
        DatastoreAccessControlEntryStruct aCLEntry,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0012, tlv =>
        {
            tlv.AddUInt64(0, nodeID);
            WriteDatastoreAccessControlEntryStruct(tlv, 1, aCLEntry);
        }, ct);

    /// <summary>Send RemoveACLFromNode command (0x0013).</summary>
    public Task<InvokeResponse> RemoveACLFromNodeAsync(
        ushort listID,
        ulong nodeID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0013, tlv =>
        {
            tlv.AddUInt16(0, listID);
            tlv.AddUInt64(1, nodeID);
        }, ct);

    // Attribute readers

    /// <summary>Read AnchorRootCA attribute (0x0000).</summary>
    public Task<byte[]?> ReadAnchorRootCAAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<byte[]>(0x0000, ct);

    /// <summary>Read AnchorNodeID attribute (0x0001).</summary>
    public Task<ulong> ReadAnchorNodeIDAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ulong>(0x0001, ct);

    /// <summary>Read AnchorVendorID attribute (0x0002).</summary>
    public Task<ushort> ReadAnchorVendorIDAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0002, ct);

    /// <summary>Read FriendlyName attribute (0x0003).</summary>
    public Task<string?> ReadFriendlyNameAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0003, ct);

    /// <summary>Read GroupKeySetList attribute (0x0004).</summary>
    public Task<DatastoreGroupKeySetStruct[]?> ReadGroupKeySetListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreGroupKeySetStruct[]>(0x0004, ct);

    /// <summary>Read GroupList attribute (0x0005).</summary>
    public Task<DatastoreGroupInformationEntryStruct[]?> ReadGroupListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreGroupInformationEntryStruct[]>(0x0005, ct);

    /// <summary>Read NodeList attribute (0x0006).</summary>
    public Task<DatastoreNodeInformationEntryStruct[]?> ReadNodeListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreNodeInformationEntryStruct[]>(0x0006, ct);

    /// <summary>Read AdminList attribute (0x0007).</summary>
    public Task<DatastoreAdministratorInformationEntryStruct[]?> ReadAdminListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreAdministratorInformationEntryStruct[]>(0x0007, ct);

    /// <summary>Read Status attribute (0x0008).</summary>
    public Task<object?> ReadStatusAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0008, ct);

    /// <summary>Read EndpointGroupIDList attribute (0x0009).</summary>
    public Task<DatastoreEndpointGroupIDEntryStruct[]?> ReadEndpointGroupIDListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreEndpointGroupIDEntryStruct[]>(0x0009, ct);

    /// <summary>Read EndpointBindingList attribute (0x000A).</summary>
    public Task<DatastoreEndpointBindingEntryStruct[]?> ReadEndpointBindingListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreEndpointBindingEntryStruct[]>(0x000A, ct);

    /// <summary>Read NodeKeySetList attribute (0x000B).</summary>
    public Task<DatastoreNodeKeySetEntryStruct[]?> ReadNodeKeySetListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreNodeKeySetEntryStruct[]>(0x000B, ct);

    /// <summary>Read NodeACLList attribute (0x000C).</summary>
    public Task<DatastoreACLEntryStruct[]?> ReadNodeACLListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreACLEntryStruct[]>(0x000C, ct);

    /// <summary>Read NodeEndpointList attribute (0x000D).</summary>
    public Task<DatastoreEndpointEntryStruct[]?> ReadNodeEndpointListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<DatastoreEndpointEntryStruct[]>(0x000D, ct);
}
