// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: microwave-oven-control-cluster.xml
// Cluster: Microwave Oven Control (0x005F)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Microwave Oven Control (0x005F, rev 1)</summary>
public class MicrowaveOvenControlCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x005F;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="MicrowaveOvenControlCluster"/> bound to the given session and endpoint.</summary>
    public MicrowaveOvenControlCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Power is specified as a unitless number or a percentage</summary>
        PowerAsNumber = 1u << 0,
        /// <summary>Power is specified in Watts</summary>
        PowerInWatts = 1u << 1,
        /// <summary>Supports the limit attributes used with the PWRNUM feature</summary>
        PowerNumberLimits = 1u << 2,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>CookTime (0x0000).</summary>
        public const uint CookTime = 0x0000;
        /// <summary>MaxCookTime (0x0001).</summary>
        public const uint MaxCookTime = 0x0001;
        /// <summary>PowerSetting (0x0002).</summary>
        public const uint PowerSetting = 0x0002;
        /// <summary>MinPower (0x0003).</summary>
        public const uint MinPower = 0x0003;
        /// <summary>MaxPower (0x0004).</summary>
        public const uint MaxPower = 0x0004;
        /// <summary>PowerStep (0x0005).</summary>
        public const uint PowerStep = 0x0005;
        /// <summary>SupportedWatts (0x0006).</summary>
        public const uint SupportedWatts = 0x0006;
        /// <summary>SelectedWattIndex (0x0007).</summary>
        public const uint SelectedWattIndex = 0x0007;
        /// <summary>WattRating (0x0008).</summary>
        public const uint WattRating = 0x0008;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>SetCookingParameters (0x0000).</summary>
        public const uint SetCookingParameters = 0x0000;
        /// <summary>AddMoreTime (0x0001).</summary>
        public const uint AddMoreTime = 0x0001;
    }

    // Async command methods

    /// <summary>Send SetCookingParameters command (0x0000).</summary>
    public Task<InvokeResponse> SetCookingParametersAsync(
        byte? cookMode = default,
        uint? cookTime = default,
        byte? powerSetting = default,
        byte? wattSettingIndex = default,
        bool? startAfterSetting = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            if (cookMode != null) tlv.AddUInt8(0, cookMode.Value);
            if (cookTime != null) tlv.AddUInt32(1, cookTime.Value);
            if (powerSetting != null) tlv.AddUInt8(2, powerSetting.Value);
            if (wattSettingIndex != null) tlv.AddUInt8(3, wattSettingIndex.Value);
            if (startAfterSetting != null) tlv.AddBool(4, startAfterSetting.Value);
        }, ct);

    /// <summary>Send AddMoreTime command (0x0001).</summary>
    public Task<InvokeResponse> AddMoreTimeAsync(
        uint timeToAdd,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv => { tlv.AddUInt32(0, timeToAdd); }, ct);

    // Attribute readers

    /// <summary>Read CookTime attribute (0x0000).</summary>
    public Task<uint> ReadCookTimeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0000, ct);

    /// <summary>Read MaxCookTime attribute (0x0001).</summary>
    public Task<uint> ReadMaxCookTimeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0001, ct);

    /// <summary>Read PowerSetting attribute (0x0002).</summary>
    public Task<byte> ReadPowerSettingAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0002, ct);

    /// <summary>Read MinPower attribute (0x0003).</summary>
    public Task<byte> ReadMinPowerAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0003, ct);

    /// <summary>Read MaxPower attribute (0x0004).</summary>
    public Task<byte> ReadMaxPowerAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0004, ct);

    /// <summary>Read PowerStep attribute (0x0005).</summary>
    public Task<byte> ReadPowerStepAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0005, ct);

    /// <summary>Read SupportedWatts attribute (0x0006).</summary>
    public Task<ushort[]?> ReadSupportedWattsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ushort[]>(0x0006, ct);

    /// <summary>Read SelectedWattIndex attribute (0x0007).</summary>
    public Task<byte> ReadSelectedWattIndexAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0007, ct);

    /// <summary>Read WattRating attribute (0x0008).</summary>
    public Task<ushort> ReadWattRatingAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0008, ct);
}
