// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: operational-state-cluster.xml
// Cluster: Operational State (0x0060)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Operational State (0x0060, rev 1)</summary>
public class OperationalStateCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0060;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="OperationalStateCluster"/> bound to the given session and endpoint.</summary>
    public OperationalStateCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>OperationalStateEnum enum values.</summary>
    public enum OperationalStateEnum : byte
    {
        /// <summary>Stopped value.</summary>
        Stopped = 0x00,
        /// <summary>Running value.</summary>
        Running = 0x01,
        /// <summary>Paused value.</summary>
        Paused = 0x02,
        /// <summary>Error value.</summary>
        Error = 0x03,
    }

    /// <summary>ErrorStateEnum enum values.</summary>
    public enum ErrorStateEnum : byte
    {
        /// <summary>NoError value.</summary>
        NoError = 0x00,
        /// <summary>UnableToStartOrResume value.</summary>
        UnableToStartOrResume = 0x01,
        /// <summary>UnableToCompleteOperation value.</summary>
        UnableToCompleteOperation = 0x02,
        /// <summary>CommandInvalidInState value.</summary>
        CommandInvalidInState = 0x03,
    }

    /// <summary>OperationalStateStruct struct.</summary>
    public sealed class OperationalStateStruct
    {
        /// <summary>Gets or sets OperationalStateID.</summary>
        public byte OperationalStateID { get; set; }
        /// <summary>Gets or sets OperationalStateLabel.</summary>
        public string? OperationalStateLabel { get; set; }
    }

    /// <summary>ErrorStateStruct struct.</summary>
    public sealed class ErrorStateStruct
    {
        /// <summary>Gets or sets ErrorStateID.</summary>
        public byte ErrorStateID { get; set; }
        /// <summary>Gets or sets ErrorStateLabel.</summary>
        public string? ErrorStateLabel { get; set; }
        /// <summary>Gets or sets ErrorStateDetails.</summary>
        public string? ErrorStateDetails { get; set; }
    }

    // TLV struct serializers

    private static void WriteOperationalStateStruct(MatterTLV tlv, byte tag, OperationalStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteOperationalStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOperationalStateStruct(MatterTLV tlv, OperationalStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteOperationalStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteOperationalStateStructFields(MatterTLV tlv, OperationalStateStruct value)
    {
        tlv.AddUInt8(0, value.OperationalStateID);
        if (value.OperationalStateLabel != null) tlv.AddUTF8String(1, value.OperationalStateLabel);
    }

    private static void WriteErrorStateStruct(MatterTLV tlv, byte tag, ErrorStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteErrorStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteErrorStateStruct(MatterTLV tlv, ErrorStateStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteErrorStateStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteErrorStateStructFields(MatterTLV tlv, ErrorStateStruct value)
    {
        tlv.AddUInt8(0, value.ErrorStateID);
        if (value.ErrorStateLabel != null) tlv.AddUTF8String(1, value.ErrorStateLabel);
        if (value.ErrorStateDetails != null) tlv.AddUTF8String(2, value.ErrorStateDetails);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>PhaseList (0x0000).</summary>
        public const uint PhaseList = 0x0000;
        /// <summary>CurrentPhase (0x0001).</summary>
        public const uint CurrentPhase = 0x0001;
        /// <summary>CountdownTime (0x0002).</summary>
        public const uint CountdownTime = 0x0002;
        /// <summary>OperationalStateList (0x0003).</summary>
        public const uint OperationalStateList = 0x0003;
        /// <summary>OperationalState (0x0004).</summary>
        public const uint OperationalState = 0x0004;
        /// <summary>OperationalError (0x0005).</summary>
        public const uint OperationalError = 0x0005;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>Pause (0x0000).</summary>
        public const uint Pause = 0x0000;
        /// <summary>Stop (0x0001).</summary>
        public const uint Stop = 0x0001;
        /// <summary>Start (0x0002).</summary>
        public const uint Start = 0x0002;
        /// <summary>Resume (0x0003).</summary>
        public const uint Resume = 0x0003;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>OperationalError (0x0000).</summary>
        public const uint OperationalError = 0x0000;
        /// <summary>OperationCompletion (0x0001).</summary>
        public const uint OperationCompletion = 0x0001;
    }

    // Async command methods

    /// <summary>Send Pause command (0x0000).</summary>
    public Task<InvokeResponse> PauseAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    /// <summary>Send Stop command (0x0001).</summary>
    public Task<InvokeResponse> StopAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, ct: ct);

    /// <summary>Send Start command (0x0002).</summary>
    public Task<InvokeResponse> StartAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, ct: ct);

    /// <summary>Send Resume command (0x0003).</summary>
    public Task<InvokeResponse> ResumeAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, ct: ct);

    // Attribute readers

    /// <summary>Read PhaseList attribute (0x0000).</summary>
    public Task<string[]?> ReadPhaseListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string[]>(0x0000, ct);

    /// <summary>Read CurrentPhase attribute (0x0001).</summary>
    public Task<byte?> ReadCurrentPhaseAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read CountdownTime attribute (0x0002).</summary>
    public Task<uint?> ReadCountdownTimeAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0002, ct);

    /// <summary>Read OperationalStateList attribute (0x0003).</summary>
    public Task<OperationalStateStruct[]?> ReadOperationalStateListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<OperationalStateStruct[]>(0x0003, ct);

    /// <summary>Read OperationalState attribute (0x0004).</summary>
    public Task<OperationalStateEnum> ReadOperationalStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<OperationalStateEnum>(0x0004, ct);

    /// <summary>Read OperationalError attribute (0x0005).</summary>
    public Task<object?> ReadOperationalErrorAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0005, ct);
}
