// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: power-topology-cluster.xml
// Cluster: Power Topology (0x009C)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Power Topology (0x009C, rev 1)</summary>
public class PowerTopologyCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x009C;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="PowerTopologyCluster"/> bound to the given session and endpoint.</summary>
    public PowerTopologyCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>This endpoint provides or consumes power to/from the entire node</summary>
        NodeTopology = 1u << 0,
        /// <summary>This endpoint provides or consumes power to/from itself and its child endpoints</summary>
        TreeTopology = 1u << 1,
        /// <summary>This endpoint provides or consumes power to/from a specified set of endpoints</summary>
        SetTopology = 1u << 2,
        /// <summary>The specified set of endpoints may change</summary>
        DynamicPowerFlow = 1u << 3,
        /// <summary>This endpoint provides information about downstream nodes on its circuit</summary>
        ElectricalCircuit = 1u << 4,
    }

    /// <summary>CircuitNodeStruct struct.</summary>
    public sealed class CircuitNodeStruct
    {
        /// <summary>Gets or sets Node.</summary>
        public ulong Node { get; set; }
        /// <summary>Gets or sets Endpoint.</summary>
        public ushort? Endpoint { get; set; }
        /// <summary>Gets or sets Label.</summary>
        public string? Label { get; set; }
        /// <summary>Gets or sets FabricIndex.</summary>
        public byte FabricIndex { get; set; }
    }

    // TLV struct serializers

    private static void WriteCircuitNodeStruct(MatterTLV tlv, byte tag, CircuitNodeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteCircuitNodeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCircuitNodeStruct(MatterTLV tlv, CircuitNodeStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteCircuitNodeStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteCircuitNodeStructFields(MatterTLV tlv, CircuitNodeStruct value)
    {
        tlv.AddUInt64(1, value.Node);
        if (value.Endpoint != null) tlv.AddUInt16(2, value.Endpoint.Value);
        if (value.Label != null) tlv.AddUTF8String(3, value.Label);
    }

    // TLV struct deserializers

    private static CircuitNodeStruct ReadCircuitNodeStruct(MatterTLV tlv)
        => ReadCircuitNodeStruct(tlv, null);

    private static CircuitNodeStruct ReadCircuitNodeStruct(MatterTLV tlv, int? tag)
    {
        var value = new CircuitNodeStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 1:
                    value.Node = tlv.GetUnsignedInt(1);
                    break;
                case 2:
                    if (tlv.IsNextNull()) { tlv.GetNull(2); } else { value.Endpoint = (ushort)tlv.GetUnsignedIntAny(2); }
                    break;
                case 3:
                    if (tlv.IsNextNull()) { tlv.GetNull(3); } else { value.Label = tlv.GetUTF8String(3); }
                    break;
                case 254:
                    value.FabricIndex = (byte)tlv.GetUnsignedIntAny(254);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>AvailableEndpoints (0x0000).</summary>
        public const uint AvailableEndpoints = 0x0000;
        /// <summary>ActiveEndpoints (0x0001).</summary>
        public const uint ActiveEndpoints = 0x0001;
        /// <summary>ElectricalCircuitNodes (0x0002).</summary>
        public const uint ElectricalCircuitNodes = 0x0002;
    }

    // Attribute readers

    /// <summary>Read AvailableEndpoints attribute (0x0000).</summary>
    public Task<ushort[]?> ReadAvailableEndpointsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ushort[]>(0x0000, ct);

    /// <summary>Read ActiveEndpoints attribute (0x0001).</summary>
    public Task<ushort[]?> ReadActiveEndpointsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ushort[]>(0x0001, ct);

    /// <summary>Read ElectricalCircuitNodes attribute (0x0002).</summary>
    public Task<CircuitNodeStruct[]?> ReadElectricalCircuitNodesAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0002, ReadCircuitNodeStruct, ct);

    // Attribute writers

    /// <summary>Write ElectricalCircuitNodes attribute (0x0002).</summary>
    public Task<WriteResponse> WriteElectricalCircuitNodesAsync(
        CircuitNodeStruct[] electricalCircuitNodes,
        bool timedRequest = true,
        ushort timedTimeoutMs = 5000,
        CancellationToken ct = default)
        => WriteAttributeAsync(0x0002, tlv =>
        {
            ArgumentNullException.ThrowIfNull(electricalCircuitNodes);
            if (electricalCircuitNodes != null) { tlv.AddArray(2); foreach (var item in electricalCircuitNodes) { WriteCircuitNodeStruct(tlv, item); } tlv.EndContainer(); }
        }, timedRequest, timedTimeoutMs, ct);
}
