// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: power-source-cluster.xml
// Cluster: Power Source (0x002F)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Power Source (0x002F, rev 3)</summary>
public class PowerSourceCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x002F;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="PowerSourceCluster"/> bound to the given session and endpoint.</summary>
    public PowerSourceCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>A wired power source</summary>
        Wired = 1u << 0,
        /// <summary>A battery power source</summary>
        Battery = 1u << 1,
        /// <summary>A rechargeable battery power source</summary>
        Rechargeable = 1u << 2,
        /// <summary>A replaceable battery power source</summary>
        Replaceable = 1u << 3,
    }

    /// <summary>WiredFaultEnum enum values.</summary>
    public enum WiredFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>OverVoltage value.</summary>
        OverVoltage = 0x01,
        /// <summary>UnderVoltage value.</summary>
        UnderVoltage = 0x02,
    }

    /// <summary>BatFaultEnum enum values.</summary>
    public enum BatFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>OverTemp value.</summary>
        OverTemp = 0x01,
        /// <summary>UnderTemp value.</summary>
        UnderTemp = 0x02,
    }

    /// <summary>BatChargeFaultEnum enum values.</summary>
    public enum BatChargeFaultEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>AmbientTooHot value.</summary>
        AmbientTooHot = 0x01,
        /// <summary>AmbientTooCold value.</summary>
        AmbientTooCold = 0x02,
        /// <summary>BatteryTooHot value.</summary>
        BatteryTooHot = 0x03,
        /// <summary>BatteryTooCold value.</summary>
        BatteryTooCold = 0x04,
        /// <summary>BatteryAbsent value.</summary>
        BatteryAbsent = 0x05,
        /// <summary>BatteryOverVoltage value.</summary>
        BatteryOverVoltage = 0x06,
        /// <summary>BatteryUnderVoltage value.</summary>
        BatteryUnderVoltage = 0x07,
        /// <summary>ChargerOverVoltage value.</summary>
        ChargerOverVoltage = 0x08,
        /// <summary>ChargerUnderVoltage value.</summary>
        ChargerUnderVoltage = 0x09,
        /// <summary>SafetyTimeout value.</summary>
        SafetyTimeout = 0x0A,
    }

    /// <summary>PowerSourceStatusEnum enum values.</summary>
    public enum PowerSourceStatusEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>Active value.</summary>
        Active = 0x01,
        /// <summary>Standby value.</summary>
        Standby = 0x02,
        /// <summary>Unavailable value.</summary>
        Unavailable = 0x03,
    }

    /// <summary>WiredCurrentTypeEnum enum values.</summary>
    public enum WiredCurrentTypeEnum : byte
    {
        /// <summary>AC value.</summary>
        AC = 0x00,
        /// <summary>DC value.</summary>
        DC = 0x01,
    }

    /// <summary>BatChargeLevelEnum enum values.</summary>
    public enum BatChargeLevelEnum : byte
    {
        /// <summary>OK value.</summary>
        OK = 0x00,
        /// <summary>Warning value.</summary>
        Warning = 0x01,
        /// <summary>Critical value.</summary>
        Critical = 0x02,
    }

    /// <summary>BatReplaceabilityEnum enum values.</summary>
    public enum BatReplaceabilityEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>NotReplaceable value.</summary>
        NotReplaceable = 0x01,
        /// <summary>UserReplaceable value.</summary>
        UserReplaceable = 0x02,
        /// <summary>FactoryReplaceable value.</summary>
        FactoryReplaceable = 0x03,
    }

    /// <summary>BatChargeStateEnum enum values.</summary>
    public enum BatChargeStateEnum : byte
    {
        /// <summary>Unknown value.</summary>
        Unknown = 0x00,
        /// <summary>IsCharging value.</summary>
        IsCharging = 0x01,
        /// <summary>IsAtFullCharge value.</summary>
        IsAtFullCharge = 0x02,
        /// <summary>IsNotCharging value.</summary>
        IsNotCharging = 0x03,
    }

    /// <summary>BatCommonDesignationEnum enum values.</summary>
    public enum BatCommonDesignationEnum : ushort
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x0000,
        /// <summary>AAA value.</summary>
        AAA = 0x0001,
        /// <summary>AA value.</summary>
        AA = 0x0002,
        /// <summary>C value.</summary>
        C = 0x0003,
        /// <summary>D value.</summary>
        D = 0x0004,
        /// <summary>4v5 value.</summary>
        _4v5 = 0x0005,
        /// <summary>6v0 value.</summary>
        _6v0 = 0x0006,
        /// <summary>9v0 value.</summary>
        _9v0 = 0x0007,
        /// <summary>1_2AA value.</summary>
        _12AA = 0x0008,
        /// <summary>AAAA value.</summary>
        AAAA = 0x0009,
        /// <summary>A value.</summary>
        A = 0x000A,
        /// <summary>B value.</summary>
        B = 0x000B,
        /// <summary>F value.</summary>
        F = 0x000C,
        /// <summary>N value.</summary>
        N = 0x000D,
        /// <summary>No6 value.</summary>
        No6 = 0x000E,
        /// <summary>SubC value.</summary>
        SubC = 0x000F,
        /// <summary>A23 value.</summary>
        A23 = 0x0010,
        /// <summary>A27 value.</summary>
        A27 = 0x0011,
        /// <summary>BA5800 value.</summary>
        BA5800 = 0x0012,
        /// <summary>Duplex value.</summary>
        Duplex = 0x0013,
        /// <summary>4SR44 value.</summary>
        _4SR44 = 0x0014,
        /// <summary>523 value.</summary>
        _523 = 0x0015,
        /// <summary>531 value.</summary>
        _531 = 0x0016,
        /// <summary>15v0 value.</summary>
        _15v0 = 0x0017,
        /// <summary>22v5 value.</summary>
        _22v5 = 0x0018,
        /// <summary>30v0 value.</summary>
        _30v0 = 0x0019,
        /// <summary>45v0 value.</summary>
        _45v0 = 0x001A,
        /// <summary>67v5 value.</summary>
        _67v5 = 0x001B,
        /// <summary>J value.</summary>
        J = 0x001C,
        /// <summary>CR123A value.</summary>
        CR123A = 0x001D,
        /// <summary>CR2 value.</summary>
        CR2 = 0x001E,
        /// <summary>2CR5 value.</summary>
        _2CR5 = 0x001F,
        /// <summary>CR_P2 value.</summary>
        CRP2 = 0x0020,
        /// <summary>CR_V3 value.</summary>
        CRV3 = 0x0021,
        /// <summary>SR41 value.</summary>
        SR41 = 0x0022,
        /// <summary>SR43 value.</summary>
        SR43 = 0x0023,
        /// <summary>SR44 value.</summary>
        SR44 = 0x0024,
        /// <summary>SR45 value.</summary>
        SR45 = 0x0025,
        /// <summary>SR48 value.</summary>
        SR48 = 0x0026,
        /// <summary>SR54 value.</summary>
        SR54 = 0x0027,
        /// <summary>SR55 value.</summary>
        SR55 = 0x0028,
        /// <summary>SR57 value.</summary>
        SR57 = 0x0029,
        /// <summary>SR58 value.</summary>
        SR58 = 0x002A,
        /// <summary>SR59 value.</summary>
        SR59 = 0x002B,
        /// <summary>SR60 value.</summary>
        SR60 = 0x002C,
        /// <summary>SR63 value.</summary>
        SR63 = 0x002D,
        /// <summary>SR64 value.</summary>
        SR64 = 0x002E,
        /// <summary>SR65 value.</summary>
        SR65 = 0x002F,
        /// <summary>SR66 value.</summary>
        SR66 = 0x0030,
        /// <summary>SR67 value.</summary>
        SR67 = 0x0031,
        /// <summary>SR68 value.</summary>
        SR68 = 0x0032,
        /// <summary>SR69 value.</summary>
        SR69 = 0x0033,
        /// <summary>SR516 value.</summary>
        SR516 = 0x0034,
        /// <summary>SR731 value.</summary>
        SR731 = 0x0035,
        /// <summary>SR712 value.</summary>
        SR712 = 0x0036,
        /// <summary>LR932 value.</summary>
        LR932 = 0x0037,
        /// <summary>A5 value.</summary>
        A5 = 0x0038,
        /// <summary>A10 value.</summary>
        A10 = 0x0039,
        /// <summary>A13 value.</summary>
        A13 = 0x003A,
        /// <summary>A312 value.</summary>
        A312 = 0x003B,
        /// <summary>A675 value.</summary>
        A675 = 0x003C,
        /// <summary>AC41E value.</summary>
        AC41E = 0x003D,
        /// <summary>10180 value.</summary>
        _10180 = 0x003E,
        /// <summary>10280 value.</summary>
        _10280 = 0x003F,
        /// <summary>10440 value.</summary>
        _10440 = 0x0040,
        /// <summary>14250 value.</summary>
        _14250 = 0x0041,
        /// <summary>14430 value.</summary>
        _14430 = 0x0042,
        /// <summary>14500 value.</summary>
        _14500 = 0x0043,
        /// <summary>14650 value.</summary>
        _14650 = 0x0044,
        /// <summary>15270 value.</summary>
        _15270 = 0x0045,
        /// <summary>16340 value.</summary>
        _16340 = 0x0046,
        /// <summary>RCR123A value.</summary>
        RCR123A = 0x0047,
        /// <summary>17500 value.</summary>
        _17500 = 0x0048,
        /// <summary>17670 value.</summary>
        _17670 = 0x0049,
        /// <summary>18350 value.</summary>
        _18350 = 0x004A,
        /// <summary>18500 value.</summary>
        _18500 = 0x004B,
        /// <summary>18650 value.</summary>
        _18650 = 0x004C,
        /// <summary>19670 value.</summary>
        _19670 = 0x004D,
        /// <summary>25500 value.</summary>
        _25500 = 0x004E,
        /// <summary>26650 value.</summary>
        _26650 = 0x004F,
        /// <summary>32600 value.</summary>
        _32600 = 0x0050,
    }

    /// <summary>BatApprovedChemistryEnum enum values.</summary>
    public enum BatApprovedChemistryEnum : ushort
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x0000,
        /// <summary>Alkaline value.</summary>
        Alkaline = 0x0001,
        /// <summary>LithiumCarbonFluoride value.</summary>
        LithiumCarbonFluoride = 0x0002,
        /// <summary>LithiumChromiumOxide value.</summary>
        LithiumChromiumOxide = 0x0003,
        /// <summary>LithiumCopperOxide value.</summary>
        LithiumCopperOxide = 0x0004,
        /// <summary>LithiumIronDisulfide value.</summary>
        LithiumIronDisulfide = 0x0005,
        /// <summary>LithiumManganeseDioxide value.</summary>
        LithiumManganeseDioxide = 0x0006,
        /// <summary>LithiumThionylChloride value.</summary>
        LithiumThionylChloride = 0x0007,
        /// <summary>Magnesium value.</summary>
        Magnesium = 0x0008,
        /// <summary>MercuryOxide value.</summary>
        MercuryOxide = 0x0009,
        /// <summary>NickelOxyhydride value.</summary>
        NickelOxyhydride = 0x000A,
        /// <summary>SilverOxide value.</summary>
        SilverOxide = 0x000B,
        /// <summary>ZincAir value.</summary>
        ZincAir = 0x000C,
        /// <summary>ZincCarbon value.</summary>
        ZincCarbon = 0x000D,
        /// <summary>ZincChloride value.</summary>
        ZincChloride = 0x000E,
        /// <summary>ZincManganeseDioxide value.</summary>
        ZincManganeseDioxide = 0x000F,
        /// <summary>LeadAcid value.</summary>
        LeadAcid = 0x0010,
        /// <summary>LithiumCobaltOxide value.</summary>
        LithiumCobaltOxide = 0x0011,
        /// <summary>LithiumIon value.</summary>
        LithiumIon = 0x0012,
        /// <summary>LithiumIonPolymer value.</summary>
        LithiumIonPolymer = 0x0013,
        /// <summary>LithiumIronPhosphate value.</summary>
        LithiumIronPhosphate = 0x0014,
        /// <summary>LithiumSulfur value.</summary>
        LithiumSulfur = 0x0015,
        /// <summary>LithiumTitanate value.</summary>
        LithiumTitanate = 0x0016,
        /// <summary>NickelCadmium value.</summary>
        NickelCadmium = 0x0017,
        /// <summary>NickelHydrogen value.</summary>
        NickelHydrogen = 0x0018,
        /// <summary>NickelIron value.</summary>
        NickelIron = 0x0019,
        /// <summary>NickelMetalHydride value.</summary>
        NickelMetalHydride = 0x001A,
        /// <summary>NickelZinc value.</summary>
        NickelZinc = 0x001B,
        /// <summary>SilverZinc value.</summary>
        SilverZinc = 0x001C,
        /// <summary>SodiumIon value.</summary>
        SodiumIon = 0x001D,
        /// <summary>SodiumSulfur value.</summary>
        SodiumSulfur = 0x001E,
        /// <summary>ZincBromide value.</summary>
        ZincBromide = 0x001F,
        /// <summary>ZincCerium value.</summary>
        ZincCerium = 0x0020,
    }

    /// <summary>WiredFaultChangeType struct.</summary>
    public sealed class WiredFaultChangeType
    {
        /// <summary>Gets or sets current.</summary>
        public WiredFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets previous.</summary>
        public WiredFaultEnum[] Previous { get; set; } = default!;
    }

    /// <summary>BatFaultChangeType struct.</summary>
    public sealed class BatFaultChangeType
    {
        /// <summary>Gets or sets current.</summary>
        public BatFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets previous.</summary>
        public BatFaultEnum[] Previous { get; set; } = default!;
    }

    /// <summary>BatChargeFaultChangeType struct.</summary>
    public sealed class BatChargeFaultChangeType
    {
        /// <summary>Gets or sets current.</summary>
        public BatChargeFaultEnum[] Current { get; set; } = default!;
        /// <summary>Gets or sets previous.</summary>
        public BatChargeFaultEnum[] Previous { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteWiredFaultChangeType(MatterTLV tlv, byte tag, WiredFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteWiredFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteWiredFaultChangeType(MatterTLV tlv, WiredFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteWiredFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteWiredFaultChangeTypeFields(MatterTLV tlv, WiredFaultChangeType value)
    {
        if (value.Current != null) { tlv.AddArray(0); foreach (var item in value.Current) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
        if (value.Previous != null) { tlv.AddArray(1); foreach (var item in value.Previous) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
    }

    private static void WriteBatFaultChangeType(MatterTLV tlv, byte tag, BatFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteBatFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBatFaultChangeType(MatterTLV tlv, BatFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteBatFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBatFaultChangeTypeFields(MatterTLV tlv, BatFaultChangeType value)
    {
        if (value.Current != null) { tlv.AddArray(0); foreach (var item in value.Current) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
        if (value.Previous != null) { tlv.AddArray(1); foreach (var item in value.Previous) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
    }

    private static void WriteBatChargeFaultChangeType(MatterTLV tlv, byte tag, BatChargeFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteBatChargeFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBatChargeFaultChangeType(MatterTLV tlv, BatChargeFaultChangeType value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteBatChargeFaultChangeTypeFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteBatChargeFaultChangeTypeFields(MatterTLV tlv, BatChargeFaultChangeType value)
    {
        if (value.Current != null) { tlv.AddArray(0); foreach (var item in value.Current) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
        if (value.Previous != null) { tlv.AddArray(1); foreach (var item in value.Previous) { tlv.AddUInt8((byte)item); } tlv.EndContainer(); }
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>Status (0x0000).</summary>
        public const uint Status = 0x0000;
        /// <summary>Order (0x0001).</summary>
        public const uint Order = 0x0001;
        /// <summary>Description (0x0002).</summary>
        public const uint Description = 0x0002;
        /// <summary>WiredAssessedInputVoltage (0x0003).</summary>
        public const uint WiredAssessedInputVoltage = 0x0003;
        /// <summary>WiredAssessedInputFrequency (0x0004).</summary>
        public const uint WiredAssessedInputFrequency = 0x0004;
        /// <summary>WiredCurrentType (0x0005).</summary>
        public const uint WiredCurrentType = 0x0005;
        /// <summary>WiredAssessedCurrent (0x0006).</summary>
        public const uint WiredAssessedCurrent = 0x0006;
        /// <summary>WiredNominalVoltage (0x0007).</summary>
        public const uint WiredNominalVoltage = 0x0007;
        /// <summary>WiredMaximumCurrent (0x0008).</summary>
        public const uint WiredMaximumCurrent = 0x0008;
        /// <summary>WiredPresent (0x0009).</summary>
        public const uint WiredPresent = 0x0009;
        /// <summary>ActiveWiredFaults (0x000A).</summary>
        public const uint ActiveWiredFaults = 0x000A;
        /// <summary>BatVoltage (0x000B).</summary>
        public const uint BatVoltage = 0x000B;
        /// <summary>BatPercentRemaining (0x000C).</summary>
        public const uint BatPercentRemaining = 0x000C;
        /// <summary>BatTimeRemaining (0x000D).</summary>
        public const uint BatTimeRemaining = 0x000D;
        /// <summary>BatChargeLevel (0x000E).</summary>
        public const uint BatChargeLevel = 0x000E;
        /// <summary>BatReplacementNeeded (0x000F).</summary>
        public const uint BatReplacementNeeded = 0x000F;
        /// <summary>BatReplaceability (0x0010).</summary>
        public const uint BatReplaceability = 0x0010;
        /// <summary>BatPresent (0x0011).</summary>
        public const uint BatPresent = 0x0011;
        /// <summary>ActiveBatFaults (0x0012).</summary>
        public const uint ActiveBatFaults = 0x0012;
        /// <summary>BatReplacementDescription (0x0013).</summary>
        public const uint BatReplacementDescription = 0x0013;
        /// <summary>BatCommonDesignation (0x0014).</summary>
        public const uint BatCommonDesignation = 0x0014;
        /// <summary>BatANSIDesignation (0x0015).</summary>
        public const uint BatANSIDesignation = 0x0015;
        /// <summary>BatIECDesignation (0x0016).</summary>
        public const uint BatIECDesignation = 0x0016;
        /// <summary>BatApprovedChemistry (0x0017).</summary>
        public const uint BatApprovedChemistry = 0x0017;
        /// <summary>BatCapacity (0x0018).</summary>
        public const uint BatCapacity = 0x0018;
        /// <summary>BatQuantity (0x0019).</summary>
        public const uint BatQuantity = 0x0019;
        /// <summary>BatChargeState (0x001A).</summary>
        public const uint BatChargeState = 0x001A;
        /// <summary>BatTimeToFullCharge (0x001B).</summary>
        public const uint BatTimeToFullCharge = 0x001B;
        /// <summary>BatFunctionalWhileCharging (0x001C).</summary>
        public const uint BatFunctionalWhileCharging = 0x001C;
        /// <summary>BatChargingCurrent (0x001D).</summary>
        public const uint BatChargingCurrent = 0x001D;
        /// <summary>ActiveBatChargeFaults (0x001E).</summary>
        public const uint ActiveBatChargeFaults = 0x001E;
        /// <summary>EndpointList (0x001F).</summary>
        public const uint EndpointList = 0x001F;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>WiredFaultChange (0x0000).</summary>
        public const uint WiredFaultChange = 0x0000;
        /// <summary>BatFaultChange (0x0001).</summary>
        public const uint BatFaultChange = 0x0001;
        /// <summary>BatChargeFaultChange (0x0002).</summary>
        public const uint BatChargeFaultChange = 0x0002;
    }

    // Attribute readers

    /// <summary>Read Status attribute (0x0000).</summary>
    public Task<PowerSourceStatusEnum> ReadStatusAsync(CancellationToken ct = default)
        => ReadAttributeAsync<PowerSourceStatusEnum>(0x0000, ct);

    /// <summary>Read Order attribute (0x0001).</summary>
    public Task<byte> ReadOrderAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read Description attribute (0x0002).</summary>
    public Task<string?> ReadDescriptionAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0002, ct);

    /// <summary>Read WiredAssessedInputVoltage attribute (0x0003).</summary>
    public Task<uint?> ReadWiredAssessedInputVoltageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0003, ct);

    /// <summary>Read WiredAssessedInputFrequency attribute (0x0004).</summary>
    public Task<ushort?> ReadWiredAssessedInputFrequencyAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0004, ct);

    /// <summary>Read WiredCurrentType attribute (0x0005).</summary>
    public Task<WiredCurrentTypeEnum> ReadWiredCurrentTypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<WiredCurrentTypeEnum>(0x0005, ct);

    /// <summary>Read WiredAssessedCurrent attribute (0x0006).</summary>
    public Task<uint?> ReadWiredAssessedCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0006, ct);

    /// <summary>Read WiredNominalVoltage attribute (0x0007).</summary>
    public Task<uint> ReadWiredNominalVoltageAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0007, ct);

    /// <summary>Read WiredMaximumCurrent attribute (0x0008).</summary>
    public Task<uint> ReadWiredMaximumCurrentAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0008, ct);

    /// <summary>Read WiredPresent attribute (0x0009).</summary>
    public Task<bool> ReadWiredPresentAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0009, ct);

    /// <summary>Read ActiveWiredFaults attribute (0x000A).</summary>
    public Task<WiredFaultEnum[]?> ReadActiveWiredFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<WiredFaultEnum[]>(0x000A, ct);

    /// <summary>Read BatVoltage attribute (0x000B).</summary>
    public Task<uint?> ReadBatVoltageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x000B, ct);

    /// <summary>Read BatPercentRemaining attribute (0x000C).</summary>
    public Task<byte?> ReadBatPercentRemainingAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<byte>(0x000C, ct);

    /// <summary>Read BatTimeRemaining attribute (0x000D).</summary>
    public Task<uint?> ReadBatTimeRemainingAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x000D, ct);

    /// <summary>Read BatChargeLevel attribute (0x000E).</summary>
    public Task<BatChargeLevelEnum> ReadBatChargeLevelAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BatChargeLevelEnum>(0x000E, ct);

    /// <summary>Read BatReplacementNeeded attribute (0x000F).</summary>
    public Task<bool> ReadBatReplacementNeededAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x000F, ct);

    /// <summary>Read BatReplaceability attribute (0x0010).</summary>
    public Task<BatReplaceabilityEnum> ReadBatReplaceabilityAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BatReplaceabilityEnum>(0x0010, ct);

    /// <summary>Read BatPresent attribute (0x0011).</summary>
    public Task<bool> ReadBatPresentAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x0011, ct);

    /// <summary>Read ActiveBatFaults attribute (0x0012).</summary>
    public Task<BatFaultEnum[]?> ReadActiveBatFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<BatFaultEnum[]>(0x0012, ct);

    /// <summary>Read BatReplacementDescription attribute (0x0013).</summary>
    public Task<string?> ReadBatReplacementDescriptionAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0013, ct);

    /// <summary>Read BatCommonDesignation attribute (0x0014).</summary>
    public Task<BatCommonDesignationEnum> ReadBatCommonDesignationAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BatCommonDesignationEnum>(0x0014, ct);

    /// <summary>Read BatANSIDesignation attribute (0x0015).</summary>
    public Task<string?> ReadBatANSIDesignationAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0015, ct);

    /// <summary>Read BatIECDesignation attribute (0x0016).</summary>
    public Task<string?> ReadBatIECDesignationAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string>(0x0016, ct);

    /// <summary>Read BatApprovedChemistry attribute (0x0017).</summary>
    public Task<BatApprovedChemistryEnum> ReadBatApprovedChemistryAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BatApprovedChemistryEnum>(0x0017, ct);

    /// <summary>Read BatCapacity attribute (0x0018).</summary>
    public Task<uint> ReadBatCapacityAsync(CancellationToken ct = default)
        => ReadAttributeAsync<uint>(0x0018, ct);

    /// <summary>Read BatQuantity attribute (0x0019).</summary>
    public Task<byte> ReadBatQuantityAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0019, ct);

    /// <summary>Read BatChargeState attribute (0x001A).</summary>
    public Task<BatChargeStateEnum> ReadBatChargeStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<BatChargeStateEnum>(0x001A, ct);

    /// <summary>Read BatTimeToFullCharge attribute (0x001B).</summary>
    public Task<uint?> ReadBatTimeToFullChargeAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x001B, ct);

    /// <summary>Read BatFunctionalWhileCharging attribute (0x001C).</summary>
    public Task<bool> ReadBatFunctionalWhileChargingAsync(CancellationToken ct = default)
        => ReadAttributeAsync<bool>(0x001C, ct);

    /// <summary>Read BatChargingCurrent attribute (0x001D).</summary>
    public Task<uint?> ReadBatChargingCurrentAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x001D, ct);

    /// <summary>Read ActiveBatChargeFaults attribute (0x001E).</summary>
    public Task<BatChargeFaultEnum[]?> ReadActiveBatChargeFaultsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<BatChargeFaultEnum[]>(0x001E, ct);

    /// <summary>Read EndpointList attribute (0x001F).</summary>
    public Task<ushort[]?> ReadEndpointListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<ushort[]>(0x001F, ct);
}
