// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: pwm-cluster.xml
// Cluster: Pulse Width Modulation (0x001C)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Pulse Width Modulation (0x001C, rev 1)</summary>
public class PulseWidthModulationCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x001C;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="PulseWidthModulationCluster"/> bound to the given session and endpoint.</summary>
    public PulseWidthModulationCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }
}
