// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: refrigerator-alarm.xml
// Cluster: Refrigerator Alarm (0x0057)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Refrigerator Alarm (0x0057, rev 1)</summary>
public class RefrigeratorAlarmCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0057;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="RefrigeratorAlarmCluster"/> bound to the given session and endpoint.</summary>
    public RefrigeratorAlarmCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>AlarmBitmap bitmap flags.</summary>
    [System.Flags]
    public enum AlarmBitmap : uint
    {
        /// <summary>DoorOpen flag.</summary>
        DoorOpen = 1u << 0,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>Mask (0x0000).</summary>
        public const uint Mask = 0x0000;
        /// <summary>State (0x0002).</summary>
        public const uint State = 0x0002;
        /// <summary>Supported (0x0003).</summary>
        public const uint Supported = 0x0003;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>Notify (0x0000).</summary>
        public const uint Notify = 0x0000;
    }

    // Attribute readers

    /// <summary>Read Mask attribute (0x0000).</summary>
    public Task<AlarmBitmap> ReadMaskAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmBitmap>(0x0000, ct);

    /// <summary>Read State attribute (0x0002).</summary>
    public Task<AlarmBitmap> ReadStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmBitmap>(0x0002, ct);

    /// <summary>Read Supported attribute (0x0003).</summary>
    public Task<AlarmBitmap> ReadSupportedAsync(CancellationToken ct = default)
        => ReadAttributeAsync<AlarmBitmap>(0x0003, ct);
}
