// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: rvc-clean-mode-cluster.xml
// Cluster: RVC Clean Mode (0x0055)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>RVC Clean Mode (0x0055, rev 5)</summary>
public class RVCCleanModeCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0055;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="RVCCleanModeCluster"/> bound to the given session and endpoint.</summary>
    public RVCCleanModeCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Cluster supports changing clean modes from non-Idle states</summary>
        DirectModeChange = 1u << 20,
    }

    /// <summary>StatusCode enum values.</summary>
    public enum StatusCode : byte
    {
        /// <summary>CleaningInProgress value.</summary>
        CleaningInProgress = 0x40,
    }

    /// <summary>ModeTag enum values.</summary>
    public enum ModeTag : ushort
    {
        /// <summary>Auto value.</summary>
        Auto = 0x0000,
        /// <summary>Quick value.</summary>
        Quick = 0x0001,
        /// <summary>Quiet value.</summary>
        Quiet = 0x0002,
        /// <summary>LowNoise value.</summary>
        LowNoise = 0x0003,
        /// <summary>LowEnergy value.</summary>
        LowEnergy = 0x0004,
        /// <summary>Vacation value.</summary>
        Vacation = 0x0005,
        /// <summary>Min value.</summary>
        Min = 0x0006,
        /// <summary>Max value.</summary>
        Max = 0x0007,
        /// <summary>Night value.</summary>
        Night = 0x0008,
        /// <summary>Day value.</summary>
        Day = 0x0009,
        /// <summary>DeepClean value.</summary>
        DeepClean = 0x4000,
        /// <summary>Vacuum value.</summary>
        Vacuum = 0x4001,
        /// <summary>Mop value.</summary>
        Mop = 0x4002,
        /// <summary>Vacuum then Mop value.</summary>
        VacuumThenMop = 0x4003,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>SupportedModes (0x0000).</summary>
        public const uint SupportedModes = 0x0000;
        /// <summary>CurrentMode (0x0001).</summary>
        public const uint CurrentMode = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>ChangeToMode (0x0000).</summary>
        public const uint ChangeToMode = 0x0000;
    }

    // Async command methods

    /// <summary>Send ChangeToMode command (0x0000).</summary>
    public Task<InvokeResponse> ChangeToModeAsync(
        byte newMode,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { tlv.AddUInt8(0, newMode); }, ct);

    // Attribute readers

    /// <summary>Read SupportedModes attribute (0x0000).</summary>
    public Task<object[]?> ReadSupportedModesAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<object[]>(0x0000, ct);

    /// <summary>Read CurrentMode attribute (0x0001).</summary>
    public Task<byte> ReadCurrentModeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);
}
