// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: operational-state-rvc-cluster.xml
// Cluster: RVC Operational State (0x0061)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>RVC Operational State (0x0061, rev 1)</summary>
public class RVCOperationalStateCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0061;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="RVCOperationalStateCluster"/> bound to the given session and endpoint.</summary>
    public RVCOperationalStateCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>OperationalStateEnum enum values.</summary>
    public enum OperationalStateEnum : byte
    {
        /// <summary>Stopped value.</summary>
        Stopped = 0x00,
        /// <summary>Running value.</summary>
        Running = 0x01,
        /// <summary>Paused value.</summary>
        Paused = 0x02,
        /// <summary>Error value.</summary>
        Error = 0x03,
        /// <summary>SeekingCharger value.</summary>
        SeekingCharger = 0x40,
        /// <summary>Charging value.</summary>
        Charging = 0x41,
        /// <summary>Docked value.</summary>
        Docked = 0x42,
        /// <summary>EmptyingDustBin value.</summary>
        EmptyingDustBin = 0x43,
        /// <summary>CleaningMop value.</summary>
        CleaningMop = 0x44,
        /// <summary>FillingWaterTank value.</summary>
        FillingWaterTank = 0x45,
        /// <summary>UpdatingMaps value.</summary>
        UpdatingMaps = 0x46,
    }

    /// <summary>ErrorStateEnum enum values.</summary>
    public enum ErrorStateEnum : byte
    {
        /// <summary>NoError value.</summary>
        NoError = 0x00,
        /// <summary>UnableToStartOrResume value.</summary>
        UnableToStartOrResume = 0x01,
        /// <summary>UnableToCompleteOperation value.</summary>
        UnableToCompleteOperation = 0x02,
        /// <summary>CommandInvalidInState value.</summary>
        CommandInvalidInState = 0x03,
        /// <summary>FailedToFindChargingDock value.</summary>
        FailedToFindChargingDock = 0x40,
        /// <summary>Stuck value.</summary>
        Stuck = 0x41,
        /// <summary>DustBinMissing value.</summary>
        DustBinMissing = 0x42,
        /// <summary>DustBinFull value.</summary>
        DustBinFull = 0x43,
        /// <summary>WaterTankEmpty value.</summary>
        WaterTankEmpty = 0x44,
        /// <summary>WaterTankMissing value.</summary>
        WaterTankMissing = 0x45,
        /// <summary>WaterTankLidOpen value.</summary>
        WaterTankLidOpen = 0x46,
        /// <summary>MopCleaningPadMissing value.</summary>
        MopCleaningPadMissing = 0x47,
        /// <summary>LowBattery value.</summary>
        LowBattery = 0x48,
        /// <summary>CannotReachTargetArea value.</summary>
        CannotReachTargetArea = 0x49,
        /// <summary>DirtyWaterTankFull value.</summary>
        DirtyWaterTankFull = 0x4A,
        /// <summary>DirtyWaterTankMissing value.</summary>
        DirtyWaterTankMissing = 0x4B,
        /// <summary>WheelsJammed value.</summary>
        WheelsJammed = 0x4C,
        /// <summary>BrushJammed value.</summary>
        BrushJammed = 0x4D,
        /// <summary>NavigationSensorObscured value.</summary>
        NavigationSensorObscured = 0x4E,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>PhaseList (0x0000).</summary>
        public const uint PhaseList = 0x0000;
        /// <summary>CurrentPhase (0x0001).</summary>
        public const uint CurrentPhase = 0x0001;
        /// <summary>CountdownTime (0x0002).</summary>
        public const uint CountdownTime = 0x0002;
        /// <summary>OperationalStateList (0x0003).</summary>
        public const uint OperationalStateList = 0x0003;
        /// <summary>OperationalState (0x0004).</summary>
        public const uint OperationalState = 0x0004;
        /// <summary>OperationalError (0x0005).</summary>
        public const uint OperationalError = 0x0005;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>Pause (0x0000).</summary>
        public const uint Pause = 0x0000;
        /// <summary>Resume (0x0003).</summary>
        public const uint Resume = 0x0003;
        /// <summary>GoHome (0x0080).</summary>
        public const uint GoHome = 0x0080;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>OperationalError (0x0000).</summary>
        public const uint OperationalError = 0x0000;
        /// <summary>OperationCompletion (0x0001).</summary>
        public const uint OperationCompletion = 0x0001;
    }

    // Async command methods

    /// <summary>Send Pause command (0x0000).</summary>
    public Task<InvokeResponse> PauseAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    /// <summary>Send Resume command (0x0003).</summary>
    public Task<InvokeResponse> ResumeAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, ct: ct);

    /// <summary>Send GoHome command (0x0080).</summary>
    public Task<InvokeResponse> GoHomeAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0080, ct: ct);

    // Attribute readers

    /// <summary>Read PhaseList attribute (0x0000).</summary>
    public Task<string[]?> ReadPhaseListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string[]>(0x0000, ct);

    /// <summary>Read CurrentPhase attribute (0x0001).</summary>
    public Task<byte?> ReadCurrentPhaseAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read CountdownTime attribute (0x0002).</summary>
    public Task<uint?> ReadCountdownTimeAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0002, ct);

    /// <summary>Read OperationalStateList attribute (0x0003).</summary>
    public Task<object[]?> ReadOperationalStateListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<object[]>(0x0003, ct);

    /// <summary>Read OperationalState attribute (0x0004).</summary>
    public Task<byte> ReadOperationalStateAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0004, ct);

    /// <summary>Read OperationalError attribute (0x0005).</summary>
    public Task<object?> ReadOperationalErrorAsync(CancellationToken ct = default)
        => ReadAttributeAsync(0x0005, ct);
}
