// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: sample-mei-cluster.xml
// Cluster: Sample MEI (0xFFF1FC20)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Sample MEI (0xFFF1FC20, rev 1)</summary>
public class SampleMEICluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0xFFF1FC20;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="SampleMEICluster"/> bound to the given session and endpoint.</summary>
    public SampleMEICluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>AddArguments (0x0002).</summary>
        public const uint AddArguments = 0x0002;
        /// <summary>Ping (0x0000).</summary>
        public const uint Ping = 0x0000;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>PingCountEvent (0x0000).</summary>
        public const uint PingCountEvent = 0x0000;
    }

    /// <summary>Base type for this cluster's event reports.</summary>
    public abstract class ClusterEvent
        : MatterClusterEvent
    {
        /// <summary>Initializes a new cluster event wrapper.</summary>
        protected ClusterEvent(MatterEventReport report, string eventName)
            : base(report, "Sample MEI", eventName) { }
    }

    /// <summary>Fallback event wrapper when DotMatter cannot parse a typed payload.</summary>
    public sealed class UnknownClusterEvent(MatterEventReport report, string? reason = null)
        : ClusterEvent(report, "Unknown")
    {
        /// <summary>Gets the reason the typed payload parser could not materialize this event.</summary>
        public override string? Reason { get; } = reason;
    }

    /// <summary>PingCountEvent event payload.</summary>
    public sealed class PingCountEventEventData
    {
        /// <summary>Gets or sets count.</summary>
        public uint Count { get; set; }
    }

    /// <summary>PingCountEvent event report.</summary>
    public sealed class PingCountEventEvent(MatterEventReport report, PingCountEventEventData payload)
        : ClusterEvent(report, "PingCountEvent")
    {
        /// <summary>Gets the typed PingCountEvent payload.</summary>
        public PingCountEventEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    // Async command methods

    /// <summary>Send AddArguments command (0x0002).</summary>
    public Task<InvokeResponse> AddArgumentsAsync(
        byte arg1,
        byte arg2,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv =>
        {
            tlv.AddUInt8(0, arg1);
            tlv.AddUInt8(1, arg2);
        }, ct);

    /// <summary>Send Ping command (0x0000).</summary>
    public Task<InvokeResponse> PingAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    // Event payload parsers

    private static PingCountEventEventData ReadPingCountEventEventData(MatterTLV tlv)
    {
        var value = new PingCountEventEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 1:
                    value.Count = tlv.GetUnsignedIntAny(1);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadPingCountEventEventData(MatterEventReport report, out PingCountEventEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadPingCountEventEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "PingCountEvent payload parse failed: " + ex.Message;
            return false;
        }
    }

    // Event payload JSON projectors

    private static JsonObject CreatePingCountEventEventDataJson(PingCountEventEventData value)
    {
        var json = new JsonObject();
        json["count"] = CreateJsonValue(value.Count);
        return json;
    }

    internal static JsonObject? MapEventPayloadJson(ClusterEvent evt)
    {
        return evt switch
        {
            PingCountEventEvent typed => CreatePingCountEventEventDataJson(typed.Payload),
            _ => null,
        };
    }

    // Event readers and subscriptions

    /// <summary>Read event reports from this cluster.</summary>
    public async Task<ClusterEvent[]> ReadEventsAsync(
        uint[]? eventIds = null,
        bool fabricFiltered = false,
        CancellationToken ct = default)
    {
        var events = await ReadEventsAsync(MapEventReports, eventIds, fabricFiltered, ct);
        return [.. events];
    }

    /// <summary>Subscribe to event reports from this cluster.</summary>
    public Task<MatterEventSubscription<ClusterEvent>> SubscribeEventsAsync(
        uint[]? eventIds = null,
        ushort minInterval = 1,
        ushort maxInterval = 60,
        bool fabricFiltered = false,
        CancellationToken ct = default)
        => SubscribeEventsAsync(MapEventReports, eventIds, minInterval, maxInterval, fabricFiltered, ct);

    internal static ClusterEvent[] MapEventReports(IReadOnlyList<MatterEventReport> reports)
    {
        if (reports.Count == 0)
        {
            return [];
        }

        var events = new List<ClusterEvent>(reports.Count);
        foreach (var report in reports)
        {
            events.Add(MapEventReport(report));
        }

        return [.. events];
    }

    internal static ClusterEvent MapEventReport(MatterEventReport report)
    {
        return report.EventId switch
        {
            Events.PingCountEvent when TryReadPingCountEventEventData(report, out var pingCountEventEventData, out _) => new PingCountEventEvent(report, pingCountEventEventData!),
            Events.PingCountEvent when TryReadPingCountEventEventData(report, out _, out var pingCountEventReason) => new UnknownClusterEvent(report, pingCountEventReason),
            _ => new UnknownClusterEvent(report, "Event ID is not recognized by this cluster."),
        };
    }
}
