// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: scene.xml
// Cluster: Scenes Management (0x0062)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Scenes Management (0x0062, rev 1)</summary>
public class ScenesManagementCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0062;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="ScenesManagementCluster"/> bound to the given session and endpoint.</summary>
    public ScenesManagementCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>The ability to store a name for a scene.</summary>
        SceneNames = 1u << 0,
    }

    /// <summary>CopyModeBitmap bitmap flags.</summary>
    [System.Flags]
    public enum CopyModeBitmap : uint
    {
        /// <summary>CopyAllScenes flag.</summary>
        CopyAllScenes = 1u << 0,
    }

    /// <summary>SceneInfoStruct struct.</summary>
    public sealed class SceneInfoStruct
    {
        /// <summary>Gets or sets SceneCount.</summary>
        public byte SceneCount { get; set; }
        /// <summary>Gets or sets CurrentScene.</summary>
        public byte CurrentScene { get; set; }
        /// <summary>Gets or sets CurrentGroup.</summary>
        public ushort CurrentGroup { get; set; }
        /// <summary>Gets or sets SceneValid.</summary>
        public bool SceneValid { get; set; }
        /// <summary>Gets or sets RemainingCapacity.</summary>
        public byte RemainingCapacity { get; set; }
        /// <summary>Gets or sets FabricIndex.</summary>
        public byte FabricIndex { get; set; }
    }

    /// <summary>AttributeValuePairStruct struct.</summary>
    public sealed class AttributeValuePairStruct
    {
        /// <summary>Gets or sets AttributeID.</summary>
        public uint AttributeID { get; set; }
        /// <summary>Gets or sets ValueUnsigned8.</summary>
        public byte? ValueUnsigned8 { get; set; }
        /// <summary>Gets or sets ValueSigned8.</summary>
        public sbyte? ValueSigned8 { get; set; }
        /// <summary>Gets or sets ValueUnsigned16.</summary>
        public ushort? ValueUnsigned16 { get; set; }
        /// <summary>Gets or sets ValueSigned16.</summary>
        public short? ValueSigned16 { get; set; }
        /// <summary>Gets or sets ValueUnsigned32.</summary>
        public uint? ValueUnsigned32 { get; set; }
        /// <summary>Gets or sets ValueSigned32.</summary>
        public int? ValueSigned32 { get; set; }
        /// <summary>Gets or sets ValueUnsigned64.</summary>
        public ulong? ValueUnsigned64 { get; set; }
        /// <summary>Gets or sets ValueSigned64.</summary>
        public long? ValueSigned64 { get; set; }
    }

    /// <summary>ExtensionFieldSetStruct struct.</summary>
    public sealed class ExtensionFieldSetStruct
    {
        /// <summary>Gets or sets ClusterID.</summary>
        public uint ClusterID { get; set; }
        /// <summary>Gets or sets AttributeValueList.</summary>
        public AttributeValuePairStruct[] AttributeValueList { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteSceneInfoStruct(MatterTLV tlv, byte tag, SceneInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteSceneInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSceneInfoStruct(MatterTLV tlv, SceneInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteSceneInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteSceneInfoStructFields(MatterTLV tlv, SceneInfoStruct value)
    {
        tlv.AddUInt8(0, value.SceneCount);
        tlv.AddUInt8(1, value.CurrentScene);
        tlv.AddUInt16(2, value.CurrentGroup);
        tlv.AddBool(3, value.SceneValid);
        tlv.AddUInt8(4, value.RemainingCapacity);
    }

    private static void WriteAttributeValuePairStruct(MatterTLV tlv, byte tag, AttributeValuePairStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteAttributeValuePairStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAttributeValuePairStruct(MatterTLV tlv, AttributeValuePairStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteAttributeValuePairStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteAttributeValuePairStructFields(MatterTLV tlv, AttributeValuePairStruct value)
    {
        tlv.AddUInt32(0, value.AttributeID);
        if (value.ValueUnsigned8 != null) tlv.AddUInt8(1, value.ValueUnsigned8.Value);
        if (value.ValueSigned8 != null) tlv.AddInt8(2, value.ValueSigned8.Value);
        if (value.ValueUnsigned16 != null) tlv.AddUInt16(3, value.ValueUnsigned16.Value);
        if (value.ValueSigned16 != null) tlv.AddInt16(4, value.ValueSigned16.Value);
        if (value.ValueUnsigned32 != null) tlv.AddUInt32(5, value.ValueUnsigned32.Value);
        if (value.ValueSigned32 != null) tlv.AddInt32(6, value.ValueSigned32.Value);
        if (value.ValueUnsigned64 != null) tlv.AddUInt64(7, value.ValueUnsigned64.Value);
        if (value.ValueSigned64 != null) tlv.AddInt64(8, value.ValueSigned64.Value);
    }

    private static void WriteExtensionFieldSetStruct(MatterTLV tlv, byte tag, ExtensionFieldSetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteExtensionFieldSetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteExtensionFieldSetStruct(MatterTLV tlv, ExtensionFieldSetStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteExtensionFieldSetStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteExtensionFieldSetStructFields(MatterTLV tlv, ExtensionFieldSetStruct value)
    {
        tlv.AddUInt32(0, value.ClusterID);
        if (value.AttributeValueList != null) { tlv.AddArray(1); foreach (var item in value.AttributeValueList) { WriteAttributeValuePairStruct(tlv, item); } tlv.EndContainer(); }
    }

    // TLV struct deserializers

    private static SceneInfoStruct ReadSceneInfoStruct(MatterTLV tlv)
        => ReadSceneInfoStruct(tlv, null);

    private static SceneInfoStruct ReadSceneInfoStruct(MatterTLV tlv, int? tag)
    {
        var value = new SceneInfoStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.SceneCount = (byte)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.CurrentScene = (byte)tlv.GetUnsignedIntAny(1);
                    break;
                case 2:
                    value.CurrentGroup = (ushort)tlv.GetUnsignedIntAny(2);
                    break;
                case 3:
                    value.SceneValid = tlv.GetBoolean(3);
                    break;
                case 4:
                    value.RemainingCapacity = (byte)tlv.GetUnsignedIntAny(4);
                    break;
                case 254:
                    value.FabricIndex = (byte)tlv.GetUnsignedIntAny(254);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static AttributeValuePairStruct ReadAttributeValuePairStruct(MatterTLV tlv)
        => ReadAttributeValuePairStruct(tlv, null);

    private static AttributeValuePairStruct ReadAttributeValuePairStruct(MatterTLV tlv, int? tag)
    {
        var value = new AttributeValuePairStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.AttributeID = tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    if (tlv.IsNextNull()) { tlv.GetNull(1); } else { value.ValueUnsigned8 = (byte)tlv.GetUnsignedIntAny(1); }
                    break;
                case 2:
                    if (tlv.IsNextNull()) { tlv.GetNull(2); } else { value.ValueSigned8 = (sbyte)tlv.GetSignedInt(2); }
                    break;
                case 3:
                    if (tlv.IsNextNull()) { tlv.GetNull(3); } else { value.ValueUnsigned16 = (ushort)tlv.GetUnsignedIntAny(3); }
                    break;
                case 4:
                    if (tlv.IsNextNull()) { tlv.GetNull(4); } else { value.ValueSigned16 = (short)tlv.GetSignedInt(4); }
                    break;
                case 5:
                    if (tlv.IsNextNull()) { tlv.GetNull(5); } else { value.ValueUnsigned32 = tlv.GetUnsignedIntAny(5); }
                    break;
                case 6:
                    if (tlv.IsNextNull()) { tlv.GetNull(6); } else { value.ValueSigned32 = (int)tlv.GetSignedInt(6); }
                    break;
                case 7:
                    if (tlv.IsNextNull()) { tlv.GetNull(7); } else { value.ValueUnsigned64 = tlv.GetUnsignedInt(7); }
                    break;
                case 8:
                    if (tlv.IsNextNull()) { tlv.GetNull(8); } else { value.ValueSigned64 = tlv.GetSignedInt(8); }
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static ExtensionFieldSetStruct ReadExtensionFieldSetStruct(MatterTLV tlv)
        => ReadExtensionFieldSetStruct(tlv, null);

    private static ExtensionFieldSetStruct ReadExtensionFieldSetStruct(MatterTLV tlv, int? tag)
    {
        var value = new ExtensionFieldSetStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ClusterID = tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    var items1 = new List<AttributeValuePairStruct>();
                    tlv.OpenArray(1);
                    while (!tlv.IsEndContainerNext())
                    {
                        items1.Add(ReadAttributeValuePairStruct(tlv));
                    }
                    tlv.CloseContainer();
                    value.AttributeValueList = [.. items1];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>SceneTableSize (0x0001).</summary>
        public const uint SceneTableSize = 0x0001;
        /// <summary>FabricSceneInfo (0x0002).</summary>
        public const uint FabricSceneInfo = 0x0002;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>AddScene (0x0000).</summary>
        public const uint AddScene = 0x0000;
        /// <summary>ViewScene (0x0001).</summary>
        public const uint ViewScene = 0x0001;
        /// <summary>RemoveScene (0x0002).</summary>
        public const uint RemoveScene = 0x0002;
        /// <summary>RemoveAllScenes (0x0003).</summary>
        public const uint RemoveAllScenes = 0x0003;
        /// <summary>StoreScene (0x0004).</summary>
        public const uint StoreScene = 0x0004;
        /// <summary>RecallScene (0x0005).</summary>
        public const uint RecallScene = 0x0005;
        /// <summary>GetSceneMembership (0x0006).</summary>
        public const uint GetSceneMembership = 0x0006;
        /// <summary>CopyScene (0x0040).</summary>
        public const uint CopyScene = 0x0040;
    }

    // Async command methods

    /// <summary>Send AddScene command (0x0000).</summary>
    public Task<InvokeResponse> AddSceneAsync(
        ushort groupID,
        byte sceneID,
        uint transitionTime,
        string sceneName,
        ExtensionFieldSetStruct[] extensionFieldSetStructs,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUInt8(1, sceneID);
            tlv.AddUInt32(2, transitionTime);
            tlv.AddUTF8String(3, sceneName);
            if (extensionFieldSetStructs != null) { tlv.AddArray(4); foreach (var item in extensionFieldSetStructs) { WriteExtensionFieldSetStruct(tlv, item); } tlv.EndContainer(); }
        }, ct);

    /// <summary>Send ViewScene command (0x0001).</summary>
    public Task<InvokeResponse> ViewSceneAsync(
        ushort groupID,
        byte sceneID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUInt8(1, sceneID);
        }, ct);

    /// <summary>Send RemoveScene command (0x0002).</summary>
    public Task<InvokeResponse> RemoveSceneAsync(
        ushort groupID,
        byte sceneID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUInt8(1, sceneID);
        }, ct);

    /// <summary>Send RemoveAllScenes command (0x0003).</summary>
    public Task<InvokeResponse> RemoveAllScenesAsync(
        ushort groupID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0003, tlv => { tlv.AddUInt16(0, groupID); }, ct);

    /// <summary>Send StoreScene command (0x0004).</summary>
    public Task<InvokeResponse> StoreSceneAsync(
        ushort groupID,
        byte sceneID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUInt8(1, sceneID);
        }, ct);

    /// <summary>Send RecallScene command (0x0005).</summary>
    public Task<InvokeResponse> RecallSceneAsync(
        ushort groupID,
        byte sceneID,
        uint? transitionTime = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv =>
        {
            tlv.AddUInt16(0, groupID);
            tlv.AddUInt8(1, sceneID);
            if (transitionTime != null) tlv.AddUInt32(2, transitionTime.Value);
        }, ct);

    /// <summary>Send GetSceneMembership command (0x0006).</summary>
    public Task<InvokeResponse> GetSceneMembershipAsync(
        ushort groupID,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0006, tlv => { tlv.AddUInt16(0, groupID); }, ct);

    /// <summary>Send CopyScene command (0x0040).</summary>
    public Task<InvokeResponse> CopySceneAsync(
        CopyModeBitmap mode,
        ushort groupIdentifierFrom,
        byte sceneIdentifierFrom,
        ushort groupIdentifierTo,
        byte sceneIdentifierTo,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0040, tlv =>
        {
            tlv.AddUInt8(0, (byte)mode);
            tlv.AddUInt16(1, groupIdentifierFrom);
            tlv.AddUInt8(2, sceneIdentifierFrom);
            tlv.AddUInt16(3, groupIdentifierTo);
            tlv.AddUInt8(4, sceneIdentifierTo);
        }, ct);

    // Attribute readers

    /// <summary>Read SceneTableSize attribute (0x0001).</summary>
    public Task<ushort> ReadSceneTableSizeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0001, ct);

    /// <summary>Read FabricSceneInfo attribute (0x0002).</summary>
    public Task<SceneInfoStruct[]?> ReadFabricSceneInfoAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0002, ReadSceneInfoStruct, ct);
}
