// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: switch-cluster.xml
// Cluster: Switch (0x003B)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Switch (0x003B, rev 2)</summary>
public class SwitchCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x003B;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="SwitchCluster"/> bound to the given session and endpoint.</summary>
    public SwitchCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Switch is latching</summary>
        LatchingSwitch = 1u << 0,
        /// <summary>Switch is momentary</summary>
        MomentarySwitch = 1u << 1,
        /// <summary>Switch supports release events generation</summary>
        MomentarySwitchRelease = 1u << 2,
        /// <summary>Switch supports long press detection</summary>
        MomentarySwitchLongPress = 1u << 3,
        /// <summary>Switch supports multi-press detection</summary>
        MomentarySwitchMultiPress = 1u << 4,
        /// <summary>Switch is momentary, targeted at specific user actions (focus on multi-press and optionally long press) with a reduced event generation scheme</summary>
        ActionSwitch = 1u << 5,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>NumberOfPositions (0x0000).</summary>
        public const uint NumberOfPositions = 0x0000;
        /// <summary>CurrentPosition (0x0001).</summary>
        public const uint CurrentPosition = 0x0001;
        /// <summary>MultiPressMax (0x0002).</summary>
        public const uint MultiPressMax = 0x0002;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>SwitchLatched (0x0000).</summary>
        public const uint SwitchLatched = 0x0000;
        /// <summary>InitialPress (0x0001).</summary>
        public const uint InitialPress = 0x0001;
        /// <summary>LongPress (0x0002).</summary>
        public const uint LongPress = 0x0002;
        /// <summary>ShortRelease (0x0003).</summary>
        public const uint ShortRelease = 0x0003;
        /// <summary>LongRelease (0x0004).</summary>
        public const uint LongRelease = 0x0004;
        /// <summary>MultiPressOngoing (0x0005).</summary>
        public const uint MultiPressOngoing = 0x0005;
        /// <summary>MultiPressComplete (0x0006).</summary>
        public const uint MultiPressComplete = 0x0006;
    }

    // Attribute readers

    /// <summary>Read NumberOfPositions attribute (0x0000).</summary>
    public Task<byte> ReadNumberOfPositionsAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0000, ct);

    /// <summary>Read CurrentPosition attribute (0x0001).</summary>
    public Task<byte> ReadCurrentPositionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);

    /// <summary>Read MultiPressMax attribute (0x0002).</summary>
    public Task<byte> ReadMultiPressMaxAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0002, ct);
}
