// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: target-navigator-cluster.xml
// Cluster: Target Navigator (0x0505)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Target Navigator (0x0505, rev 2)</summary>
public class TargetNavigatorCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0505;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="TargetNavigatorCluster"/> bound to the given session and endpoint.</summary>
    public TargetNavigatorCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>StatusEnum enum values.</summary>
    public enum StatusEnum : byte
    {
        /// <summary>Success value.</summary>
        Success = 0x00,
        /// <summary>TargetNotFound value.</summary>
        TargetNotFound = 0x01,
        /// <summary>NotAllowed value.</summary>
        NotAllowed = 0x02,
    }

    /// <summary>TargetInfoStruct struct.</summary>
    public sealed class TargetInfoStruct
    {
        /// <summary>Gets or sets Identifier.</summary>
        public byte Identifier { get; set; }
        /// <summary>Gets or sets Name.</summary>
        public string Name { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteTargetInfoStruct(MatterTLV tlv, byte tag, TargetInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteTargetInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTargetInfoStruct(MatterTLV tlv, TargetInfoStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteTargetInfoStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteTargetInfoStructFields(MatterTLV tlv, TargetInfoStruct value)
    {
        tlv.AddUInt8(0, value.Identifier);
        tlv.AddUTF8String(1, value.Name);
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>TargetList (0x0000).</summary>
        public const uint TargetList = 0x0000;
        /// <summary>CurrentTarget (0x0001).</summary>
        public const uint CurrentTarget = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>NavigateTarget (0x0000).</summary>
        public const uint NavigateTarget = 0x0000;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>TargetUpdated (0x0000).</summary>
        public const uint TargetUpdated = 0x0000;
    }

    // Async command methods

    /// <summary>Send NavigateTarget command (0x0000).</summary>
    public Task<InvokeResponse> NavigateTargetAsync(
        byte target,
        string? data = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            tlv.AddUInt8(0, target);
            if (data != null) tlv.AddUTF8String(1, data);
        }, ct);

    // Attribute readers

    /// <summary>Read TargetList attribute (0x0000).</summary>
    public Task<TargetInfoStruct[]?> ReadTargetListAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<TargetInfoStruct[]>(0x0000, ct);

    /// <summary>Read CurrentTarget attribute (0x0001).</summary>
    public Task<byte> ReadCurrentTargetAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);
}
