// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: temperature-control-cluster.xml
// Cluster: Temperature Control (0x0056)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Temperature Control (0x0056, rev 1)</summary>
public class TemperatureControlCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0056;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="TemperatureControlCluster"/> bound to the given session and endpoint.</summary>
    public TemperatureControlCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Use actual temperature numbers</summary>
        TemperatureNumber = 1u << 0,
        /// <summary>Use temperature levels</summary>
        TemperatureLevel = 1u << 1,
        /// <summary>Use step control with temperature numbers</summary>
        TemperatureStep = 1u << 2,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>TemperatureSetpoint (0x0000).</summary>
        public const uint TemperatureSetpoint = 0x0000;
        /// <summary>MinTemperature (0x0001).</summary>
        public const uint MinTemperature = 0x0001;
        /// <summary>MaxTemperature (0x0002).</summary>
        public const uint MaxTemperature = 0x0002;
        /// <summary>Step (0x0003).</summary>
        public const uint Step = 0x0003;
        /// <summary>SelectedTemperatureLevel (0x0004).</summary>
        public const uint SelectedTemperatureLevel = 0x0004;
        /// <summary>SupportedTemperatureLevels (0x0005).</summary>
        public const uint SupportedTemperatureLevels = 0x0005;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>SetTemperature (0x0000).</summary>
        public const uint SetTemperature = 0x0000;
    }

    // Async command methods

    /// <summary>Send SetTemperature command (0x0000).</summary>
    public Task<InvokeResponse> SetTemperatureAsync(
        short? targetTemperature = default,
        byte? targetTemperatureLevel = default,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv =>
        {
            if (targetTemperature != null) tlv.AddInt16(0, targetTemperature.Value);
            if (targetTemperatureLevel != null) tlv.AddUInt8(1, targetTemperatureLevel.Value);
        }, ct);

    // Attribute readers

    /// <summary>Read TemperatureSetpoint attribute (0x0000).</summary>
    public Task<short> ReadTemperatureSetpointAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0000, ct);

    /// <summary>Read MinTemperature attribute (0x0001).</summary>
    public Task<short> ReadMinTemperatureAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0001, ct);

    /// <summary>Read MaxTemperature attribute (0x0002).</summary>
    public Task<short> ReadMaxTemperatureAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0002, ct);

    /// <summary>Read Step attribute (0x0003).</summary>
    public Task<short> ReadStepAsync(CancellationToken ct = default)
        => ReadAttributeAsync<short>(0x0003, ct);

    /// <summary>Read SelectedTemperatureLevel attribute (0x0004).</summary>
    public Task<byte> ReadSelectedTemperatureLevelAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0004, ct);

    /// <summary>Read SupportedTemperatureLevels attribute (0x0005).</summary>
    public Task<string[]?> ReadSupportedTemperatureLevelsAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<string[]>(0x0005, ct);
}
