// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: mode-base-cluster.xml (+1 merged XML file(s))
// Cluster: Water Heater Mode (0x009E)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Water Heater Mode (0x009E, rev 1)</summary>
public class WaterHeaterModeCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x009E;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="WaterHeaterModeCluster"/> bound to the given session and endpoint.</summary>
    public WaterHeaterModeCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Dependency with the OnOff cluster</summary>
        OnOff = 1u << 0,
    }

    /// <summary>ModeTag enum values.</summary>
    public enum ModeTag : ushort
    {
        /// <summary>Auto value.</summary>
        Auto = 0x0000,
        /// <summary>Quick value.</summary>
        Quick = 0x0001,
        /// <summary>Quiet value.</summary>
        Quiet = 0x0002,
        /// <summary>LowNoise value.</summary>
        LowNoise = 0x0003,
        /// <summary>LowEnergy value.</summary>
        LowEnergy = 0x0004,
        /// <summary>Vacation value.</summary>
        Vacation = 0x0005,
        /// <summary>Min value.</summary>
        Min = 0x0006,
        /// <summary>Max value.</summary>
        Max = 0x0007,
        /// <summary>Night value.</summary>
        Night = 0x0008,
        /// <summary>Day value.</summary>
        Day = 0x0009,
        /// <summary>Off value.</summary>
        Off = 0x4000,
        /// <summary>Manual value.</summary>
        Manual = 0x4001,
        /// <summary>Timed value.</summary>
        Timed = 0x4002,
    }

    /// <summary>ModeTagStruct struct.</summary>
    public sealed class ModeTagStruct
    {
        /// <summary>Gets or sets MfgCode.</summary>
        public ushort? MfgCode { get; set; }
        /// <summary>Gets or sets Value.</summary>
        public ushort Value { get; set; }
    }

    /// <summary>ModeOptionStruct struct.</summary>
    public sealed class ModeOptionStruct
    {
        /// <summary>Gets or sets Label.</summary>
        public string Label { get; set; } = default!;
        /// <summary>Gets or sets Mode.</summary>
        public byte Mode { get; set; }
        /// <summary>Gets or sets ModeTags.</summary>
        public ModeTagStruct[] ModeTags { get; set; } = default!;
    }

    // TLV struct serializers

    private static void WriteModeTagStruct(MatterTLV tlv, byte tag, ModeTagStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteModeTagStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteModeTagStruct(MatterTLV tlv, ModeTagStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteModeTagStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteModeTagStructFields(MatterTLV tlv, ModeTagStruct value)
    {
        if (value.MfgCode != null) tlv.AddUInt16(0, value.MfgCode.Value);
        tlv.AddUInt16(1, value.Value);
    }

    private static void WriteModeOptionStruct(MatterTLV tlv, byte tag, ModeOptionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure(tag);
        WriteModeOptionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteModeOptionStruct(MatterTLV tlv, ModeOptionStruct value)
    {
        ArgumentNullException.ThrowIfNull(value);
        tlv.AddStructure();
        WriteModeOptionStructFields(tlv, value);
        tlv.EndContainer();
    }

    private static void WriteModeOptionStructFields(MatterTLV tlv, ModeOptionStruct value)
    {
        tlv.AddUTF8String(0, value.Label);
        tlv.AddUInt8(1, value.Mode);
        if (value.ModeTags != null) { tlv.AddArray(2); foreach (var item in value.ModeTags) { WriteModeTagStruct(tlv, item); } tlv.EndContainer(); }
    }

    // TLV struct deserializers

    private static ModeTagStruct ReadModeTagStruct(MatterTLV tlv)
        => ReadModeTagStruct(tlv, null);

    private static ModeTagStruct ReadModeTagStruct(MatterTLV tlv, int? tag)
    {
        var value = new ModeTagStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    if (tlv.IsNextNull()) { tlv.GetNull(0); } else { value.MfgCode = (ushort)tlv.GetUnsignedIntAny(0); }
                    break;
                case 1:
                    value.Value = (ushort)tlv.GetUnsignedIntAny(1);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static ModeOptionStruct ReadModeOptionStruct(MatterTLV tlv)
        => ReadModeOptionStruct(tlv, null);

    private static ModeOptionStruct ReadModeOptionStruct(MatterTLV tlv, int? tag)
    {
        var value = new ModeOptionStruct();
        tlv.OpenStructure(tag);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.Label = tlv.GetUTF8String(0);
                    break;
                case 1:
                    value.Mode = (byte)tlv.GetUnsignedIntAny(1);
                    break;
                case 2:
                    var items2 = new List<ModeTagStruct>();
                    tlv.OpenArray(2);
                    while (!tlv.IsEndContainerNext())
                    {
                        items2.Add(ReadModeTagStruct(tlv));
                    }
                    tlv.CloseContainer();
                    value.ModeTags = [.. items2];
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>SupportedModes (0x0000).</summary>
        public const uint SupportedModes = 0x0000;
        /// <summary>CurrentMode (0x0001).</summary>
        public const uint CurrentMode = 0x0001;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>ChangeToMode (0x0000).</summary>
        public const uint ChangeToMode = 0x0000;
    }

    // Async command methods

    /// <summary>Send ChangeToMode command (0x0000).</summary>
    public Task<InvokeResponse> ChangeToModeAsync(
        byte newMode,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, tlv => { tlv.AddUInt8(0, newMode); }, ct);

    // Attribute readers

    /// <summary>Read SupportedModes attribute (0x0000).</summary>
    public Task<ModeOptionStruct[]?> ReadSupportedModesAsync(CancellationToken ct = default)
        => ReadArrayAttributeAsync(0x0000, ReadModeOptionStruct, ct);

    /// <summary>Read CurrentMode attribute (0x0001).</summary>
    public Task<byte> ReadCurrentModeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<byte>(0x0001, ct);
}
