// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: wifi-network-diagnostics-cluster.xml
// Cluster: Wi-Fi Network Diagnostics (0x0036)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Wi-Fi Network Diagnostics (0x0036, rev 1)</summary>
public class WiFiNetworkDiagnosticsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0036;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="WiFiNetworkDiagnosticsCluster"/> bound to the given session and endpoint.</summary>
    public WiFiNetworkDiagnosticsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Node makes available the counts for the number of received and transmitted packets on the Wi-Fi interface.</summary>
        PacketCounts = 1u << 0,
        /// <summary>Node makes available the counts for the number of errors that have occurred during the reception and transmission of packets on the Wi-Fi interface.</summary>
        ErrorCounts = 1u << 1,
    }

    /// <summary>SecurityTypeEnum enum values.</summary>
    public enum SecurityTypeEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>None value.</summary>
        None = 0x01,
        /// <summary>WEP value.</summary>
        WEP = 0x02,
        /// <summary>WPA value.</summary>
        WPA = 0x03,
        /// <summary>WPA2 value.</summary>
        WPA2 = 0x04,
        /// <summary>WPA3 value.</summary>
        WPA3 = 0x05,
    }

    /// <summary>WiFiVersionEnum enum values.</summary>
    public enum WiFiVersionEnum : byte
    {
        /// <summary>a value.</summary>
        A = 0x00,
        /// <summary>b value.</summary>
        B = 0x01,
        /// <summary>g value.</summary>
        G = 0x02,
        /// <summary>n value.</summary>
        N = 0x03,
        /// <summary>ac value.</summary>
        Ac = 0x04,
        /// <summary>ax value.</summary>
        Ax = 0x05,
        /// <summary>ah value.</summary>
        Ah = 0x06,
    }

    /// <summary>AssociationFailureCauseEnum enum values.</summary>
    public enum AssociationFailureCauseEnum : byte
    {
        /// <summary>Unknown value.</summary>
        Unknown = 0x00,
        /// <summary>AssociationFailed value.</summary>
        AssociationFailed = 0x01,
        /// <summary>AuthenticationFailed value.</summary>
        AuthenticationFailed = 0x02,
        /// <summary>SsidNotFound value.</summary>
        SsidNotFound = 0x03,
    }

    /// <summary>ConnectionStatusEnum enum values.</summary>
    public enum ConnectionStatusEnum : byte
    {
        /// <summary>Connected value.</summary>
        Connected = 0x00,
        /// <summary>NotConnected value.</summary>
        NotConnected = 0x01,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>BSSID (0x0000).</summary>
        public const uint BSSID = 0x0000;
        /// <summary>SecurityType (0x0001).</summary>
        public const uint SecurityType = 0x0001;
        /// <summary>WiFiVersion (0x0002).</summary>
        public const uint WiFiVersion = 0x0002;
        /// <summary>ChannelNumber (0x0003).</summary>
        public const uint ChannelNumber = 0x0003;
        /// <summary>RSSI (0x0004).</summary>
        public const uint RSSI = 0x0004;
        /// <summary>BeaconLostCount (0x0005).</summary>
        public const uint BeaconLostCount = 0x0005;
        /// <summary>BeaconRxCount (0x0006).</summary>
        public const uint BeaconRxCount = 0x0006;
        /// <summary>PacketMulticastRxCount (0x0007).</summary>
        public const uint PacketMulticastRxCount = 0x0007;
        /// <summary>PacketMulticastTxCount (0x0008).</summary>
        public const uint PacketMulticastTxCount = 0x0008;
        /// <summary>PacketUnicastRxCount (0x0009).</summary>
        public const uint PacketUnicastRxCount = 0x0009;
        /// <summary>PacketUnicastTxCount (0x000A).</summary>
        public const uint PacketUnicastTxCount = 0x000A;
        /// <summary>CurrentMaxRate (0x000B).</summary>
        public const uint CurrentMaxRate = 0x000B;
        /// <summary>OverrunCount (0x000C).</summary>
        public const uint OverrunCount = 0x000C;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>ResetCounts (0x0000).</summary>
        public const uint ResetCounts = 0x0000;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>Disconnection (0x0000).</summary>
        public const uint Disconnection = 0x0000;
        /// <summary>AssociationFailure (0x0001).</summary>
        public const uint AssociationFailure = 0x0001;
        /// <summary>ConnectionStatus (0x0002).</summary>
        public const uint ConnectionStatus = 0x0002;
    }

    // Async command methods

    /// <summary>Send ResetCounts command (0x0000).</summary>
    public Task<InvokeResponse> ResetCountsAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    // Attribute readers

    /// <summary>Read BSSID attribute (0x0000).</summary>
    public Task<byte[]?> ReadBSSIDAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<byte[]>(0x0000, ct);

    /// <summary>Read SecurityType attribute (0x0001).</summary>
    public Task<SecurityTypeEnum> ReadSecurityTypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<SecurityTypeEnum>(0x0001, ct);

    /// <summary>Read WiFiVersion attribute (0x0002).</summary>
    public Task<WiFiVersionEnum> ReadWiFiVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<WiFiVersionEnum>(0x0002, ct);

    /// <summary>Read ChannelNumber attribute (0x0003).</summary>
    public Task<ushort?> ReadChannelNumberAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0003, ct);

    /// <summary>Read RSSI attribute (0x0004).</summary>
    public Task<sbyte?> ReadRSSIAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<sbyte>(0x0004, ct);

    /// <summary>Read BeaconLostCount attribute (0x0005).</summary>
    public Task<uint?> ReadBeaconLostCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0005, ct);

    /// <summary>Read BeaconRxCount attribute (0x0006).</summary>
    public Task<uint?> ReadBeaconRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0006, ct);

    /// <summary>Read PacketMulticastRxCount attribute (0x0007).</summary>
    public Task<uint?> ReadPacketMulticastRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0007, ct);

    /// <summary>Read PacketMulticastTxCount attribute (0x0008).</summary>
    public Task<uint?> ReadPacketMulticastTxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0008, ct);

    /// <summary>Read PacketUnicastRxCount attribute (0x0009).</summary>
    public Task<uint?> ReadPacketUnicastRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0009, ct);

    /// <summary>Read PacketUnicastTxCount attribute (0x000A).</summary>
    public Task<uint?> ReadPacketUnicastTxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x000A, ct);

    /// <summary>Read CurrentMaxRate attribute (0x000B).</summary>
    public Task<ulong?> ReadCurrentMaxRateAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000B, ct);

    /// <summary>Read OverrunCount attribute (0x000C).</summary>
    public Task<ulong?> ReadOverrunCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000C, ct);
}
