// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: wifi-network-diagnostics-cluster.xml
// Cluster: Wi-Fi Network Diagnostics (0x0036)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;
using System.Text.Json.Nodes;

namespace DotMatter.Core.Clusters;

/// <summary>Wi-Fi Network Diagnostics (0x0036, rev 1)</summary>
public class WiFiNetworkDiagnosticsCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0036;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="WiFiNetworkDiagnosticsCluster"/> bound to the given session and endpoint.</summary>
    public WiFiNetworkDiagnosticsCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Node makes available the counts for the number of received and transmitted packets on the Wi-Fi interface.</summary>
        PacketCounts = 1u << 0,
        /// <summary>Node makes available the counts for the number of errors that have occurred during the reception and transmission of packets on the Wi-Fi interface.</summary>
        ErrorCounts = 1u << 1,
    }

    /// <summary>SecurityTypeEnum enum values.</summary>
    public enum SecurityTypeEnum : byte
    {
        /// <summary>Unspecified value.</summary>
        Unspecified = 0x00,
        /// <summary>None value.</summary>
        None = 0x01,
        /// <summary>WEP value.</summary>
        WEP = 0x02,
        /// <summary>WPA value.</summary>
        WPA = 0x03,
        /// <summary>WPA2 value.</summary>
        WPA2 = 0x04,
        /// <summary>WPA3 value.</summary>
        WPA3 = 0x05,
    }

    /// <summary>WiFiVersionEnum enum values.</summary>
    public enum WiFiVersionEnum : byte
    {
        /// <summary>a value.</summary>
        A = 0x00,
        /// <summary>b value.</summary>
        B = 0x01,
        /// <summary>g value.</summary>
        G = 0x02,
        /// <summary>n value.</summary>
        N = 0x03,
        /// <summary>ac value.</summary>
        Ac = 0x04,
        /// <summary>ax value.</summary>
        Ax = 0x05,
        /// <summary>ah value.</summary>
        Ah = 0x06,
    }

    /// <summary>AssociationFailureCauseEnum enum values.</summary>
    public enum AssociationFailureCauseEnum : byte
    {
        /// <summary>Unknown value.</summary>
        Unknown = 0x00,
        /// <summary>AssociationFailed value.</summary>
        AssociationFailed = 0x01,
        /// <summary>AuthenticationFailed value.</summary>
        AuthenticationFailed = 0x02,
        /// <summary>SsidNotFound value.</summary>
        SsidNotFound = 0x03,
    }

    /// <summary>ConnectionStatusEnum enum values.</summary>
    public enum ConnectionStatusEnum : byte
    {
        /// <summary>Connected value.</summary>
        Connected = 0x00,
        /// <summary>NotConnected value.</summary>
        NotConnected = 0x01,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>BSSID (0x0000).</summary>
        public const uint BSSID = 0x0000;
        /// <summary>SecurityType (0x0001).</summary>
        public const uint SecurityType = 0x0001;
        /// <summary>WiFiVersion (0x0002).</summary>
        public const uint WiFiVersion = 0x0002;
        /// <summary>ChannelNumber (0x0003).</summary>
        public const uint ChannelNumber = 0x0003;
        /// <summary>RSSI (0x0004).</summary>
        public const uint RSSI = 0x0004;
        /// <summary>BeaconLostCount (0x0005).</summary>
        public const uint BeaconLostCount = 0x0005;
        /// <summary>BeaconRxCount (0x0006).</summary>
        public const uint BeaconRxCount = 0x0006;
        /// <summary>PacketMulticastRxCount (0x0007).</summary>
        public const uint PacketMulticastRxCount = 0x0007;
        /// <summary>PacketMulticastTxCount (0x0008).</summary>
        public const uint PacketMulticastTxCount = 0x0008;
        /// <summary>PacketUnicastRxCount (0x0009).</summary>
        public const uint PacketUnicastRxCount = 0x0009;
        /// <summary>PacketUnicastTxCount (0x000A).</summary>
        public const uint PacketUnicastTxCount = 0x000A;
        /// <summary>CurrentMaxRate (0x000B).</summary>
        public const uint CurrentMaxRate = 0x000B;
        /// <summary>OverrunCount (0x000C).</summary>
        public const uint OverrunCount = 0x000C;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>ResetCounts (0x0000).</summary>
        public const uint ResetCounts = 0x0000;
    }

    /// <summary>Event identifiers.</summary>
    public static class Events
    {
        /// <summary>Disconnection (0x0000).</summary>
        public const uint Disconnection = 0x0000;
        /// <summary>AssociationFailure (0x0001).</summary>
        public const uint AssociationFailure = 0x0001;
        /// <summary>ConnectionStatus (0x0002).</summary>
        public const uint ConnectionStatus = 0x0002;
    }

    /// <summary>Base type for this cluster's event reports.</summary>
    public abstract class ClusterEvent
        : MatterClusterEvent
    {
        /// <summary>Initializes a new cluster event wrapper.</summary>
        protected ClusterEvent(MatterEventReport report, string eventName)
            : base(report, "Wi-Fi Network Diagnostics", eventName) { }
    }

    /// <summary>Fallback event wrapper when DotMatter cannot parse a typed payload.</summary>
    public sealed class UnknownClusterEvent(MatterEventReport report, string? reason = null)
        : ClusterEvent(report, "Unknown")
    {
        /// <summary>Gets the reason the typed payload parser could not materialize this event.</summary>
        public override string? Reason { get; } = reason;
    }

    /// <summary>Disconnection event payload.</summary>
    public sealed class DisconnectionEventData
    {
        /// <summary>Gets or sets ReasonCode.</summary>
        public ushort ReasonCode { get; set; }
    }

    /// <summary>Disconnection event report.</summary>
    public sealed class DisconnectionEvent(MatterEventReport report, DisconnectionEventData payload)
        : ClusterEvent(report, "Disconnection")
    {
        /// <summary>Gets the typed Disconnection payload.</summary>
        public DisconnectionEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>AssociationFailure event payload.</summary>
    public sealed class AssociationFailureEventData
    {
        /// <summary>Gets or sets AssociationFailureCause.</summary>
        public AssociationFailureCauseEnum AssociationFailureCause { get; set; } = default!;
        /// <summary>Gets or sets Status.</summary>
        public ushort Status { get; set; }
    }

    /// <summary>AssociationFailure event report.</summary>
    public sealed class AssociationFailureEvent(MatterEventReport report, AssociationFailureEventData payload)
        : ClusterEvent(report, "AssociationFailure")
    {
        /// <summary>Gets the typed AssociationFailure payload.</summary>
        public AssociationFailureEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    /// <summary>ConnectionStatus event payload.</summary>
    public sealed class ConnectionStatusEventData
    {
        /// <summary>Gets or sets ConnectionStatus.</summary>
        public ConnectionStatusEnum ConnectionStatus { get; set; } = default!;
    }

    /// <summary>ConnectionStatus event report.</summary>
    public sealed class ConnectionStatusEvent(MatterEventReport report, ConnectionStatusEventData payload)
        : ClusterEvent(report, "ConnectionStatus")
    {
        /// <summary>Gets the typed ConnectionStatus payload.</summary>
        public ConnectionStatusEventData Payload { get; } = payload;

        /// <inheritdoc />
        public override object? TypedPayload => Payload;
    }

    // Async command methods

    /// <summary>Send ResetCounts command (0x0000).</summary>
    public Task<InvokeResponse> ResetCountsAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    // Attribute readers

    /// <summary>Read BSSID attribute (0x0000).</summary>
    public Task<byte[]?> ReadBSSIDAsync(CancellationToken ct = default)
        => ReadRefAttributeAsync<byte[]>(0x0000, ct);

    /// <summary>Read SecurityType attribute (0x0001).</summary>
    public Task<SecurityTypeEnum> ReadSecurityTypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<SecurityTypeEnum>(0x0001, ct);

    /// <summary>Read WiFiVersion attribute (0x0002).</summary>
    public Task<WiFiVersionEnum> ReadWiFiVersionAsync(CancellationToken ct = default)
        => ReadAttributeAsync<WiFiVersionEnum>(0x0002, ct);

    /// <summary>Read ChannelNumber attribute (0x0003).</summary>
    public Task<ushort?> ReadChannelNumberAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0003, ct);

    /// <summary>Read RSSI attribute (0x0004).</summary>
    public Task<sbyte?> ReadRSSIAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<sbyte>(0x0004, ct);

    /// <summary>Read BeaconLostCount attribute (0x0005).</summary>
    public Task<uint?> ReadBeaconLostCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0005, ct);

    /// <summary>Read BeaconRxCount attribute (0x0006).</summary>
    public Task<uint?> ReadBeaconRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0006, ct);

    /// <summary>Read PacketMulticastRxCount attribute (0x0007).</summary>
    public Task<uint?> ReadPacketMulticastRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0007, ct);

    /// <summary>Read PacketMulticastTxCount attribute (0x0008).</summary>
    public Task<uint?> ReadPacketMulticastTxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0008, ct);

    /// <summary>Read PacketUnicastRxCount attribute (0x0009).</summary>
    public Task<uint?> ReadPacketUnicastRxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x0009, ct);

    /// <summary>Read PacketUnicastTxCount attribute (0x000A).</summary>
    public Task<uint?> ReadPacketUnicastTxCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<uint>(0x000A, ct);

    /// <summary>Read CurrentMaxRate attribute (0x000B).</summary>
    public Task<ulong?> ReadCurrentMaxRateAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000B, ct);

    /// <summary>Read OverrunCount attribute (0x000C).</summary>
    public Task<ulong?> ReadOverrunCountAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ulong>(0x000C, ct);

    // Event payload parsers

    private static DisconnectionEventData ReadDisconnectionEventData(MatterTLV tlv)
    {
        var value = new DisconnectionEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ReasonCode = (ushort)tlv.GetUnsignedIntAny(0);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadDisconnectionEventData(MatterEventReport report, out DisconnectionEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadDisconnectionEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "Disconnection payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static AssociationFailureEventData ReadAssociationFailureEventData(MatterTLV tlv)
    {
        var value = new AssociationFailureEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.AssociationFailureCause = (AssociationFailureCauseEnum)tlv.GetUnsignedIntAny(0);
                    break;
                case 1:
                    value.Status = (ushort)tlv.GetUnsignedIntAny(1);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadAssociationFailureEventData(MatterEventReport report, out AssociationFailureEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadAssociationFailureEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "AssociationFailure payload parse failed: " + ex.Message;
            return false;
        }
    }

    private static ConnectionStatusEventData ReadConnectionStatusEventData(MatterTLV tlv)
    {
        var value = new ConnectionStatusEventData();
        tlv.OpenStructure(7);
        while (!tlv.IsEndContainerNext())
        {
            switch (tlv.PeekTag())
            {
                case 0:
                    value.ConnectionStatus = (ConnectionStatusEnum)tlv.GetUnsignedIntAny(0);
                    break;
                default:
                    tlv.SkipElement();
                    break;
            }
        }

        tlv.CloseContainer();
        return value;
    }

    private static bool TryReadConnectionStatusEventData(MatterEventReport report, out ConnectionStatusEventData? payload, out string? reason)
    {
        payload = null;
        if (report.RawData is null)
        {
            reason = "Event payload TLV was not captured.";
            return false;
        }

        try
        {
            payload = ReadConnectionStatusEventData(new MatterTLV(report.RawData.GetBytes()));
            reason = null;
            return true;
        }
        catch (Exception ex)
        {
            reason = "ConnectionStatus payload parse failed: " + ex.Message;
            return false;
        }
    }

    // Event payload JSON projectors

    private static JsonObject CreateDisconnectionEventDataJson(DisconnectionEventData value)
    {
        var json = new JsonObject();
        json["reasonCode"] = CreateJsonValue(value.ReasonCode);
        return json;
    }

    private static JsonObject CreateAssociationFailureEventDataJson(AssociationFailureEventData value)
    {
        var json = new JsonObject();
        if (value.AssociationFailureCause is { } associationFailureCause)
        {
            json["associationFailureCause"] = CreateJsonValue(associationFailureCause.ToString());
        }
        json["status"] = CreateJsonValue(value.Status);
        return json;
    }

    private static JsonObject CreateConnectionStatusEventDataJson(ConnectionStatusEventData value)
    {
        var json = new JsonObject();
        if (value.ConnectionStatus is { } connectionStatus)
        {
            json["connectionStatus"] = CreateJsonValue(connectionStatus.ToString());
        }
        return json;
    }

    internal static JsonObject? MapEventPayloadJson(ClusterEvent evt)
    {
        return evt switch
        {
            DisconnectionEvent typed => CreateDisconnectionEventDataJson(typed.Payload),
            AssociationFailureEvent typed => CreateAssociationFailureEventDataJson(typed.Payload),
            ConnectionStatusEvent typed => CreateConnectionStatusEventDataJson(typed.Payload),
            _ => null,
        };
    }

    // Event readers and subscriptions

    /// <summary>Read event reports from this cluster.</summary>
    public async Task<ClusterEvent[]> ReadEventsAsync(
        uint[]? eventIds = null,
        bool fabricFiltered = false,
        CancellationToken ct = default)
    {
        var events = await ReadEventsAsync(MapEventReports, eventIds, fabricFiltered, ct);
        return [.. events];
    }

    /// <summary>Subscribe to event reports from this cluster.</summary>
    public Task<MatterEventSubscription<ClusterEvent>> SubscribeEventsAsync(
        uint[]? eventIds = null,
        ushort minInterval = 1,
        ushort maxInterval = 60,
        bool fabricFiltered = false,
        CancellationToken ct = default)
        => SubscribeEventsAsync(MapEventReports, eventIds, minInterval, maxInterval, fabricFiltered, ct);

    internal static ClusterEvent[] MapEventReports(IReadOnlyList<MatterEventReport> reports)
    {
        if (reports.Count == 0)
        {
            return [];
        }

        var events = new List<ClusterEvent>(reports.Count);
        foreach (var report in reports)
        {
            events.Add(MapEventReport(report));
        }

        return [.. events];
    }

    internal static ClusterEvent MapEventReport(MatterEventReport report)
    {
        return report.EventId switch
        {
            Events.Disconnection when TryReadDisconnectionEventData(report, out var disconnectionEventData, out _) => new DisconnectionEvent(report, disconnectionEventData!),
            Events.Disconnection when TryReadDisconnectionEventData(report, out _, out var disconnectionReason) => new UnknownClusterEvent(report, disconnectionReason),
            Events.AssociationFailure when TryReadAssociationFailureEventData(report, out var associationFailureEventData, out _) => new AssociationFailureEvent(report, associationFailureEventData!),
            Events.AssociationFailure when TryReadAssociationFailureEventData(report, out _, out var associationFailureReason) => new UnknownClusterEvent(report, associationFailureReason),
            Events.ConnectionStatus when TryReadConnectionStatusEventData(report, out var connectionStatusEventData, out _) => new ConnectionStatusEvent(report, connectionStatusEventData!),
            Events.ConnectionStatus when TryReadConnectionStatusEventData(report, out _, out var connectionStatusReason) => new UnknownClusterEvent(report, connectionStatusReason),
            _ => new UnknownClusterEvent(report, "Event ID is not recognized by this cluster."),
        };
    }
}
