// <auto-generated/>
// Generated by DotMatter.CodeGen from CHIP SDK v1.5 (connectedhomeip).
// XML: window-covering.xml
// Cluster: Window Covering (0x0102)
// To regenerate: dotnet run --project DotMatter.CodeGen

#nullable enable

using DotMatter.Core.InteractionModel;
using DotMatter.Core.Sessions;
using DotMatter.Core.TLV;

namespace DotMatter.Core.Clusters;

/// <summary>Window Covering (0x0102, rev 5)</summary>
public class WindowCoveringCluster : ClusterBase
{
    /// <summary>Matter cluster identifier.</summary>
    public const uint ClusterId = 0x0102;

    /// <inheritdoc />
    protected override uint GetClusterId() => ClusterId;

    /// <summary>Creates a new <see cref="WindowCoveringCluster"/> bound to the given session and endpoint.</summary>
    public WindowCoveringCluster(ISession session, ushort endpointId = 1)
        : base(session, endpointId) { }

    /// <summary>Feature flags for this cluster.</summary>
    [System.Flags]
    public enum Feature : uint
    {
        /// <summary>Lift control and behavior for lifting/sliding window coverings</summary>
        Lift = 1u << 0,
        /// <summary>Tilt control and behavior for tilting window coverings</summary>
        Tilt = 1u << 1,
        /// <summary>Position aware lift control is supported.</summary>
        PositionAwareLift = 1u << 2,
        /// <summary>Absolute positioning is supported.</summary>
        AbsolutePosition = 1u << 3,
        /// <summary>Position aware tilt control is supported.</summary>
        PositionAwareTilt = 1u << 4,
    }

    /// <summary>Type enum values.</summary>
    public enum Type : byte
    {
        /// <summary>RollerShade value.</summary>
        RollerShade = 0x00,
        /// <summary>RollerShade2Motor value.</summary>
        RollerShade2Motor = 0x01,
        /// <summary>RollerShadeExterior value.</summary>
        RollerShadeExterior = 0x02,
        /// <summary>RollerShadeExterior2Motor value.</summary>
        RollerShadeExterior2Motor = 0x03,
        /// <summary>Drapery value.</summary>
        Drapery = 0x04,
        /// <summary>Awning value.</summary>
        Awning = 0x05,
        /// <summary>Shutter value.</summary>
        Shutter = 0x06,
        /// <summary>TiltBlindTiltOnly value.</summary>
        TiltBlindTiltOnly = 0x07,
        /// <summary>TiltBlindLiftAndTilt value.</summary>
        TiltBlindLiftAndTilt = 0x08,
        /// <summary>ProjectorScreen value.</summary>
        ProjectorScreen = 0x09,
        /// <summary>Unknown value.</summary>
        Unknown = 0xFF,
    }

    /// <summary>EndProductType enum values.</summary>
    public enum EndProductType : byte
    {
        /// <summary>RollerShade value.</summary>
        RollerShade = 0x00,
        /// <summary>RomanShade value.</summary>
        RomanShade = 0x01,
        /// <summary>BalloonShade value.</summary>
        BalloonShade = 0x02,
        /// <summary>WovenWood value.</summary>
        WovenWood = 0x03,
        /// <summary>PleatedShade value.</summary>
        PleatedShade = 0x04,
        /// <summary>CellularShade value.</summary>
        CellularShade = 0x05,
        /// <summary>LayeredShade value.</summary>
        LayeredShade = 0x06,
        /// <summary>LayeredShade2D value.</summary>
        LayeredShade2D = 0x07,
        /// <summary>SheerShade value.</summary>
        SheerShade = 0x08,
        /// <summary>TiltOnlyInteriorBlind value.</summary>
        TiltOnlyInteriorBlind = 0x09,
        /// <summary>InteriorBlind value.</summary>
        InteriorBlind = 0x0A,
        /// <summary>VerticalBlindStripCurtain value.</summary>
        VerticalBlindStripCurtain = 0x0B,
        /// <summary>InteriorVenetianBlind value.</summary>
        InteriorVenetianBlind = 0x0C,
        /// <summary>ExteriorVenetianBlind value.</summary>
        ExteriorVenetianBlind = 0x0D,
        /// <summary>LateralLeftCurtain value.</summary>
        LateralLeftCurtain = 0x0E,
        /// <summary>LateralRightCurtain value.</summary>
        LateralRightCurtain = 0x0F,
        /// <summary>CentralCurtain value.</summary>
        CentralCurtain = 0x10,
        /// <summary>RollerShutter value.</summary>
        RollerShutter = 0x11,
        /// <summary>ExteriorVerticalScreen value.</summary>
        ExteriorVerticalScreen = 0x12,
        /// <summary>AwningTerracePatio value.</summary>
        AwningTerracePatio = 0x13,
        /// <summary>AwningVerticalScreen value.</summary>
        AwningVerticalScreen = 0x14,
        /// <summary>TiltOnlyPergola value.</summary>
        TiltOnlyPergola = 0x15,
        /// <summary>SwingingShutter value.</summary>
        SwingingShutter = 0x16,
        /// <summary>SlidingShutter value.</summary>
        SlidingShutter = 0x17,
        /// <summary>Unknown value.</summary>
        Unknown = 0xFF,
    }

    /// <summary>Mode bitmap flags.</summary>
    [System.Flags]
    public enum Mode : uint
    {
        /// <summary>MotorDirectionReversed flag.</summary>
        MotorDirectionReversed = 1u << 0,
        /// <summary>CalibrationMode flag.</summary>
        CalibrationMode = 1u << 1,
        /// <summary>MaintenanceMode flag.</summary>
        MaintenanceMode = 1u << 2,
        /// <summary>LedFeedback flag.</summary>
        LedFeedback = 1u << 3,
    }

    /// <summary>OperationalStatus bitmap flags.</summary>
    [System.Flags]
    public enum OperationalStatus : uint
    {
        /// <summary>Global flag.</summary>
        Global = 1u << 0,
        /// <summary>Lift flag.</summary>
        Lift = 1u << 2,
        /// <summary>Tilt flag.</summary>
        Tilt = 1u << 4,
    }

    /// <summary>ConfigStatus bitmap flags.</summary>
    [System.Flags]
    public enum ConfigStatus : uint
    {
        /// <summary>Operational flag.</summary>
        Operational = 1u << 0,
        /// <summary>OnlineReserved flag.</summary>
        OnlineReserved = 1u << 1,
        /// <summary>LiftMovementReversed flag.</summary>
        LiftMovementReversed = 1u << 2,
        /// <summary>LiftPositionAware flag.</summary>
        LiftPositionAware = 1u << 3,
        /// <summary>TiltPositionAware flag.</summary>
        TiltPositionAware = 1u << 4,
        /// <summary>LiftEncoderControlled flag.</summary>
        LiftEncoderControlled = 1u << 5,
        /// <summary>TiltEncoderControlled flag.</summary>
        TiltEncoderControlled = 1u << 6,
    }

    /// <summary>SafetyStatus bitmap flags.</summary>
    [System.Flags]
    public enum SafetyStatus : uint
    {
        /// <summary>RemoteLockout flag.</summary>
        RemoteLockout = 1u << 0,
        /// <summary>TamperDetection flag.</summary>
        TamperDetection = 1u << 1,
        /// <summary>FailedCommunication flag.</summary>
        FailedCommunication = 1u << 2,
        /// <summary>PositionFailure flag.</summary>
        PositionFailure = 1u << 3,
        /// <summary>ThermalProtection flag.</summary>
        ThermalProtection = 1u << 4,
        /// <summary>ObstacleDetected flag.</summary>
        ObstacleDetected = 1u << 5,
        /// <summary>Power flag.</summary>
        Power = 1u << 6,
        /// <summary>StopInput flag.</summary>
        StopInput = 1u << 7,
        /// <summary>MotorJammed flag.</summary>
        MotorJammed = 1u << 8,
        /// <summary>HardwareFailure flag.</summary>
        HardwareFailure = 1u << 9,
        /// <summary>ManualOperation flag.</summary>
        ManualOperation = 1u << 10,
        /// <summary>Protection flag.</summary>
        Protection = 1u << 11,
    }

    /// <summary>Attribute identifiers.</summary>
    public static class Attributes
    {
        /// <summary>Type (0x0000).</summary>
        public const uint Type = 0x0000;
        /// <summary>PhysicalClosedLimitLift (0x0001).</summary>
        public const uint PhysicalClosedLimitLift = 0x0001;
        /// <summary>PhysicalClosedLimitTilt (0x0002).</summary>
        public const uint PhysicalClosedLimitTilt = 0x0002;
        /// <summary>CurrentPositionLift (0x0003).</summary>
        public const uint CurrentPositionLift = 0x0003;
        /// <summary>CurrentPositionTilt (0x0004).</summary>
        public const uint CurrentPositionTilt = 0x0004;
        /// <summary>NumberOfActuationsLift (0x0005).</summary>
        public const uint NumberOfActuationsLift = 0x0005;
        /// <summary>NumberOfActuationsTilt (0x0006).</summary>
        public const uint NumberOfActuationsTilt = 0x0006;
        /// <summary>ConfigStatus (0x0007).</summary>
        public const uint ConfigStatus = 0x0007;
        /// <summary>CurrentPositionLiftPercentage (0x0008).</summary>
        public const uint CurrentPositionLiftPercentage = 0x0008;
        /// <summary>CurrentPositionTiltPercentage (0x0009).</summary>
        public const uint CurrentPositionTiltPercentage = 0x0009;
        /// <summary>OperationalStatus (0x000A).</summary>
        public const uint OperationalStatus = 0x000A;
        /// <summary>TargetPositionLiftPercent100ths (0x000B).</summary>
        public const uint TargetPositionLiftPercent100ths = 0x000B;
        /// <summary>TargetPositionTiltPercent100ths (0x000C).</summary>
        public const uint TargetPositionTiltPercent100ths = 0x000C;
        /// <summary>EndProductType (0x000D).</summary>
        public const uint EndProductType = 0x000D;
        /// <summary>CurrentPositionLiftPercent100ths (0x000E).</summary>
        public const uint CurrentPositionLiftPercent100ths = 0x000E;
        /// <summary>CurrentPositionTiltPercent100ths (0x000F).</summary>
        public const uint CurrentPositionTiltPercent100ths = 0x000F;
        /// <summary>InstalledOpenLimitLift (0x0010).</summary>
        public const uint InstalledOpenLimitLift = 0x0010;
        /// <summary>InstalledClosedLimitLift (0x0011).</summary>
        public const uint InstalledClosedLimitLift = 0x0011;
        /// <summary>InstalledOpenLimitTilt (0x0012).</summary>
        public const uint InstalledOpenLimitTilt = 0x0012;
        /// <summary>InstalledClosedLimitTilt (0x0013).</summary>
        public const uint InstalledClosedLimitTilt = 0x0013;
        /// <summary>Mode (0x0017).</summary>
        public const uint Mode = 0x0017;
        /// <summary>SafetyStatus (0x001A).</summary>
        public const uint SafetyStatus = 0x001A;
    }

    /// <summary>Command identifiers.</summary>
    public static class Commands
    {
        /// <summary>UpOrOpen (0x0000).</summary>
        public const uint UpOrOpen = 0x0000;
        /// <summary>DownOrClose (0x0001).</summary>
        public const uint DownOrClose = 0x0001;
        /// <summary>StopMotion (0x0002).</summary>
        public const uint StopMotion = 0x0002;
        /// <summary>GoToLiftValue (0x0004).</summary>
        public const uint GoToLiftValue = 0x0004;
        /// <summary>GoToLiftPercentage (0x0005).</summary>
        public const uint GoToLiftPercentage = 0x0005;
        /// <summary>GoToTiltValue (0x0007).</summary>
        public const uint GoToTiltValue = 0x0007;
        /// <summary>GoToTiltPercentage (0x0008).</summary>
        public const uint GoToTiltPercentage = 0x0008;
    }

    // Async command methods

    /// <summary>Send UpOrOpen command (0x0000).</summary>
    public Task<InvokeResponse> UpOrOpenAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0000, ct: ct);

    /// <summary>Send DownOrClose command (0x0001).</summary>
    public Task<InvokeResponse> DownOrCloseAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0001, ct: ct);

    /// <summary>Send StopMotion command (0x0002).</summary>
    public Task<InvokeResponse> StopMotionAsync(CancellationToken ct = default)
        => InvokeCommandAsync(0x0002, ct: ct);

    /// <summary>Send GoToLiftValue command (0x0004).</summary>
    public Task<InvokeResponse> GoToLiftValueAsync(
        ushort liftValue,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0004, tlv => { tlv.AddUInt16(0, liftValue); }, ct);

    /// <summary>Send GoToLiftPercentage command (0x0005).</summary>
    public Task<InvokeResponse> GoToLiftPercentageAsync(
        ushort liftPercent100thsValue,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0005, tlv => { tlv.AddUInt16(0, liftPercent100thsValue); }, ct);

    /// <summary>Send GoToTiltValue command (0x0007).</summary>
    public Task<InvokeResponse> GoToTiltValueAsync(
        ushort tiltValue,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0007, tlv => { tlv.AddUInt16(0, tiltValue); }, ct);

    /// <summary>Send GoToTiltPercentage command (0x0008).</summary>
    public Task<InvokeResponse> GoToTiltPercentageAsync(
        ushort tiltPercent100thsValue,
        CancellationToken ct = default)
        => InvokeCommandAsync(0x0008, tlv => { tlv.AddUInt16(0, tiltPercent100thsValue); }, ct);

    // Attribute readers

    /// <summary>Read Type attribute (0x0000).</summary>
    public Task<Type> ReadTypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<Type>(0x0000, ct);

    /// <summary>Read PhysicalClosedLimitLift attribute (0x0001).</summary>
    public Task<ushort> ReadPhysicalClosedLimitLiftAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0001, ct);

    /// <summary>Read PhysicalClosedLimitTilt attribute (0x0002).</summary>
    public Task<ushort> ReadPhysicalClosedLimitTiltAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0002, ct);

    /// <summary>Read CurrentPositionLift attribute (0x0003).</summary>
    public Task<ushort?> ReadCurrentPositionLiftAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0003, ct);

    /// <summary>Read CurrentPositionTilt attribute (0x0004).</summary>
    public Task<ushort?> ReadCurrentPositionTiltAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x0004, ct);

    /// <summary>Read NumberOfActuationsLift attribute (0x0005).</summary>
    public Task<ushort> ReadNumberOfActuationsLiftAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0005, ct);

    /// <summary>Read NumberOfActuationsTilt attribute (0x0006).</summary>
    public Task<ushort> ReadNumberOfActuationsTiltAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0006, ct);

    /// <summary>Read ConfigStatus attribute (0x0007).</summary>
    public Task<ConfigStatus> ReadConfigStatusAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ConfigStatus>(0x0007, ct);

    /// <summary>Read CurrentPositionLiftPercentage attribute (0x0008).</summary>
    public Task<byte?> ReadCurrentPositionLiftPercentageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<byte>(0x0008, ct);

    /// <summary>Read CurrentPositionTiltPercentage attribute (0x0009).</summary>
    public Task<byte?> ReadCurrentPositionTiltPercentageAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<byte>(0x0009, ct);

    /// <summary>Read OperationalStatus attribute (0x000A).</summary>
    public Task<OperationalStatus> ReadOperationalStatusAsync(CancellationToken ct = default)
        => ReadAttributeAsync<OperationalStatus>(0x000A, ct);

    /// <summary>Read TargetPositionLiftPercent100ths attribute (0x000B).</summary>
    public Task<ushort?> ReadTargetPositionLiftPercent100thsAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x000B, ct);

    /// <summary>Read TargetPositionTiltPercent100ths attribute (0x000C).</summary>
    public Task<ushort?> ReadTargetPositionTiltPercent100thsAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x000C, ct);

    /// <summary>Read EndProductType attribute (0x000D).</summary>
    public Task<EndProductType> ReadEndProductTypeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<EndProductType>(0x000D, ct);

    /// <summary>Read CurrentPositionLiftPercent100ths attribute (0x000E).</summary>
    public Task<ushort?> ReadCurrentPositionLiftPercent100thsAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x000E, ct);

    /// <summary>Read CurrentPositionTiltPercent100ths attribute (0x000F).</summary>
    public Task<ushort?> ReadCurrentPositionTiltPercent100thsAsync(CancellationToken ct = default)
        => ReadNullableAttributeAsync<ushort>(0x000F, ct);

    /// <summary>Read InstalledOpenLimitLift attribute (0x0010).</summary>
    public Task<ushort> ReadInstalledOpenLimitLiftAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0010, ct);

    /// <summary>Read InstalledClosedLimitLift attribute (0x0011).</summary>
    public Task<ushort> ReadInstalledClosedLimitLiftAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0011, ct);

    /// <summary>Read InstalledOpenLimitTilt attribute (0x0012).</summary>
    public Task<ushort> ReadInstalledOpenLimitTiltAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0012, ct);

    /// <summary>Read InstalledClosedLimitTilt attribute (0x0013).</summary>
    public Task<ushort> ReadInstalledClosedLimitTiltAsync(CancellationToken ct = default)
        => ReadAttributeAsync<ushort>(0x0013, ct);

    /// <summary>Read Mode attribute (0x0017).</summary>
    public Task<Mode> ReadModeAsync(CancellationToken ct = default)
        => ReadAttributeAsync<Mode>(0x0017, ct);

    /// <summary>Read SafetyStatus attribute (0x001A).</summary>
    public Task<SafetyStatus> ReadSafetyStatusAsync(CancellationToken ct = default)
        => ReadAttributeAsync<SafetyStatus>(0x001A, ct);

    // Attribute writers

    /// <summary>Write Mode attribute (0x0017).</summary>
    public Task<WriteResponse> WriteModeAsync(
        Mode mode,
        bool timedRequest = true,
        ushort timedTimeoutMs = 5000,
        CancellationToken ct = default)
        => WriteAttributeAsync(0x0017, tlv =>
        {
            ArgumentNullException.ThrowIfNull(mode);
            tlv.AddUInt8(2, (byte)mode);
        }, timedRequest, timedTimeoutMs, ct);
}
